### ISSUE TITLE
[ATC Paper] Request for Experiments

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1006]
1. Device B, memory bandwidth experiments, redo with BIG CORES ONLY. (the values are way too strange. it is way TOO slow compared to Device C. Check the cpufreq/devfreq again please.) The value could be skewed by little cores.

**Comment by wooksong** [comment]
@myungjoo You got me right. The values in the manuscript is updated. FYI, the values for the big cores only are 2.62 and 4.08 GiB/s while the values for the little cores only are 0.406 and 1.102 GiB/s.

**Comment by myungjoo** [comment]
@wooksong Ok then, please make sure the values of 8890 are from BIG CORES only as well.

**Comment by wooksong** [comment]
@myungjoo I found something interesting while repeatedly running pmbw on 8890. It seems that the results could be shared after performing the same experiments on XU4.

**Comment by wooksong** [comment]
Note that X-axis represents array size in log scale (Array Size log 2 [B]).

## XU4 ##
In the case of XU4, the values mentioned in https://github.com/nnsuite/nnstreamer/issues/1006#issuecomment-449698578 are quite reasonable.

**Read**
![xu4bigread](https://user-images.githubusercontent.com/2772376/50508637-0c704f00-0ac6-11e9-9b3a-74e3d6dd06bc.png)

**Write**
![xu4bigwrite](https://user-images.githubusercontent.com/2772376/50508644-11cd9980-0ac6-11e9-9fe5-b9b73a9f536b.png)

## 8890 ##
In the case of 8890, the results differ from measurement to measurement.

**Read**
The average is 5.70 GiB/s when the array size is 2^31.
![8890bigread](https://user-images.githubusercontent.com/2772376/50508719-5b1de900-0ac6-11e9-96f3-92bce18a2579.png)

**Write**
The average is 6.32 GiB/s when the array size is 2^31.
![8890bigwrite](https://user-images.githubusercontent.com/2772376/50508655-1c882e80-0ac6-11e9-955b-83396e7dae50.png)

**Comment by myungjoo** [comment]
Results for x64 are missing..

**Comment by wooksong** [comment]
@myungjoo @again4you's machine is the target for x64.

**Comment by myungjoo** [comment]
@again4you Please report the results from your machine directly to the .tex file.

**Comment by myungjoo** [comment]
Paper Submitted. Thank you everyone!
