### ISSUE TITLE
[Filter/Tensorflow] trouble at avoiding memcpy

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#1016]
Currently, I'm trying to remove `memcpy` at the input/output processing of tensorflow.
https://github.com/nnsuite/nnstreamer/blob/b3ac8123a09032013d12b05e9e7e2243087b46ba/gst/tensor_filter/tensor_filter_tensorflow_core.cc#L366-L374

To solve this problem, I have tested `c_api` rather than ordinary APIs.
There is only one improvement: `memcpy` for the input tensor could be removed.
Unfortunately, I couldn't find the way to remove `memcpy` for the output tensor because of below reason.
```bash
---------------------------------------------------------------
c_api.cc:2569
---------------------------------------------------------------
void TF_SessionRun(TF_Session* session, const TF_Buffer* run_options,
                   const TF_Output* inputs, TF_Tensor* const* input_values,
                   int ninputs, const TF_Output* outputs,
                   TF_Tensor** output_values, int noutputs,
                   const TF_Operation* const* target_opers, int ntargets,
                   TF_Buffer* run_metadata, TF_Status* status) {
  // TODO(josh11b,mrry): Change Session to be able to use a Graph*
  // directly, instead of requiring us to serialize to a GraphDef and
  // call Session::Extend().
  if (session->extend_before_run &&
      !ExtendSessionGraphHelper(session, status)) {
    return;
  }

  TF_Run_Setup(noutputs, output_values, status);
  ...

---------------------------------------------------------------
c_api.cc:771
---------------------------------------------------------------
static void TF_Run_Setup(int noutputs, TF_Tensor** c_outputs,
                         TF_Status* status) {
  status->status = Status::OK();
  for (int i = 0; i < noutputs; ++i) {
    c_outputs[i] = nullptr;
  }
}
```
Since `c_api` convert output data ptr(we allocated and inserted) to `nullptr`, the values are useless.

Maybe the data pointers of output tensor(allocated in the tensorflow core) are accessible.
In this case, however, we have to decide when output tensors are deleted, and it occurs another job.

Furthermore, because `c_api` requires [another library](https://www.tensorflow.org/install/lang_c), I'm not sure that the various build environments are able to afford it.

**Comment by myungjoo** [comment]
You need to write an issue at tensorflow github as well :)
