### ISSUE TITLE
Better Instructions on Compiling and resolving dependencies

### ISSUE THREAD

**Issue by faisalthaheem** [nnsuite/nnstreamer#1041]
# Issue Description
Need better instructions on compile process from sources.

Expected Result
============
Instructions will allow for code to be compiled. Will give instructions on how to obtain/compile dependencies.

How to Reproduce
===============
1. Clone nnstreamer
2. Follow building with meson instructions
3. meson stops and complains of missing tensorflow (and tensorflow-lite) library

Further Information
===============
build environment - Ubuntu 16.04 - docker container

root@predator:/code/nnstreamer# ./meson/meson.py build
The Meson build system
Version: 0.48.2
Source dir: /code/nnstreamer
Build dir: /code/nnstreamer/build
Build type: native build
Project name: nnstreamer
Project version: 0.1.0
Native C compiler: cc (gcc 5.4.0 "cc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609")
Native C++ compiler: c++ (gcc 5.4.0 "c++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Dependency glib-2.0 found: YES 2.48.2
Dependency gstreamer-1.0 found: YES 1.8.3
Dependency gstreamer-base-1.0 found: YES 1.8.3
Dependency gstreamer-controller-1.0 found: YES 1.8.3
Dependency gstreamer-video-1.0 found: YES 1.8.3
Dependency gstreamer-audio-1.0 found: YES 1.8.3
Dependency gstreamer-app-1.0 found: YES 1.8.3
Dependency gstreamer-check-1.0 found: YES 1.8.3
Library m found: YES
Library dl found: YES
Library pthread found: YES
Dependency orc-0.4 found: YES 0.4.25
Program orcc found: YES (/usr/bin/orcc)
Dependency tensorflow found: NO (tried pkgconfig)

meson.build:75:2: ERROR:  Dependency "tensorflow" not found, tried pkgconfig

**Comment by faisalthaheem** [comment]
Thanks for assigning the issue @wooksong.

I managed to move forward by downloading the tensorflow c libraries from (https://www.tensorflow.org/install/lang_c) with gpu support on linux. 

Managed to compile nnstreamer when using flag cmake -DENABLE_TENSORFLOW_LITE=OFF ..

but then then I'm not able to run the example pipeline "Example : camera live-view image classification. w/ gst-launch, decoded by tensor_decoder" as tensorflow lite is not configure in the compiled library.

How do I compile tensorflow lite required library?

**Comment by jaeyun-jung** [comment]
Before updating related documents, could you please check below link?
http://ppa.launchpad.net/nnstreamer/ppa/ubuntu/pool/main/t/tensorflow/
You can download tensorflow-lite pkg, and install deb in your local pc.
Also you can refer nnstreamer wiki page (https://github.com/nnsuite/nnstreamer/wiki/usage-examples-screenshots)

**Comment by faisalthaheem** [comment]
thank you. installing tensorflow-lite-dev from that ppa resolved the problem, but now, I get the following error when trying to run the pipeline "Example : camera live-view image classification."

nnapi error: unable to open library libneuralnetworks.so
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:cam_src: Internal data stream error.
Additional debug info:
gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:cam_src:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.238605578
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

Some more information:
===================
I also tried installing nnstreamer from the ppa, while it works fine, it's very very slow, about 1 frame per 3 seconds as if it's not using gpu at all with the following output
nnapi error: unable to open library libneuralnetworks.so
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
WARNING: from element /GstPipeline:pipeline0/GstXImageSink:img_test: A lot of buffers are being dropped.
Additional debug info:
gstbasesink.c(2902): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstXImageSink:img_test:
There may be a timestamping problem, or this computer is too slow.


It would be great if you guys can provide some hints on how to compile the tensorflow-lite-dev library myself from the sources or point me to the project that is already doing this (CI?)

**Comment by jaeyun-jung** [comment]
@faisalthaheem Please provide more information,
1. Do you run the example - image classification with gst-launch script? or build executable file?
   - If runs with gst-launch command (it is slow..mixed in textoverlay), please try to build/run exe file.
2. Please check the web-cam and gst-glugin-path. 
   - We supposed cam device '/dev/video0'.
   - Please check GST_PLUGIN_PATH and nnstreamer lib path , or run example with the option '--gst-plugin-path'. e.g,
```
./nnstreamer_example_image_classification --gst-plugin-path=<nnstreamer.so path in your pc>
```

**Comment by faisalthaheem** [comment]
Thanks @jaeyun-jung I'll try that out.

For Now, you are right I was using gst-launch to build and run the pipeline, the source was my integrated webcam.

Primarily I wanted to use nnstreamer with tensorflow framework, not tensorflow-lite. As I've come to understand from the sources and documentation (release notes) that support for tensorflow is still in progress.

This is a very promising project and very well crafted, great work guys!. But I will have to take another route and use app sinks and sources to do my processing using gpu.

At the moment the best way to compile nnstreamer is to add the ppa and install tensorflow-dev and tensorflow-lite-dev from there.

Some things that can make it easier for information to be discoverable

1. Add release notes to the "releases" of the git repo as it's more commonly practiced, instead of the wiki page.

2. Add a table of what's supported currently to the homepage in terms of frameworks, it took me some time to understand tensorflow support is still in works, with no committed release date or version.

3. May be provide a docker container with things setup to let people build quickly instead of trying to figure out where to get dependencies from.
