### ISSUE TITLE
Can I set up a build environment on Ubuntu ?

### ISSUE THREAD

**Issue by boxerab** [nnsuite/nnstreamer#1075]
I am a GStreamer contributor who would like to learn more about this project.  Can you recommend steps to set up a build environment on Ubuntu ?

**Comment by myungjoo** [comment]
If you use Ubuntu 16.04, You will need to get meson >= 0.40 from that PPA or xenial-backport as well. For Ubuntu 18.04 you are good to go with what jaeyun-jung said.

**Comment by boxerab** [comment]
Thanks! I was able to get the examples working on Ubuntu 18.
I did get this error:

`nnapi error: unable to open library libneuralnetworks.so`

**Comment by boxerab** [comment]
This looks like an error from Android nnapi. Thanks again for the help getting started.
