### ISSUE TITLE
Remove redundant nnstreamer_example folder

### ISSUE THREAD

**Issue by boxerab** [nnsuite/nnstreamer#1078]
This is now a separate repo - maybe could be added as a git submodule

**Comment by myungjoo** [comment]
No, I won't.

nnstreamer-example.git and nnstreamer.git will generate binary packages of its own.
Inter-package-depdencies MUST be resolved by dependency between independently built and deployed binary packages. Build dependencies can be resolved that way as well ("BuildRequires" of RPM or "BuildDeps" of DEB packages). 

The "good" way is to build library.git, generating library.rpm / library-devel.rpm and then, build application.git, generating application.rpm. Modern build systems (OBS, GBS, Launchpad, ...) can do all the depedency resolves and do it automatically for a target package (application.git in this case).

In general, if you need git-submodule or "wget", "curl" other git repos (usually libraries) to build something, it only means that the package is not ready for deployment/integration or the build script or the build system SUCKS.

**Comment by boxerab** [comment]
Thanks. I am only suggesting that you will have to maintain two copies of the examples, in two repositories. Wouldn't it be better to maintain only one ?
