### ISSUE TITLE
[TensorType] any plan to support STRING?

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#1081]
Since the various use cases with diverse source data could encourage developers who have interest at nnstreamer, I've tried to make an example with AUDIO rather than video.

However, because we don't have a type about STRING yet, I can't make it possible.
[The simple audio(speech) recognition model of tensorflow](https://www.tensorflow.org/tutorials/sequences/audio_recognition?hl=ko) using STRING type as its input data.
Furthermore, tensorflow uses below code to convert `wav` file to `Tensor`
```bash
tensorflow/examples/speech_commands/label_wav.cc:145
=============================================================
Status read_wav_status = tensorflow::ReadFileToString (
  tensorflow::Env::Default(), file_name, &wav_string
);
Tensor wav_tensor(tensorflow::DT_STRING, tensorflow::TensorShape({}));
wav_tensor.scalar<string>()() = wav_string;
```

It indicates that lots of DNN models takes STRING as their input data if they use `wav` files.

**Comment by myungjoo** [comment]
If we can assume ```N``` as the size limit of this "string", you can use UINT8 / N:1:1:1 tensor and let it be consumed in tensor_filter::WHATEVERNNFWYOUUSE as a corresponding string.

Or with small "N", you may make it "aggregate" in runtime until you have "break" or predetermined "number of consecutive tensor".


Otherwise, you will need to invent "variable-size" tensor.

**Comment by jaeyun-jung** [comment]
@helloahn please check the PR #1129, to support DT_STRING in tensorflow sub-plugin.

**Comment by jaeyun-jung** [comment]
If a tensorflow model uses wav as a input, we have to read and pass the whole wav file.
speech command model in testcase uses wav file (header + 16000 audio samples, total 16022 * 2 bytes for 1 second audio input, 16k sample-rate mono pcm)

**Comment by helloahn** [comment]
@jaeyun-jung Thank you for the comment!
