### ISSUE TITLE
Versioning of nnstreamer + TAOS-CI

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1108]
With the start of the project, TAOS & TAOS-CI, we planned to have version names of:
```
A: Autobahn  (The 2018 version)
B: Broadway  (Maybe..  TAOS-CI of today may become this)
C: CHAMPS-ELYSEES (Paris)  / ChoongMoo-ro / 
D: Downing St. (London) 
E: Elm 
F: Fifth Ave. (NYC) 
G: Grafton St. (Dublin) 
H: Highway 66 (US) / Hollywood Blvd 
I: Interstate 
K: Karakoram Highway 
L: Las Vegas blvd. 
M: Madison Ave. 
...
S: Samsung-ro
...
U: Umyeon-ro
...
```
because "tao" of TAOS means road (道) although it also means
"Tiny and Advanced" or "Tizen AI OS Support", ...

Anyway, how are we going to put version names to nnstreamer and TAOS-CI?
I suppose we may reuse TAOS version names for both? :)

**Comment by leemgs** [comment]
Will the next version be "**B: Broadway**" because now is Feb-2019?

**Comment by myungjoo** [comment]
Yup. the new version name of TAOS (TAO = 道 = Road) is expected to be Broadway
