### ISSUE TITLE
[Test] Tests with live sources/sinks

### ISSUE THREAD

**Issue by kparichay** [nnsuite/nnstreamer#1145]
Unit tests should also add test cases with live sources/sinks.
Non-live sources/sinks do not perform synchronization.
Using only non-live sources/sinks do not test for the below concepts at least. There might be more missing details.

1. Synchronization
2. Latency

One solution for automated test cases with live source/sink is to use udp network source/sink, as it can be automated. However, compatibility with TAOS-CI needs to be verified.

**Comment by myungjoo** [comment]
With unit testing networking (non localhost) is not allowed. We are using isolated build infrastructure, which prohibits using external resources (including networks).

You need to use something available without peripheral hardware or networks:
- a movie clip file
- a virtual camera replaying a saved file.
- a virtual network device replaying a saved file.

I think we have related unit test cases in unittest_sink.c, which has psuedo-live sources with fixed framerates.

**Comment by kparichay** [comment]
We can use `videotestsrc` with `is-live` property set as `TRUE` to simulate live source for video and add additional test cases.
Correspondingly, `audiotestsrc` and `appsrc` has the same attribute to simulate live sources.
Measuring frame drop can test for synchronization and latency issues with taos-ci.

**Comment by myungjoo** [comment]
I believe we already have related test cases.
