### ISSUE TITLE
Website link in github title points to something seemingly unrelated

### ISSUE THREAD

**Issue by Aidenhjj** [nnsuite/nnstreamer#1175]
# Issue Description
The link in the README (http://nnsuite.mooo.com/nnstreamer/ci/taos/) seems to talk about some unrelated project.

Expected Result
============
Website with `nnstreamer` specific information.

**Comment by myungjoo** [comment]
The web site in the link is the front-page of CI system of nnstreamer. The main body introduces the CI system itself; however, you can choose corresponding nnstreamer services with tabs on the top.

**Comment by leemgs** [comment]
@Aidenhjj  FYI, https://github.com/nnsuite/TAOS-CI

**Comment by myungjoo** [comment]
@leemgs Anyway, when we have a nice representative web page for nnstreamer, we would put that there.

**Comment by myungjoo** [comment]
As there is no more discussions and the TAOS-CI link is really for nnstreamer-CI, I'm closing this.
