### ISSUE TITLE
lcov/gcov does not generate ./ext/ folder. And time is incorrect.

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#1193]
It is strange. The existing lcov/gcov does not generate  source files of ./ext/ folder. 

* Screenshot:

![image](https://user-images.githubusercontent.com/82404/53790947-82cc7a00-3f6b-11e9-84e2-f2decd8e8d55.png)

**Comment by leemgs** [comment]
* After @jaeyun-jung  PR

![image](https://user-images.githubusercontent.com/82404/53798445-9aabfa00-3f7b-11e9-9c24-e131d1cc939d.png)

**Comment by jaeyun-jung** [comment]
In my local,
![utc](https://user-images.githubusercontent.com/39614140/53799100-05116a00-3f7d-11e9-8a94-c59501504b30.png)

**Comment by leemgs** [comment]
However, the time zone is not **KST** format. IT seems that the output format is **UTC** without **KST** because of the gbs build environment.

![image](https://user-images.githubusercontent.com/82404/53800170-73572c00-3f7f-11e9-95ec-75e7591cebe4.png)

**Comment by leemgs** [comment]
* About UTC time zone of lcov (genhtml command): 
https://github.com/linux-test-project/lcov/pull/12/commits/f433d02c127111b5a82b4142949f33ae260f6ae1#diff-e0fa7bb3df3ef605bff92f39fe3a25e4

Use UTC to get a timezone-independent date

The date is used for updating the time inside manpages.
If localtime is used, the date could vary depending on the user's
timezone. To enable reproducible builds, UTC is used instead.

**Comment by myungjoo** [comment]
Please take a look at the version. It says ```0.0.3```. That's pretty old. Something is still wrong with unit-test-coverage.

**Comment by leemgs** [comment]
> Please take a look at the version. It says 0.0.3. 

Issue #1275 .  0.0.3 issue was fixed.
