### ISSUE TITLE
[Aggregator] New Feature Suggested, Required by Project:NS-2

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1202]
```
Input frames: 0, 1, 2, 3, 4, 5, 6, ... , 2i, 2i+1, 2i+2, 2i+3, ...
Output frames: 0, 2, 4, 6, ... , 2i, 2i+2, 2i+4, ...
```

Without actually aggregating multiple frames into a frame, we may need to drop frames (flush > 1). This is expected to be accomplished by slightly tweaking tensor_aggregator

**Comment by jaeyun-jung** [comment]
Suggestion: 

mode
none / rate / pattern / random

1. rate
```mode=rate:20``` push buffer after 50ms (skip all incoming buffers until next proc time)

2. pattern
```mode=pattern:push2,skip1``` push 2 buffers then skip 1

3. random
```mode=random``` randomly push incoming buffer

**Comment by jaeyun-jung** [comment]
One more, do we need to handle buffer-drop in aggregator?
I think implementing new element is better, not in aggregator.

**Comment by myungjoo** [comment]
> One more, do we need to handle buffer-drop in aggregator?
I think implementing new element is better, not in aggregator.

If code-sharing is not much, that's better.

We may think as a mutated Tee:
```
          pattern=0,1
[sinkpad] TeeBLAHBLAH [srcpad0]
                      [srcpad1]
```
Then, with incoming frames ```..., 2i, 2i+1, 2i+2, ...```,
srcpad0 gets: ``` ..., 2i, 2i+2, 2i+4, ...``` and
srcpad1 gets: ``` ..., 2i+1, 2i+3, 2i+5, ...```.
