### ISSUE TITLE
[Filter / tensorflow] 

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#121]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Friday Jun 01, 2018 at 07:22 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/56_

----

If Filter/Main, Filter/Tensorflow-Lite is up and being tasked, this may be started parallelly.

tflite has higher priority!

**Comment by myungjoo** [comment]
Assigning this to @helloahn because I saw him implementing this today. :)
