### ISSUE TITLE
[CI/CD] Urgent! OBS failed in building nnstreamer for all architectures

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#1220]
It looks a python package required by meson is missing.
We need to fix it.

```bash
[   69s] + meson --buildtype=plain --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64 --bindir=/usr/lib/nnstreamer/bin --includedir=/usr/include -Dinstall-example=true -Denable-tensorflow=true build
[   69s] Traceback (most recent call last):
[   69s]   File "/usr/bin/meson", line 6, in <module>
[   69s]     from pkg_resources import load_entry_point
[   69s] ModuleNotFoundError: No module named 'pkg_resources'
[   69s] error: Bad exit status from /var/tmp/rpm-tmp.KHMV6C (%build)
```

**Comment by myungjoo** [comment]
Uh. shit. They've updated Tizen;Base recently: accepted/tizen/base/20190308.035718
On the next business day, we need further testing and write the bug report at bugs.tizen.org

**Comment by myungjoo** [comment]
OK.. https://review.tizen.org/gerrit/#/c/platform/upstream/meson/+/201129/ This fixes the error.

As a workaround you may add 
```
BuildRequires: python3-setuptools
```
to nnstreamer.spec

**Comment by myungjoo** [comment]
@wooksong Please follow up with https://review.tizen.org/gerrit/#/c/platform/upstream/meson/+/201129/ and contact its maintainers to accelerate SR process. Without nagging them, it make take a month or longer to have the fix released.

**Comment by myungjoo** [comment]
https://review.tizen.org/gerrit/gitweb?p=platform/upstream/meson.git;a=commit;h=f1591678c9cc990a8b7ad5a0b34ded1b3b4f97dc

Tizen:Base SR Accepted. OBS updated and no more such errors.

**Comment by wooksong** [comment]
@myungjoo They created [their own patch](https://review.tizen.org/gerrit/#/c/platform/upstream/meson/+/201139/) this morning and merged it. 

They said that it will be applied (means SR) next Monday since this is a base package.

**Comment by wooksong** [comment]
https://build.tizen.org/package/show/devel:AIC:Tizen:5.0:nnsuite/nnstreamer

Resolved!
