### ISSUE TITLE
More Parts MUST be exposed to devel.

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1223]
In order to develop some serious Gst Application / Library with nnstreamer, we need to refer to
type checking/declarations of nnstreamer filters. 

Thus we need to expose more about filters. Before this, we need to hide private info.

**Comment by jaeyun-jung** [comment]
define GstTensorFilterPrivate and add private using g_type_class_add_private()

**Comment by jaeyun-jung** [comment]
PR #1363 to hide private properties in tensor-filter

**Comment by jaeyun-jung** [comment]
Do we need to update all the nnstreamer plugins to add private structure?

**Comment by myungjoo** [comment]
Let's do this when this is really required.
