### ISSUE TITLE
[Filter/Tensorflow] Test result of tensorflow-gpu & the way of removing memcpy

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#1239]
### the result of applying tensorflow-gpu
Recently, I've tried to apply tensorflow-gpu at nnstreamer rather than our tensorflow package to check it's working well with gpu version.

Shortly, it was done with high quality without any memory or further problem with the current version.
For instance, the latency of the example `object_detection` is reduced from 300ms to 20ms on average.

I used bazel build system to generate shared libraries and installed tensorflow-gpu through pip install.
If you want to know the details, I'll make a document at wiki page.

### the way to avoid gbs error of CI server: #1038
The problem, failure of gbs build only called at our CI server, is discussed with @myungjoo and decided to make a detour to solve it.
I will make a flag before using memcpy to decide using memcpy with stable, and remove memcpy with unstable, and I want to discuss the flag.
Among the various ways, which way is better?

1. define an environment variable, like `TF_MEM_OPTIMIZATION` or something.
2. add a property at tensor_filter(but it's only for tensorflow from now on).
3. other ideas.

Please share your idea in this thread.

**Comment by myungjoo** [comment]
In order to supply configurations, I have implemented ```gst/nnstreamer/nnstreamer_conf.h/c```. Extend it with default configuration described in ```/nnstreamer.ini```.

For example, by default, it uses the "hardcoded value" in nnstreamer_conf.h
It can be overriden by the value in nnstreamer.ini, which can again overriden by
environmental values.

e.g., you may add:
```
[tensorflow]
input_frame_nomemcpy_support=true
```
