### ISSUE TITLE
[Design] unconverter(?)

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#124]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Tuesday Jun 05, 2018 at 03:32 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/59_

----

Suggested by @jijoong-moon 

We need a converter that converts from other/tensor to conventional media stream (e.g., video/x-raw)

Please consider the possibility of using openCV in NNStreamer

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jun 05, 2018 at 03:32 GMT_

----

:octocat: **cibot**: Thank you for posting issue #59. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Friday Jul 27, 2018 at 02:41 GMT_

----

Additional Requirements Found during Development: (putting these as Sprint 1808B)
1. label.txt + tensor for label --> gst text stream
2. (not yet determined) bounding boxes -> gst video with given resolution.

**Comment by myungjoo** [comment]
The basic function of tensor_dec is completed. Closing this to remove duplication.
