### ISSUE TITLE
SSAT build checker fails

### ISSUE THREAD

**Issue by kparichay** [nnsuite/nnstreamer#1247]
SSAT build checker fails in "nnstreamer_repo_rnn", and disappears with rebuild.
This can be seen with PR #1237.

This link corresponds to the details when the build failed - 
http://nnsuite.mooo.com/nnstreamer/ci/repo-workers/pr-checker/1237-201903151942480.91760110855103-d5e4565aef5f97d05aff6aca996e21a093b2266a/

And this link corresponds to the build passing with the same code - 
http://nnsuite.mooo.com/nnstreamer/ci/repo-workers/pr-checker/1237-201903151955380.72278594970703-86521663b36e86e09a17183730699709fe35d9c7/

**Comment by myungjoo** [comment]
To recreate the error, try:
```
NNStreamer/tests/nnstreamer_repo_rnn$ X=0; while [ "$X" == "0" ]; do rm *.log; rm *.xraw; ssat; X=$? ; done
```
