### ISSUE TITLE
[RunTest] nnstreamer/apptest: improve execution speed of  apptest module

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#1265]
The existing apptest module always download the same files such as network model and label file repeatedly. It is reported by @jaeyun-jung . We need to improve the existing operation (1) to reduce a waiting time and (2) to save AWS network cost.

* Screenshot:
![image](https://user-images.githubusercontent.com/82404/54794066-f5866680-4c88-11e9-8caf-adeae8981b52.png)

**Comment by leemgs** [comment]
[My Proposal]

At frist, /temp will be one of the appropriate locations to save the files:
1. /tmp/*.tflite (network model)
2. /tmp/*.txt (label)

Then, if /tmp/** files exists after checking a file name and file size, Do not download repeatedly the same files via network.

**Comment by leemgs** [comment]
* A related PR: https://github.com/nnsuite/TAOS-CI/pull/490

**Comment by leemgs** [comment]
The up-to-date version of Ubuntu distribution  does not use 'tmpfs' (in memory filesystem) to maintain /tmp folder. 

* /etc/default/rcS
* /lib/systemd/system/systemd-tmpfiles-clean.service

**Comment by myungjoo** [comment]
What about storing model files in AWS? (and maintain either "main version" or "mirroring version" there with publically available & readable URL?)
