### ISSUE TITLE
[AppTest] some file names are broken again in log file.

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#1280]
* log file: 
[nnstreamer-apptest-output-20190327.txt](https://github.com/nnsuite/nnstreamer/files/3012175/nnstreamer-apptest-output-20190327.txt)

```bash

  3950K .......... .......... .......... .......... .......... 95%  421M 0s
  4000K .......... .......... .......... .......... .......... 96%  396M 0s
  4050K .......... .......... .......... .......... .......... 98%  430M 0s
  4100K .......... .......... .......... .......... .......... 99%  434M 0s
  4150K .......... .......... .....                           100%  436M=0.3s

2019-03-27 17:13:40 (16.0 MB/s) - �쁬obilenet_v1_1.0_224_quant.tflite�� saved [4276000/4276000]


[DEBUG] Downloading 'tflite label' with wget command ...
--2019-03-27 17:13:40--  https://github.com/nnsuite/testcases/raw/master/DeepLearningModels/tensorflow-lite/Mobilenet_v1_1.0_224_quant/labels.txt
Resolving github.com (github.com)... 192.30.255.113, 192.30.255.112
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/nnsuite/testcases/master/DeepLearningModels/tensorflow-lite/Mobilenet_v1_1.0_224_quant/labels.txt [following]
--2019-03-27 17:13:41--  https://raw.githubusercontent.com/nnsuite/testcases/master/DeepLearningModels/tensorflow-lite/Mobilenet_v1_1.0_224_quant/labels.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.72.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.72.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10484 (10K) [text/plain]
Saving to: �쁫abels.txt��

     0K ..........                                            100%  145M=0s

2019-03-27 17:13:41 (145 MB/s) - �쁫abels.txt�� saved [10484/10484]

[DEBUG] App (Producer): Starting 'gst-launch-1.0 videotestsrc ! v4l2sink device=/dev/video0' test on the VNC environment...

[DEBUG] App (Consumer1): Starting 'gst-launch-1.0 v4l2src device=/dev/video0 ! videoconvert ! ximagesink' test on the Xvnc environment...
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
[DEBUG][PASS] It's okay. The consumer application is successfully completed.
```

* Screenshot: 
![image](https://user-images.githubusercontent.com/82404/55060347-9c696900-50b4-11e9-9e36-cae3417c461e.png)

**Comment by leemgs** [comment]
@wooksong , @jaeyun-jung , Could you give me a hint to fix this issue? I think that you can give me helpful hint to me. :)

**Comment by wooksong** [comment]
This is because 'content-type' in HTTP-header is omitted from those *.log file. For this reason, web browser cannot recognize 'charset' of the log files so that such strange characters displayed.
```bash
$ curl -s -I http://nnsuite.mooo.com/nnstreamer/ci/repo-workers/pr-checker/1285-201903280640520.24126410484314-0f0fe8738d4a24985ec147d541f53387c38b551a/report/nnstreamer-apptest-output.log
HTTP/1.1 200 OK
Date: Fri, 29 Mar 2019 05:59:12 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Wed, 27 Mar 2019 21:55:27 GMT
ETag: "2973-5851a7ed544a3"
Accept-Ranges: bytes
Content-Length: 10611
Connection: close
```

In order to fix this issue, I made two changes. 
1) Uncomment the following line in /etc/apache2/conf-enabled/charset.conf
```xml
# AddDefaultCharset UTF-8
```
2) Add the following lines to /etc/apache2/apache2.conf 
```xml
<FilesMatch "\.(txt|log)$">
	ForceType 'text/plain; charset=UTF-8'
</FilesMatch>
```

After applying these changes, 
```bash
$ curl -s -I http://nnsuite.mooo.com/nnstreamer/ci/repo-workers/pr-checker/1285-201903280640520.24126410484314-0f0fe8738d4a24985ec147d541f53387c38b551a/report/nnstreamer-apptest-output.log
HTTP/1.1 200 OK
Date: Fri, 29 Mar 2019 06:00:35 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Wed, 27 Mar 2019 21:55:27 GMT
ETag: "2973-5851a7ed544a3"
Accept-Ranges: bytes
Content-Length: 10611
Vary: Accept-Encoding
***Content-Type: text/plain; charset=utf-8***
Connection: close
```

You can check that there are no more strange characters displayed at all: http://nnsuite.mooo.com/nnstreamer/ci/repo-workers/pr-checker/1285-201903280640520.24126410484314-0f0fe8738d4a24985ec147d541f53387c38b551a/report/nnstreamer-apptest-output.log  (Don't forget ctrl+f5).

One thing to concern is that my changes are system-wide approach. Using .htaccess is more better solution I guess.

**Comment by leemgs** [comment]
> Add the following lines to /etc/apache2/apache2.conf
> <FilesMatch "\.(txt|log)$">
> 	ForceType 'text/plain; charset=UTF-8'
> </FilesMatch>
> 
@wooksong  , But, I am looking for another recipe to solve this issue without modifying the configuration file (e.g., /etc/apache2/apache2.conf) of the Apache web-server?  Initially, the  ./ci/taos/common/global-variable.sh has been created to handle a character set issue of www-data (The Apache webserver).

> $ curl -s -I http://nnsuite.mooo.com/nnstreamer/ci/repo-workers/pr-checker/1285-201903280640520.24126410484314-0f0fe8738d4a24985ec147d541f53387c38b551a/report/nnstreamer-apptest-output.log

For reference, apptest module of nnstreamer use  '-o logfile' option of 'wget' command instead of 'curl' to  report to stand error (stderr).
* https://github.com/nnsuite/TAOS-CI/blob/master/ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh#L61

**Comment by leemgs** [comment]
The below PRs are to fix this issue without modifying the configuration file of Apache/httpd daemon:
* #504, #506
