### ISSUE TITLE
[Admin] Task Distributions

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#129]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jun 07, 2018 at 01:59 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/64_

----

### Full Time Tasks. (to be allocated / taken): Proposed Tasks for @jy1210-jung @jinhyuck83-park @sewon-oh @hello-ahn 

- [x] tensor_filter_tensorflow_lite ( @jinhyuck83-park @hello-ahn)
  - Additional problem to solve: would it be more efficient to let tensorflow_lite (instead of tensor_filter / tensor_filter_tensorflow_lite) to "allocate" output buffer? If yes, we need to add an interface between tensor_filter(main) and tensor_filter_* for output buffer management.
  - Need understandings on both tf-lite and gst. (2 people / <2 month for "1.0")
  - Need to "guarantee" no-memcpy-ness.
  - Verify APIs of tensor_filter::main, suggest revises.
  - Create TF-lite models for test cases.
  - (later) Need to provide performance measurement standard for NNFW/models.
  - (later) Need to provide performance recommendations for NNFW usages.
  - (later) May keep working on other NNFW (tensorflow, caffe, caffe2, ...) later.

- [x] CI / integration test (not unit test) (1 people / <2 month for "1.0") ( @sewon-oh )
  - Enable nnstreamer CI facility from TAOS-CI , https://github.sec.samsung.net/STAR/TAOS-CI/issues/2
  - Run nnstreamer CI web-service , http://aaci.mooo.com/nnstreamer/ci/standalone/
  - Need to create test cases & integration test suite , #125
  - (later) Need to monitor overall performance (the whole pipeline) #67 
  - (later) Need to support Litmus (smoke test) for all platforms.
  - (later) Need to support github.com / LF.

- [x] tensor_sink (app sink) (1 people / <2 month for "1.0") ( @jy1210-jung )
  - Need careful design for the API (to apps).
  - Need careful design for performance. (setup performance measurement standard for apps)
  - GST Probe is to be researched as well.
  - Provide test cases / test apps.

201807 Goal: test with a straight stream. (video-src --> t_convert --> t_filter (tensorflow-lite) --> t_sink )

---

### Part Time Tasks. (do this as a side job)
- [ ] tensor_filter_custom samples (useful "preloaded" filters) and test cases / fixes
- [ ] test cases with movie files, potentially testing synch issues later.
  - This is required to have a least one lossless picture stream and one lossy picture stream (h.264, ...).
  - This is supposed to test synchronization issues later.
- [ ] more unit test cases (esp. tensor_converter / tensor_filter_custom with more examples )
- [ ] stream synchronization issues. (multi-srcs / tee-ed streams / serial streams with different FPS or inconsistent FPS)

---

### Not urgent but important tasks.
- [ ] other/tensor findtype standardization (upstream) (not full time task)
- [ ] Ready for moving to github.com / LF. (not full time task)
- [ ] Communicate with maintainers. (not full time task)
  - Final goal: make the way to gstreamer-plugins-good.
- [ ] GST Probe (1 people / within 1 month)
  - Performance / Overhead analysis
  - other/tensor considerations
  - Need to determine whether we are going to support GST Probe or to enforce app_sink (tensor_sink) only.
- [ ] GST Stream performance analysis in general. (getting the skillsets and tools)
- [x] tensor to media converter (taken. @jijoong-moon )

---

### Postponed (later) tasks
- [ ] tensor_transform
- [ ] tensor_merge
- [ ] tensor_source
  - IIO
  - LIDAR/RADAR
  - ROSBAG?
- [ ] tensor_converter::audio
- [ ] tensor_converter::text
- [ ] tensor_converter::video more colorspaces.
- [ ] Research: support openCV and/or utilize openCV for tensor_XXX elements.
- [ ] use NEON / SSE / or anything for tensor_XXX elements

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jun 07, 2018 at 01:59 GMT_

----

:octocat: **cibot**: Thank you for posting issue #64. The person in charge will reply soon.

**Comment by myungjoo** [comment]
This info is obsolete. I'll create a new one later from our internal doc repo.
