### ISSUE TITLE
[Test] running test makes working directory dirty

### ISSUE THREAD

**Issue by kparichay** [nnsuite/nnstreamer#1332]
Running tests calls meson.build in nnstreamer/nnstreamer_example which modifies the `TEST_OPENCV` variable in nnstreamer/tests/nnstreamer_filter_custom/runTest.sh polluting the original git directory (polluting means that runTest.sh is now modified and appears under modified files in `git status`).

To resolve this, I am thinking about using moving `TEST_OPENCV` to an environment variable, which can be reset in meson.build and correspondingly used in runTest.sh. However, this method adds an extra global environment variable.

Can you suggest a better method?

**Comment by myungjoo** [comment]
Ah... that script (/nnstreamerr_example/meson.build) is ugly.

Assuming that the nnstreamer binaries do not differ with changes of "enable-opencv-test" (it appears so),
the availability of OPENCV should be determined at runtime of runTest.sh at /tests/nnstreamer_filter_custom/.

METHOD 1 (best): find if opencv is available. (without looking at rpm/deb)
METHOD 2 (not that good): use envvar (given by tester / build-scripts)
