### ISSUE TITLE
[Bug/unittestcoverage-tool] tizen-api coverage is not exposed.

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1333]
Instead of tizen-api, codegen-testcode is included.

Exclude test/codegen. Include tizen-api/src

http://nnsuite.mooo.com/nnstreamer/ci/gcov_html/index.html

This does not seem to be a bug from TAOS-CI itself.
Probably, there is a bug in tests/unittestcoverage.py

**Comment by jaeyun-jung** [comment]
This is because of invalid source path for tizen-api.
I will update new PR to resolve this issue.

**Comment by jaeyun-jung** [comment]
PR #1338 to fix this issue

**Comment by jaeyun-jung** [comment]
Now coverage report includes tizen c-api.
