### ISSUE TITLE
[Tizen/API] License Verification.

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1351]
- [x] Is it ok to have LGPL as the license of Tizen-C-API packages?
- [x] If it's ok, let's re-license ALL Tizen-C-API files and packages to LGPL.

**Comment by again4you** [comment]
After talking with Somang Park (somang.park) who is in charge of Open Source Group,
there is no problem to use LGPL v2.0 License for Tizen C-API.

So we decide to use LGPL v2.0 License instead of Apache.
