### ISSUE TITLE
Questions about Documentation&usage (especially getting-started.md)

### ISSUE THREAD

**Issue by ik1ne** [nnsuite/nnstreamer#1405]
# Issue Description
1. Detailed instruction for nnstreamer user via PPA?
It is mentioned that nnstreamer can be installed via PPA repository, but [Usage Examples on usage example screenshots](https://github.com/nnsuite/nnstreamer/wiki/usage-examples-screenshots#usage-examples) uses $NNST_ROOT envvar which is declared only on Build examples section of that document.

2. For build/compile, do I need to follow all sections in getting-started(both pdebuild and debian)?
I think one of these is enough for the whole build process(as pdebuld generates .deb file at /var/cache/pdebuild/result that can be installed with dpkg -i), however the documentation's Prerequisite/PPA/pdebuild/Self-hosted build section has same indentation.

**Comment by myungjoo** [comment]
> Detailed instruction for nnstreamer user via PPA?

PPA is a standard mechanism of Ubuntu. If you need instructions about PPA, you can simply google it. Anyway, you should be able to use PPA without any further instruction. It's way too simple for that (according to the nnstreamer documentation):
```
$ sudo add-apt-repository ppa:nnstreamer/ppa
$ sudo apt-get update
$ sudo apt-get install nnstreamer
```

> It is mentioned that nnstreamer can be installed via PPA repository, but Usage Examples on usage example screenshots uses $NNST_ROOT envvar which is declared only on Build examples section of that document.

It has nothing to do with PPA. It's about using nnstreamer after it is installed. PPA is a single instance of installing mechanisms. In a few examples (app examples), the NNST_ROOT refers the path to your own model or application. In other examples (building examples), it refers the installation target path. If you use PPA, you don't need to build & install, so this is totally unrelated. You may suggest updates (patches) to the documentation if you think this is too confusing.

> 2. For build/compile, do I need to follow all sections

No, we are simply giving all the options for users. Not all of users use Ubuntu. There are way too many different operating systems and their variants.

**Comment by myungjoo** [comment]
As the discussion is discontinued. I'm closing this.
