### ISSUE TITLE
[Security] library path in .ini

### ISSUE THREAD

**Issue by jaeyun-jung** [nnsuite/nnstreamer#1411]
190430-0002

환경변수값 변조로 임의 라이브러리 로드 가능

현재 nnstreamer 필터 플러그인 사용시 아래와 같은 시스템 환경변수와 default 경로를 사용하여 runtime 라이브러리 경로를 받아들이고 있음

export NNSTREAMER_FILTERS 
export NNSTREAMER_DECODERS

#define NNSTREAMER_FILTERS              "/usr/lib/nnstreamer/filters/" 
#define NNSTREAMER_DECODERS         "/usr/lib/nnstreamer/decoders/"

NNSTREAMER_FILTERS 환경변수 값을 변조하여 악의적인 filter를 로딩해서 사용 가능하다.

![190430-0002](https://user-images.githubusercontent.com/39614140/56944372-0bc3f400-6b5e-11e9-8e36-a3fec8bcd56d.png)

악의적인 사용자가 쉽게 변경 가능한 환경변수방식보다는 , RO 영역에 위치한 고정된 라이브러리 경로를 사용하게 한다.

**Comment by jaeyun-jung** [comment]
IMO, we cannot fix this issue about registering sub-plugins.
I just added PRs to validate sub-plugins data before the registration.
( PR #1421 and PR #1422 )
Also I updated PR to handle error case of invalid params. (PR #1415)

**Comment by myungjoo** [comment]
We may disable env-var by adding one more value in .ini file.

For example,
if ```nnstreamer.ini``` has:
```
[common]
disable_envvar=TRUE
```
, then, do not load envvars.

**Comment by jaeyun-jung** [comment]
Added new PR to check env-var (https://github.com/nnsuite/nnstreamer/pull/1424)
