### ISSUE TITLE
[COVERITY] Using uninitialized value `num_mapped` in gst_tensor_src_iio_fill()

### ISSUE THREAD

**Issue by again4you** [nnsuite/nnstreamer#1418]
Uninitialized value `num_mapped` is used in for statement.

* Code: gst/nnstreamer/tensor_source/tensor_src_iio.c
* Link: http://10.113.139.115:8081/reports.htm#v14205/p10167/fileInstanceId=116224943&defectInstanceId=48783434&mergedDefectId=1053516

**Comment by again4you** [comment]
@kparichay Plz handle this issue.

**Comment by jaeyun-jung** [comment]
@again4you If you don't try to fix this issue, I will make new PR about this.

**Comment by jaeyun-jung** [comment]
PR #1420 to fix this issue.
