### ISSUE TITLE
[Filter] Support Intel Movidius Neural Compute Stick

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#1437]
This issue is for tracking the working status of #1138.

- Requirements
  - [x] (mandatory) Add a tensor filter extension for Intel Neural Compute Stick 1 support
  - [x] (mandatory) Support the version 2 of NCSDK (Software Development Kit for the Neural Compute Stick) only
  - [ ] ~~(mandatory) Add several examples based on this tensor filter extension using TensorFlow and Caffe models~~ 
  - [ ] ~~Optional requirements will be added later~~
**Above sub-tasks are postponed and will be handled in the newly opened other issue**

**Comment by myungjoo** [comment]
@wooksong Please close this if you have no pending tasks related.

**Comment by wooksong** [comment]
@myungjoo Got it.
