### ISSUE TITLE
[CI] Seems that checker-pr-comment.sh and checker-issue-comment.sh run twice

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#1444]
It seems that checker-pr-comment.sh and checker-issue-comment.sh run twice whenever new PR or new issue is submitted.

**Comment by wooksong** [comment]
This is because the webhook handlers for checker-pr-comment.sh and checker-issue-comment.sh are not disabled at the CI server what we used for yocto build and yocto unit tests.

I've just disabled them. After watching for few days, if there is no issue, we can close this issue.

**Comment by myungjoo** [comment]
You can close it yourself. :p
