### ISSUE TITLE
Tizen Sample Apps

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1446]
Add Tizen Sample Apps
- C-API / Pipeline

**Comment by leemgs** [comment]
Users can refer to https://github.com/nnsuite/nnstreamer-example to develop their sample applications based on nnstreamer. 
* https://github.com/nnsuite/nnstreamer-example

**Comment by myungjoo** [comment]
@leemgs We do not have proper Tizen sample application in nnstreamer-example.git, yet. Tizen sample applications MUST use ML-APIs only, without gstreamer APIs.

**Comment by myungjoo** [comment]
Done.
