### ISSUE TITLE
Filter / Custom Python. Fix Request

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1449]
@wooksong has reported this in a PR #1357 :

```C
192 cb_type type = py_core_getCbType (py->py_private_data);
```

in ext/nnstreamer/tensor_filter/tensor_filter_python.c

 you need to fix it.

---

**Comment by dongju-chae** [comment]
Oh. This issue was included in the up-to-date PR.

**Comment by myungjoo** [comment]
Oh.. OK Then.. :)
