### ISSUE TITLE
[CI] Timestamp error

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#1460]
At #1459 
Timestamp error occurred.
The detail message is below
> Timestamp error: files are from the future: Mon, 27 May 2019 16:41:12 +0900 > (now) Mon May 27 07:40:39 UTC 2019.

Please check it.

**Comment by myungjoo** [comment]
Log in to the CI server and check the date there. Anyway, the difference seems to be a few minutes (UTC vs KST). There is a possibility that your clock is a few minutes off.

**Comment by helloahn** [comment]
it's solved
