### ISSUE TITLE
TF/TF-Lite 1.13 and nnstreamer @ ubuntu & Tizen

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1512]
TensorFlow 1.13 for Tizen is being prepared at https://build.tizen.org/package/show/devel:AIC:Tizen:5.0:nnsuite:test/tensorflow-1.13.1

The code is available at https://review.tizen.org/gerrit/gitweb?p=platform/upstream/tensorflow.git;a=shortlog;h=refs/heads/sandbox/mzx/1.13.1
, which is going to support Ubuntu/Debian build (xenial/bionic) soon.

The build rpm files can be downloaded at download.tizen.org/live

1. Check the compatibiltiy
    - (MJ) Tested x86-32 tf-lite with nnstreamer build + unittest: OK
2. If not compatible, design multi-version support for the tf/tf-lite subplugins.

**Comment by helloahn** [comment]
#1552 will solve the compatibility of TF.

**Comment by myungjoo** [comment]
1.13 is now fully integrated and tested.
