### ISSUE TITLE
JAVA API (Android)

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1514]
This is to be "equivalent" with C# API (#1513 )

**Comment by jaeyun-jung** [comment]
2019-09-09 initial version uploaded (https://bintray.com/beta/#/nnsuite/nnstreamer/nnstreamer?tab=overview)

TBD
2019-10 upload next version (0.0.2)
- added new method to set the timeout in single-shot
- added mutex-lock for single-shot functions

**Comment by myungjoo** [comment]
We have released APIs along with 1.0.0 release.
