### ISSUE TITLE
[Tizen/C-API] Privilege request API

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1531]
E.g., ```add_ml_privilege_camera()```.

To make 1:1 relation between API function and privilege item, we need such "dummy" APIs.

Need to consult with security correspondents first, before writing APIs.

**Comment by myungjoo** [comment]
I think this can be closed??

**Comment by jaeyun-jung** [comment]
This needs testcase (not in nnstreamer) I requested to HJ to add new testcases about cam privilege.

**Comment by jaeyun-jung** [comment]
This issue will be closed after testing the privilege with mmfw res-mgr.

**Comment by myungjoo** [comment]
@jaeyun-jung I think it's already tested?

**Comment by jaeyun-jung** [comment]
Test done with @helloahn, close this issue.
