### ISSUE TITLE
[Discussion] [Tizen/C-API] Whitelist Draft

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1532]
Here are the first draft of pipeline construction element whitelist:

```
tensor_* (all from nnstreamer)
tizencamerasrc (ALIAS until tizencamerasrc is released via TIzen)
(TBD) something to get MIC input

videoconvert
videoscale
videoframerate

tee
queue
composite (TBD)

appsrc
appsink
valve
switch

decodebin (TBD)
demux (TBD. to separate video and audio streams from a combined stream)
```

**Comment by jaeyun-jung** [comment]
switches and base filter
- input-selector
- output-selector
- capsfilter

base element for audio/video
- audioconvert
- audioresample
- volume
- audiorate
- videorate

**Comment by jaeyun-jung** [comment]
how about adding all good/base plugins?

TBD consideration
plugin opencv ?

**Comment by myungjoo** [comment]
> how about adding all good/base plugins?

Nope. Let's start with what we've already used for sample apps + elements that MUST be required by other AI projects. Expanding whitelist is easy.

E.g.,
capsfilter
~concat~
~dataurisrc~
~downloadbuffer~
~fakesrc~
~fakesink~
~fdsrc~
~fdsink~
filesrc
filesink
~funnel~
~identity~
input-selector
output-selector
queue
~queue2~
tee
~typefind~
~multiqueue~
valve
~streamiddemux~

**Comment by myungjoo** [comment]
#1665 is finalizing this.

**Comment by myungjoo** [comment]
This is applied to Tizen already.
