### ISSUE TITLE
[CI/Launchpad] Tensorflow 1.13 for Ubuntu Bionic/Xenial Packaging

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1536]
I'm giving up CMAKE build of Tensorflow 1.13.
It won't happen unless we convert .bzl to .cmake.

Thus, our tensorflow repo in review.tizen.org will support TF-LITE only for 1.13, which will disable tensorflow (non-lite) in Tizen:Unified.

1. Thus, in Launchpad-PPA, please add a tensorflow & tf-lite build with BAZEL+OpenJDK8; Ubuntu has it already.

2. Test TF 1.13 compatibilty in Ubuntu. DO this test FIRST (before 1.) with PIP install or any copy TF 1.13 you can get for Ubuntu.

3. Archive TF/TF-Lite 1.09 for Tizen/Ubuntu somewhere.

**Comment by helloahn** [comment]
Since there is no required header if we build&install through bazel, I'll try to make our tensorflow filter using c_api only.

**Comment by myungjoo** [comment]
Uh... it's done... :)
