### ISSUE TITLE
[CI/Android] Setup Android CI (build-check)

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1539]
As Android support is being important, we need to setup CI for Android builds (and API test in the future).

**Comment by jaeyun-jung** [comment]
The step to build Android library in CI
1. make temporal build directory and copy the files in api directory
2. copy the required libs and gradle-settings to build directory (these files are prepared in external directory)
    - gradlew and gradle-wrapper.jar
    - GStreamer.java is needed to start gradle-build
    - tensorflow-lite (now ver 1.13 is used in CI)
3. update gradle settings (nnstreamer directory per PR)
4. build and check Android library, copy the result to bin directory

**Comment by jaeyun-jung** [comment]
API test
The application-context is required to initialize. GStreamer. (GStreamer.init(context))
So now I am preparing Android instrumented test, which runs on the target device.

**Comment by jaeyun-jung** [comment]
2019-10-16
Now TAOS-CI runs build test for Android API library.
I also added instrumentation test for Android-API.

Close this issue.
