### ISSUE TITLE
[Filter/nnfw] New Filter 4 Tizen

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1545]
We will soon get a new nnfw for Tizen.
We need to provide a tensor_filter::XXX for it.

**Comment by myungjoo** [comment]
#1695 is the skeleton code for this issue.
CC: @kparichay

**Comment by myungjoo** [comment]
As the new Tizen-nnfw is released not in July/Early-August, this is dropped from 5.5 M2 and postponed to 6.0 M1.

**Comment by kparichay** [comment]
@myungjoo is this duplicate of #1677 ?

**Comment by myungjoo** [comment]
Yes. It is duplicated. We have more info in #1677. Thus, I'm closing this.
