### ISSUE TITLE
[Tizen/C-API] GST-LESS Tensor_Filter for Single Shot API

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1547]
Another tensor_filter.c-like implementation as a backend of single-shot API, which does not require gstreamer, but can accept tensor_filter's subplugins.

This is for (latency) performance enhancement for single-shot API users who do not reuse handles.

This is Tizen 2020-M1 release item.

**Comment by kparichay** [comment]
Tasks for this epic
- [ ] Make filters independent of gst headers
  - [ ] plugin_api headers independent of gst
  - [ ] filters independent of gst
- [ ] Make tensor-filter without gst
- [ ] Make capi-single using the above tensor-filter without gst dependency

**Comment by myungjoo** [comment]
As we have discussed today, this should NOT interfere with Tizen 5.5 M2 releases. Thus, keep the current single-shot API implementation and make "another" library that does not affect the current C-API. We can later merge the two after M2 release.

**Comment by kparichay** [comment]
Yes, thanks for the direction, will follow.
