### ISSUE TITLE
[PPA/Meson] Meson 0.50.1 is (almost) ready

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#1581]
Related to #1380, #1440, #1461 

Since May, launchpad has failed to build the recent version of nnstreamer for arm architectures. I guess this is because there are no meson >= 0.43 for arm architectures. In order to work around this issue, I just debianized Meson 0.50.1 in [my private Launchpad PPA](https://launchpad.net/~wooksong/+archive/ubuntu/build-test/+packages). 

Although all of the tests embedded in Meson are by-passed (in my local machine, tests can be passed if proper dependencies for them are properly provided), Meson itself looks work well.

However, I have still faced build errors with ```cc1plus: error: /usr/src/gtest/include: No such file or directory [-Werror=missing-include-dirs]```. After briefly investigating the reason for this failure, I found out that include_directories provided by 'gtest_dep' are really wrong. 

```bash
c++ -Itests/59830eb@@unittest_sink@exe -Itests 
...omission...
-I/usr/src/gtest -I/usr/src/gtest/include 
...omission...
```

At least, libgtest-dev on Ubuntu 16.04, there is no directory named '/usr/src/gtest/include'. If '-Wmissing-include-dirs' is removed from meson.build in ./, it is possible to build nnstreamer with Meson 0.50.1. 

I will investigate this issue more in my free time, but your comments are very welcome. Until resolve this issue, we could just remove '-Wmissing-include-dirs' as a working-around solution maybe.

**Comment by jaeyun-jung** [comment]
To resolve include path of gtest, I built and installed gtest from https://github.com/google/googletest.

**Comment by myungjoo** [comment]
Please feel free to add -Wno-missing-include-dir for gtest as long as the effect is limited to gtest build.

**Comment by jaeyun-jung** [comment]
build log _ubuntu_output.txt
[143/156] Compiling C++ object 'tests/unittest_plugins@exe/gtest-all.cc.o'.
[144/156] Compiling C++ object 'tests/unittest_common@exe/gtest-all.cc.o'.

**Comment by wooksong** [comment]
https://github.com/mesonbuild/meson/blame/master/mesonbuild/dependencies/dev.py#L86

This is meson's bug since 0.45. Embedded logic to find 'gtest' is not flexible.
