### ISSUE TITLE
Help required for gst-pipeline setup issue for Tizen DTV.

### ISSUE THREAD

**Issue by szihs** [nnsuite/nnstreamer#1596]
# Issue Description

I am trying to setup nnstreamer pipeline in DTV. I am not gstreamer guy so I need some help.

As per my knowledge, DTV gstreamer pipeline is litte different. I say so due to  zero copy requirements (tbm buffer) in pipeline
 
So SW processing elements like videoscale/videoconvert _maynot_ work. 
Since buffer is not actually raw. I wish to avoid CPU processing, I am not sure totally but i assume so.

So I setup DTV Video Display Pipeline which is working.
filesrc -- demuxer -- dtvdecoder -- **gpu_pp** -- directvideosink

`https://github.sec.samsung.net/harsh-ag/ai-gstreamer-pipeline/blob/latest/gstreamer_pipeline.cpp
`
The gpu_pp use GPU passthrough filter to render to DTV hardware plane buffer and sets index in directvideosink to enable that for display.
I have got this part working.

**gpu_pp is ideal place it seems to me to connect to the tensor pipline for processing.**

The gpu_pp plugin caps are currently as below
```
GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstVr360

Pad Templates:
  SINK template: 'sink'
    Availability: Always
    Capabilities:
      ANY

  SRC template: 'src'
    Availability: Always
    Capabilities:
      video/x-raw
                  width: [ 1920, 3840 ]
                 height: [ 1080, 2160 ]
              framerate: [ 30000/1001, 60000/1001 ]
          avg_framerate: [ 0/1, 1/1 ]
            r_framerate: [ 0/1, 1/1 ]
                 **format: STV1**
```

I plan to add another `src2` pad which will connect to tensor_converter and would send video/x-raw,width,height buffer and get the nueral network process on say 300x300,rgb buffer coming from src2 pad.

I have tried to read gstreamer documentation on official website how to write plugin.
I tried to add new pad src2 to passthrough dummy GstMyFillter created below

`https://github.sec.samsung.net/harsh-ag/gst-template`

The HEAD points to commit i hope to work to get the above job done.
```

filesrc -- demuxer -- dtvdecoder -- **gpu_pp** -- directvideosink
                                                             |          (src_pad)        
                                                            |
                                                            | (  **src_pad_2**)                                                  
                                                            --- tensor_converter -- tensor_filter -- tensor_sink
```

I hope to run similar pipline in host first so that i could modify the gpu_pp plugin in DTV.

```
 gst-launch-1.0 -vv --gst-debug=*:2,myfilter:6 --gst-plugin-path=$PWD/gst-plugin/src/.libs \
 videotestsrc ! myfilter name=t  \
t.src ! queue ! autovideosink \
t.src2 ! queue ! "video/x-raw, width=(int)224, height=(int)224,  format=RGB" ! fakesink
```

I get below error
```
harsh@harsh-ubuntu:~/workspace/pvr/samples/AI/2019/gst-template$ gst-launch-1.0 -vv --gst-debug=*:2,myfilter:6 --gst-plugin-path=$PWD/gst-plugin/src/.libs  videotestsrc ! myfilter name=t silent=true t.src ! queue ! autovideosink t.src2 ! queue ! "video/x-raw, width=(int)224, height=(int)224,  format=RGB" ! fakesink
0:00:00.128766068 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:192:gst_my_filter_query:<t> received query caps query: 0x1ae6940, GstQueryCaps, filter=(GstCaps)"NULL", caps=(GstCaps)"NULL";
0:00:00.128814765 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:193:gst_my_filter_query:<t> pad template_caps ANY
0:00:00.128827449 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:202:gst_my_filter_query:<t> pad current_caps NULL
0:00:00.128853358 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:192:gst_my_filter_query:<t> received query caps query: 0x1ae68a0, GstQueryCaps, filter=(GstCaps)"NULL", caps=(GstCaps)"NULL";
0:00:00.128870595 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:193:gst_my_filter_query:<t> pad template_caps ANY
0:00:00.128890688 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:202:gst_my_filter_query:<t> pad current_caps NULL
0:00:00.129050279 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:192:gst_my_filter_query:<t> received query caps query: 0x1ae69e0, GstQueryCaps, filter=(GstCaps)"NULL", caps=(GstCaps)"NULL";
0:00:00.129072191 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:193:gst_my_filter_query:<t> pad template_caps ANY
0:00:00.129082022 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:202:gst_my_filter_query:<t> pad current_caps NULL
0:00:00.129120578 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:192:gst_my_filter_query:<t> received query caps query: 0x1ae6ca0, GstQueryCaps, filter=(GstCaps)"NULL", caps=(GstCaps)"NULL";
0:00:00.129146260 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:193:gst_my_filter_query:<t> pad template_caps ANY
0:00:00.129156483 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:202:gst_my_filter_query:<t> pad current_caps NULL
0:00:00.129187497 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:192:gst_my_filter_query:<t> received query caps query: 0x1ae6a80, GstQueryCaps, filter=(GstCaps)"NULL", caps=(GstCaps)"NULL";
0:00:00.129201844 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:193:gst_my_filter_query:<t> pad template_caps ANY
0:00:00.129211447 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:202:gst_my_filter_query:<t> pad current_caps NULL
Setting pipeline to PAUSED ...
0:00:00.133357660 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:129:gst_my_filter_change_state:<t> received change_state 10
0:00:00.133643681 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:129:gst_my_filter_change_state:<t> received change_state 19
Pipeline is PREROLLING ...
0:00:00.133872234 31335      0x1ae6940 LOG                 myfilter gstmyfilter.c:354:gst_my_filter_sink_event:<t> sink_event Received stream-start event: stream-start event: 0x1aed510, time 99:99:99.999999999, seq-num 46, GstEventStreamStart, stream-id=(string)aa63c58291a08a9537f154a8dc67e8e3, flags=(GstStreamFlags)GST_STREAM_FLAG_NONE, group-id=(uint)0;
sink(0x1ae22b0) src(0x1ae24f0) src2(0x1ae2730) pad(0x1ae22b0)
0:00:00.134221091 31335      0x1ae6940 WARN                 basesrc gstbasesrc.c:2948:gst_base_src_loop:<videotestsrc0> error: Internal data flow error.
0:00:00.134239621 31335      0x1ae6940 WARN                 basesrc gstbasesrc.c:2948:gst_base_src_loop:<videotestsrc0> error: streaming task paused, reason not-negotiated (-4)
0:00:00.134296949 31335      0x1ae6940 LOG                 myfilter gstmyfilter.c:354:gst_my_filter_sink_event:<t> sink_event Received eos event: eos event: 0x1aed580, time 99:99:99.999999999, seq-num 42, (NULL)
sink(0x1ae22b0) src(0x1ae24f0) src2(0x1ae2730) pad(0x1ae22b0)
ERROR: from element /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0: Internal data flow error.
Additional debug info:
gstbasesrc.c(2948): gst_base_src_loop (): /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0:
streaming task paused, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
0:00:00.183865641 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:129:gst_my_filter_change_state:<t> received change_state 26
0:00:00.183901898 31335      0x1ace950 LOG                 myfilter gstmyfilter.c:129:gst_my_filter_change_state:<t> received change_state 17
```

Can you please help me to resolve how to handle it in gstreamer.

**Comment by myungjoo** [comment]
- myfilter is totally out of scope of this project. It's just GStreaemr filter, not nnstreamer filter. Go to gstreamer community for that issue.
- ```gst-launch-1.0 -vv --gst-debug=*:2,myfilter:6 --gst-plugin-path=$PWD/gst-plugin/src/.libs \
 videotestsrc ! myfilter name=t  \
t.src ! queue ! autovideosink \
t.src2 ! queue ! "video/x-raw, width=(int)224, height=(int)224,  format=RGB" ! fakesink```

create videotestsrc with the given caps (```video/x-raw, width=(int)224, height=(int)224,  format=RGB```) or add convert/scaler before the capsfilter.

**Comment by myungjoo** [comment]
And your gst pipeline is totally incorrect:
Even ``` gst-launch-1.0 videotestsrc ! "video/x-raw, width=(int)224, height=(int)224,  format=RGB" ! autovideosink ``` this won't work. You are simply using Gst incorrectly here.

**Comment by szihs** [comment]
@myungjoo  Thank you for your reply.

> Anyway.. myfilter is not correctly processing caps. 
Can you please elaborate about this a small bit more. 

Yes i referred plugin-development guide for trying to create below myfilter, but gstreamer plugins is not my area of expertise. So if you can kindly provide inputs, i will be grateful.
https://github.sec.samsung.net/harsh-ag/gst-template

> gst-launch-1.0 -vv --gst-debug=*:2,myfilter:6 --gst-plugin-path=$PWD/gst-plugin/src/.libs  videotestsrc ! myfilter name=t silent=true  \
> t.src ! queue ! videoconvert !  autovideosink \
> t.src2 ! queue ! "video/x-raw, width=(int)224, height=(int)224" ! fakesink
> 

Based on your advice, I added videoconvert to the pipeline and it seems to show.

Currently I am just pushing same dummy data to both pads.
```
  ret = gst_pad_push (filter->srcpad, buf);

  if (filter->src2pad) {
         GST_DEBUG_OBJECT (filter->src2pad, "push hello");
         ret = gst_pad_push (filter->src2pad, gst_buffer_ref(buf));
  }
```
What i don't understand is since i hope to develop different width/height caps for each pad, 
why would caps filter with RGB from second sink affect the first autovideosink ?

Also I would kindly request if you can tell me how to correct process caps or refer some pointers.
Thanks for your time.

**Comment by myungjoo** [comment]
> What i don't understand is since i hope to develop different width/height caps for each pad,
why would caps filter with RGB from second sink affect the first autovideosink ?

I don't want to look at the code, but it almost surely implies that your implementation does not allow to negotiate caps differently with different pads. Anyway.. there is no reason to do it; it's useless. You can simply add tee and do whatever different to each src after queue there. I just can't understand why you are doing it.

**Comment by szihs** [comment]
I understand using tee is preferred as per gstreamer design.

However it looked to me duplicate gpu codes to do on same buffer in two separate contexts
in each tee connected plugin doing render to texture for each sink,
in what could have been part of same plugin with 2 src pad. Thus will save lot of duplicate code and memory requirements for pipeline.

Regards,
Harsh

**Comment by myungjoo** [comment]
Tee does not duplicate frames unless you do in-place operations, and most gst elements do not do in-place operations. And you want different caps for the two pads, thus you are going to apply operations independently for the two pads. Thus, there is no (or little) performance/memory overheads of using tee there. If you are applying the same operations to the two different caps-stream, you can apply independently with a tee-ed streams. Because they are shared object, the system is not supposed to copy code sections and they are automatically parallelised. You are actually saving memory and improves performance by using tee here.

**Comment by szihs** [comment]
Maybe I didn't clarify.

decoder --- tee -- gpu_pp -- directvideosink
                       |
                       | --  gpu_pp2 -- tensor_convert -- tensor_filter -- tensor_sink 

decoder output say  1920x1080, NV12 video stream (dmabuf-fd)... 
gpu_pp create a gpu context1, context1 create eglimage from dmabuf-fd render to sinksize (1920x1080, NV12)

gpu_pp2 create a gpu context2, context2 again create eglImage from same dmabuf, but render to say 300x300, RGBA image for tensor converter plugin.

even though gpu_pp & gpu_pp_2 run in different thread. i will have to create texture and map dmabufd in both plugins..

if they were 2 src pad, 
it would be 

BindPipeline_1
RenderTexture(1) -> for waylandsink

BindPipeline_2
RenderTexture(2) -> for tensor_converter.

1080p is just example, 
If we have 4k video support, in this case reading 4k buffer ~ 12MB twice per frame is big loss..

**Comment by myungjoo** [comment]
As long as both gpu_pp and gpu_pp2 do NOT do in-place operations and dmabuf-fd handling in tee (I've never exprienced dmabuf handling) is not incorrect, tee DOES NOT incur memcpy. I guess gpu_pp2 is simply a GPU-based down-scale? I see completely no reason to make a single filter that combines gpu_pp + gpu_pp2 + tee. If there is memcpy in tee stage, you just need to correct tee to behave correctly with dmabuf or inherit tee to create tee-dmabuf.
