### ISSUE TITLE
Pytorch dependency with meson : how to resolve ? 

### ISSUE THREAD

**Issue by boxerab** [nnsuite/nnstreamer#1604]
With new pytorch dep, it would help to have some info on how to resolve it:

```
meson.build:158:2: ERROR: Dependency "pytorch" not found, tried pkgconfig and cmake

A full log can be found at /home/aaron/src/nnstreamer/build/meson-logs/meson-log.txt
```
I tried installing pytorch via

`pip install torchvision`

but this doesn't fix the meson error. 

Thanks.

**Comment by myungjoo** [comment]
Those folks publishing PIP often pay no attention to C/C++ programmers and omits pkgconfig files in their packages. Thus you need pytorch packages along with proper .pc (pkgconfig) files.

For example, you can use pytorch package from our nnstreamer/ppa PPA.

In pytorch in nnstreamer/ppa:
```
debian/pytorch/usr/lib/python3.*/dist-packages/torch/include/* usr/include
debian/pytorch/usr/lib/python3.*/dist-packages/torch/share/* usr/share
debian/pytorch/usr/lib/python3.*/dist-packages/torch/lib/* usr/lib
pytorch.pc usr/lib/pkgconfig
caffe2.pc usr/lib/pkgconfig
```

**Comment by boxerab** [comment]
Perfect! Thank you!
