### ISSUE TITLE
[Build/CI] Internal CI service for test result reports

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1617]
Please configure a daily/nightly internal CI service for test result reporting.

**Comment by dongju-chae** [comment]
FYI, the test result for daily build is reported with the below links.
- coverage: http://nnsuiteci.mooo.com/nnstreamer/ci/gcov_html/
- unittest: http://nnsuiteci.mooo.com/nnstreamer/ci/unittest_result/

**Comment by myungjoo** [comment]
Thanks!!!
