### ISSUE TITLE
[Android] Enable JCenter

### ISSUE THREAD

**Issue by jijoongmoon** [nnsuite/nnstreamer#1620]
In order to distribute nnstreamer aar, we are going to use JCenter.

**Comment by myungjoo** [comment]
@yunakim has approved the budget for JCenter. We may need to use "per-year" plan if possible anyway (easier to manage).

**Comment by jaeyun-jung** [comment]
2019-09-10 Initial version uploaded

To include nnstreamer, add dependency in build.gradle
```
dependencies {
    // Set latest version of NNStreamer API
    implementation 'org.nnsuite:nnstreamer:0.0.1'
}
```

**Comment by myungjoo** [comment]
When you have it daily built & deployed from CI server, please close this.

**Comment by jaeyun-jung** [comment]
@myungjoo Uploading api-library to bintray does not update the package in jcenter. It needs manual request at bintray web page, after new version is uploaded.

**Comment by jaeyun-jung** [comment]
Currently we don't need to set up daily build in CI server, uploading new version to jcenter requires manual request in bintray web page.

To update api-library, add account info and run script in CI  (consider firewall issue)
