### ISSUE TITLE
[Tizen] Similar package in tizen 

### ISSUE THREAD

**Issue by kparichay** [nnsuite/nnstreamer#1664]
`inference-engine-tflite-0.0.1-1.1.src.rpm` provides similar functionality as nnstreamer single-shot API with tf-lite. Further, there are two packages for `inference-engine` with opencv and a generic version.

**Comment by myungjoo** [comment]
Those are implemented by MMFW folks (정태영) who envisioned to write Media-Vision APIs based on OPENCV and this "inference-engine". We need further discussions with them to remove inference-engines and use "ML-Single" APIs instead.

**Comment by myungjoo** [comment]
We will be addressing this issue after 5.5 M2 release.

**Comment by myungjoo** [comment]
- Discussed the issue with Tizen/MMFW.
- Told the customers to use ML-APIs instead.
For Tizen 6.0 M1, we will be assisting the transition.

**Comment by myungjoo** [comment]
Conclusion:

They will create "inference-engine-MLAPI" or "inference-engine-nnstreamer".
Then, they will deprecate inference-engine-tensorflow-lite
