### ISSUE TITLE
[Tizen] 2nd ACR Items

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1668]
Prepare 2nd ACR so that we can start 2nd ACR as soon as 1st ACR is fully completed.

Please write 2nd ACR items here.

- API Doc update
    - whitelist (subset of real whitelist)
-

**Comment by jaeyun-jung** [comment]
Changed
- ml_tensors_info_get_tensor_size()

Added
- ml_single_set_timeout()
- ML_TIZEN_CAM_VIDEO_SRC and ML_TIZEN_CAM_AUDIO_SRC

TBD
- ml_validate_model_file()

**Comment by myungjoo** [comment]
2nd ACR confirmed and is at doc status. Closing this at github side.
