### ISSUE TITLE
[Dist/Tizen] Provide libncsdk and libncsdk-dev packages

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#1711]
This is a sub-item of https://github.com/nnsuite/nnstreamer/issues/1696 and https://github.com/nnsuite/nnstreamer/issues/1709. 

In order to enable the nnstreamer-ncsdk2 sub-package, libncsdk and libncsdk-dev packages are required. Note that ncsdk2 depends on caffe.

Need to check that we can use https://review.tizen.org/gerrit/#/admin/projects/platform/upstream/caffe.

**Comment by myungjoo** [comment]
1. You may create openvino/ncsdk git repos in Tizen-gerrit and mirror from nnsuite ==> Tizen-gerrit.
2. You may use Caffe, but that's going to be out of Tizen:Unified.
3. Check if you can use libcaffeonacl instead.

**Comment by wooksong** [comment]
> 1. You may create openvino/ncsdk git repos in Tizen-gerrit and mirror from nnsuite ==> Tizen-gerrit.
>    
>    * If you are going to keep it open-p and touch "spec" files only, you may directly clone to TIzen-gerrit from the upstream without having a repo in nnsuite.
> 2. You may use Caffe, but that's going to be out of Tizen:Unified.
> 3. Check if you can use libcaffeonacl, which is already in Tizen:Unified, instead.

@myungjoo Got it.

**Comment by wooksong** [comment]
Failed to build https://review.tizen.org/gerrit/#/admin/projects/platform/upstream/caffe for x86_64 and aarch64. It looks like very simple error...

```bash
...omission...

[  204s] /usr/lib64/gcc/x86_64-tizen-linux-gnu/6.2.1/../../../../x86_64-tizen-linux-gnu/bin/ld: cannot find -lz
[  204s] collect2: error: ld returned 1 exit status
[  204s] src/caffe/CMakeFiles/caffe.dir/build.make:2720: recipe for target 'lib/libcaffe.so.1.0.0' failed
[  204s] make[2]: *** [lib/libcaffe.so.1.0.0] Error 1

...omission...
```
