### ISSUE TITLE
[Dist/Tizen] Provide packages containing libinference.so and its related files

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#1712]
This is a sub-issue of https://github.com/nnsuite/nnstreamer/issues/1708.

Prior to #1708, we need to import openvino into Tizen world. At the current time, Intel provides two binary packages,

1.  l_openvino_toolkit_p_2019.2.275.tgz and 
2. l_openvino_toolkit_runtime_raspbian_p_2019.2.242.tgz

Since armv7l or aarch64 is the main target architecture, providing a Tizen (binary) package based on l_openvino_toolkit_runtime_raspbian_p_2019.2.242.tgz would be the first step.

By building https://github.com/opencv/dldt, I got a bunch of libraries that are also included in the openvino binary package. dldt might be a open-source version of openvino (not sure).

**Comment by wooksong** [comment]
OBS package creation request has been submitted as well:

https://bugs.tizen.org/browse/TRE-2299

**Comment by myungjoo** [comment]
Please close this if there is no other pending repos.

**Comment by wooksong** [comment]
Got it.
