### ISSUE TITLE
Handle 'already loaded' case in filter sub-plugins

### ISSUE THREAD

**Issue by jaeyun-jung** [nnsuite/nnstreamer#1727]
need to fix exception case in filter sub-plugins 

static int
tflite_loadModelFile (const GstTensorFilterProperties * prop, void **private_data)
{
....
    if (strcmp (prop->model_file,
            tflite_core_getModelPath (tf->tflite_private_data))) {
      tflite_close (prop, private_data);
    } else {
      **return 1;**
    }
  }

static int
tflite_open (const GstTensorFilterProperties * prop, void **private_data)
{
  int ret = tflite_loadModelFile (prop, private_data);
  **g_assert (ret == 0);       /** This must be called only once */**
  return ret;
}

**Comment by jaeyun-jung** [comment]
PR #1728 for this issue

**Comment by myungjoo** [comment]
Need a test case after #1728

**Comment by jaeyun-jung** [comment]
PR #1778 to add testcase to reopen nn model
