### ISSUE TITLE
Condition Element for NNStreamer

### ISSUE THREAD

**Issue by jijoongmoon** [nnsuite/nnstreamer#1731]
We need the NNStreamer Element to control pipeline. 
May be, It could be good to define conditional tensor which include conditional variable or we could use multi tensor. 
The first one is element which push to the down stream when the conditional variable is true. And the other one is that can run different down stream depends on the conditional variable.

![condition](https://user-images.githubusercontent.com/23226860/66288575-b3ff9500-e914-11e9-8e23-b75d0c46a896.gif)

**Comment by myungjoo** [comment]
Duplicated with #1703

**Comment by jijoongmoon** [comment]
It is in #1703
