### ISSUE TITLE
[VoC 10/14] ML API doc and example publish

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1751]
Request from product div.

API doc and code example

Need a Tizen native app with single API invocations.

**Comment by myungjoo** [comment]
Register Tizen Single C API sample app: @helloahn 
API doc export, write doc, and publish: @myungjoo

**Comment by helloahn** [comment]
@myungjoo 
https://github.com/nnsuite/nnstreamer-example/pull/67
is the sample app

**Comment by myungjoo** [comment]
TODO: Generate API doc from Doxygen / Tizen-API doc.

**Comment by myungjoo** [comment]
https://github.com/nnsuite/nnstreamer/wiki/tizen.api.doc/5.5_m2_native/html/

**Comment by myungjoo** [comment]
API doc can be created by executing doxygen at /api/capi

(Or create .pdf from temp API doc site)

**Comment by myungjoo** [comment]
Published.
