### ISSUE TITLE
Implicit type casting issue with g_ascii_strtoull()

### ISSUE THREAD

**Issue by abcinje** [nnsuite/nnstreamer#1762]
In my PR #1748, I got a review that g_ascii_strtoull() function returns a value with type `guint64`.
I also found this kind of implicit type casting issues in other codes.

For example:

https://github.com/nnsuite/nnstreamer/blob/master/gst/nnstreamer/tensor_common.c#L984
(my PR, `guint64`→`gsize`)

https://github.com/nnsuite/nnstreamer/blob/master/gst/nnstreamer/tensor_common.c#L1198
(`guint64`→`guint`)

https://github.com/nnsuite/nnstreamer/blob/master/gst/nnstreamer/tensor_source/tensor_src_iio.c#L1071
(`guint64`→`gint64`)

Is it okay without doing explicit type casting or using appropriate types for these codes?

**Comment by myungjoo** [comment]
If we get warnings from gcc/llvm with strict options and recent version, we surely need to update them. (I haven't test it)
