### ISSUE TITLE
Add Tensor Type: quant8 and bool

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1764]
With new NPU devices, we need to support new data types: quant8 and bool.

Note that we may need to support additional types soon: quant-N. Thus, we need to think about generality and bitwise-formatting as well.

E.g., with quant-3 or int3, the formatting may be:

Data: int3 X[8]

Memory Buffer:
```
|  First Byte                 | Second Byte                 | Third Byte                  |
| X[0]-0b X[1]-0b ... X[6]-0b | X[0]-1b X[1]-1b ... X[6]-1b | X[0]-1b X[1]-1b ... X[6]-1b |
```

Thus, we will need to check the data formatting with a few H/W people and make it flexible if there are different formats.

**Comment by kparichay** [comment]
Two more candidates:
- `float16`
- `Quant16` - This will be covered with quant-N as described above.

**Comment by myungjoo** [comment]
Good point! I didnt consider the quant and base values. The first candidate to store such data is having a special tensor to the given tensor or tensors.

**Comment by kparichay** [comment]
Yes, there can be a quantization related structure, which can store all the quant related data (quant/base values, and even more values if needed). Max overhead for non-quant tensors would be 4 bytes for quant structure null ptr.
```diff
+typedef struct {
+  void * offset;  /* offset to add to the quantized data */
+  void * scale;  /* scale to be multiplied for the quantized data */
+} quant_data;

typedef struct {
  void *data;  /* uint-N values for N-bit quantized data */
+  quant_data *quant;  /* contains all extra information needed to dequantize the above data */
  size_t size;
  tensor_type type;
} GstTensorMemory;
```

 Correspondingly store the type of quantization in TensorInfo.
```diff
+typedef enum {
+  ROW_SHARED,  /* each row shares the offset and scale, (rename as DIM0_SHARED?) */
+  COL_SHARED,  /* each column shares the offset and scale, (rename as DIM1_SHARED?) */
+  FILTER_2D_SHARED,  /* each 2D tensor (DIM0 and DIM1) share the same offset and scale */
+  FILTER_3D_SHARED,  /* each 3D tensor share the same offset and scale */
+  FILTER_4D_SHARED,  /* complete 4D tensor share the same offset and scale */
+  NO_SHARED
+} tensor_quant_type;  /* How are offset and scale shared. This information will be used to passed to the framework, based on the support by the framework*/

typedef struct {
  char *name;
  tensor_type type;
  tensor_dim dimension;
+  tensor_quant_type quant_type; /* the type of quantization this tensor is representing */
} GstTensorInfo
```

**Comment by myungjoo** [comment]
It appears that we don't need to worry about this. Input/Output values are supposed to have conventional types and such manipulations are to be handled by runtime libraries of the given HW.
