### ISSUE TITLE
[Android/Api] Permission denied error while building NNStreamer API library for Android

### ISSUE THREAD

**Issue by Lee-WonJun** [nnsuite/nnstreamer#1793]
# Background
OS: Ubuntu 18.04

# Issue Description

A permission denied error occurred while building the  [NNStreamer API Library for Android](https://github.com/nnsuite/nnstreamer/blob/master/api/android/README.md).

More specifically, an error occurred while running bash-script (build-android-lib.sh) in the "Build Android API" step.

The following error occurs while running the script.

```bash
$ bash ./api/android/build-android-lib.sh
/usr/bin/svn
/bin/sed
/usr/bin/patch
/usr/bin/zip
Android SDK: /home/dldnjs1013/android/tools/sdk
GStreamer binaries: /home/dldnjs1013/android/gstreamer-1.0
NNStreamer root directory: /home/dldnjs1013/android/workspace/nnstreamer
Start to build NNStreamer library for Android.

...

Starting gradle build for Android library.
api/android/build-android-lib.sh: line 125: ./gradlew: Permission denied
Failed to build NNStreamer library.
~/android/workspace/nnstreamer ~/android/workspace/nnstreamer
~/android/workspace/nnstreamer
```

**Comment by myungjoo** [comment]
Yeah.. execution bit of the file ```gradlew``` is missing.
You may add bash to the line 125.
