### ISSUE TITLE
[Android/Api] Is it possible to use same error header in TIZEN and Non Tizen without a patch?

### ISSUE THREAD

**Issue by Lee-WonJun** [nnsuite/nnstreamer#1796]
This is a sub-item of [#1795](https://github.com/nnsuite/nnstreamer/issues/1795).

I found a bit odd thing while I write Batch script

bash-script use patch file because it is non tizen build.
and patch file modifies "api\capi\include\nnstreamer.h"

but in my opinion, 
It is possible to use same error header in TIZEN and Non Tizen without a patch.
I think, we can make header file of error.

and some file that include tizen_error.h use nnstreamer_error.h.
then I think, it is possible to use same error header 

Is there something I don't know about this approach or is it impossible?

for example.
we make nnstreamer_error.h and Its content is 
```cpp
#ifdef __TIZEN__
#include <tizen_error.h>
#else
#include <errno.h>
#define TIZEN_ERROR_NONE (0)
#define TIZEN_ERROR_INVALID_PARAMETER (-EINVAL)
#define TIZEN_ERROR_STREAMS_PIPE (-ESTRPIPE)
#define TIZEN_ERROR_TRY_AGAIN (-EAGAIN)
#define TIZEN_ERROR_UNKNOWN (-1073741824LL)
#define TIZEN_ERROR_TIMED_OUT (TIZEN_ERROR_UNKNOWN + 1)
#define TIZEN_ERROR_NOT_SUPPORTED (TIZEN_ERROR_UNKNOWN + 2)
#define TIZEN_ERROR_PERMISSION_DENIED (-EACCES)
#endif
```

and some file that include tizen_error.h use nnstreamer_error.h.
then I think, it is possilbe to use same error header 

Is there something I don't know about this approach or is it impossible?

thank you

Suggested-by: @wooksong

**Comment by myungjoo** [comment]
For Tizen SDK Rootstrap to work properly, in Tizen packages and target source repo, there should be NO header files with duplicated definitions. Thus, we should NOT have a header with ```define TIZEN_ERROR_....``` regardless whether it has ```#if/#ifdef``` or not.

Thus, to clean that up, we need to have an alternative ```tizen_error.h``` that is located out of ```api/capi/include``` and installed to capi's include at build/packaging-time for non-Tizen machines.

**Comment by wooksong** [comment]
@myungjoo I will let @Lee-WonJun understand what you mean:)
