### ISSUE TITLE
[other/tensor] Storing the rank of a tensor in tensor_dim

### ISSUE THREAD

**Issue by kparichay** [nnsuite/nnstreamer#1808]
Current setup of using the `tensor_dim dimension` in `other/tensor` does not store the information of rank inside the `dimension` array. For example - two tensors of shape [1,1,10,100] and [1,10,100] are represented in the same manner in the dimension array. Current style sets the extra dimensions to `1`. Although this makes it easier to handle, however the information on actual rank of the tensor is lost.

I propose to set the extra dimensions to `0`. This style allows to implement all the features feasible with the current style, along with storing the information of rank. This enables the following-
- Tensors of same size and similar shape can be distinguished (example - `[1,4]` and `[4]`)
- User set rank can be stored and maintained (current implementation does not allow this)
  - This would allow to directly use the user provided shape as an input for framework (currently, the only way is to try all feasible ranks for frameworks to check which works)

I think the proposed style also brings the use of dimensions more closer to python numpy/tensoflow style, where a dimensions can be squeezed/expanded.

**Comment by myungjoo** [comment]
For clarification:

Current: ```640:480```(C: [1][1][480][640]) == ```640:480:1:1```(C: [1][1][480][640]) . ```640:480:0:0``` == INVALID

Your proposal: ```640:480```(C: [1][1][480][640]) == ```640:480:0:0```(C: [1][1][480][640])  && ```640:480```(C: [1][1][480][640])  != ```640:480:1:1```(C: [1][1][480][640]) .



Additional Considerations:
- Backward compatibility
- Tensor path manipulators (e.g., merge/mux/split/...). 
- GetRank function.

**Comment by kparichay** [comment]
> Additional Considerations:
> 
> * Backward compatibility

Is backward compatibility possible? Current design considers any dimension with value `0` as invalid, but proposed design considers it valid. 
This being said, there can be a helper function to convert a given tensor dimension from proposed design to the current implementation design (the other way around is not possible). However, I am not sure if this counts as backward compatibility.

**Comment by myungjoo** [comment]
Backward compatibility for conventional nnstreamer applications; we will have a few nnstreamer applications in Tizen soon, with the version 1.0.0, which does not have this feature. We cannot enforce them to update apps after the release of next nnstreamer versions.

In other words, the conventional nnstreamer pipelines with tf-lite and custom filters (who didn't need to read any rank numbers) with the conventional notion should work.

We don't need backward compatibility for our own code (nnstreamer elements in nnstreamer.git). We just need to update them all.

**Comment by myungjoo** [comment]
The decision after playing with the prorotypes of @jaeyun-jung:

1. We won't support rank values.
2. We won't add the capability to "infer" rank values by allowing "0" as a dimension.
3. We will allow users to denote the input/output tensor ranks as properties of tensor-filter in case the neural network framework requires ranks explicitly.
    - We just need to "verify" the given rank values with the given dimensions.
    - With 0/1 dimension rank inferences, we are enforcing pipeline writers to explicitly distinguish rank values anyway (nothing is becoming worse with this decision)
    - (future work idea): if the given nnfw gives us "true/false" "success/fail" values only if the given rank is incorrect for the given model, we may "retry" all possible rank values of the given tensor dimensions automatically with the tensor-filter subplugin.

**Comment by myungjoo** [comment]
Conclusion
