### ISSUE TITLE
Join LF? LF-AI?

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1839]
Q1. Would it be beneficial for this project to join Linux Foundation?

Q2. Would they accept this project?

Q3. Could we be approved to join Linux Foundation (from our side)?

Links:
https://www.linuxfoundation.org/projects/
https://lfai.foundation/project-stages-and-lifecycle/
https://github.com/lfai/proposing-projects/tree/master/proposals

**Comment by again4you** [comment]
A1. Many developers over the _world_ try to use NNStreamer. 
We can get a lot of benefit beyond expectation.


A2. They already has an AI Open source projects such as horovod.
* https://lfai.foundation/

However, there is no project such as NNStreamer so it is a _Good_ chance!


A3. Why not?

**Comment by leemgs** [comment]
> Q1. Would it be beneficial for this project to join Linux Foundation?
I expect that we can get a more reliable position by getting the official support of Linux Foundation.

> Q2. Would they accept this project?
I think so. 

> Q3. Could we be approved to join Linux Foundation (from our side)?
Absolutely.

**Comment by myungjoo** [comment]
Proposal: https://github.com/myungjoo/proposing-projects/blob/nnstreamer/proposals/nnstreamer.adoc

**Comment by myungjoo** [comment]
This is in progress with other divisions internally. I'll ping them next week if there is no feedback

**Comment by myungjoo** [comment]
There will be an update tomorrow morning. I'm meeting guys from open source admins, then.

**Comment by myungjoo** [comment]
Managements are talking with LF-AI. We just need to wait for them to conclude.

**Comment by myungjoo** [comment]
This is officially in progress.
