### ISSUE TITLE
could not link tensorconverter0 to tensorfilter0

### ISSUE THREAD

**Issue by wangheng923** [nnsuite/nnstreamer#1853]
![无标题](https://user-images.githubusercontent.com/10862513/68451760-fa555600-022a-11ea-8401-db75d60f4fd6.png)
I tried to run simple demo and got the error like this.
gst-launch-1.0 textoverlay name=overlay font-desc="Sans, 26" ! \
    videoconvert ! ximagesink name=img_test \
    v4l2src name=cam_src ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB ! \
    tee name=t_raw \
    t_raw. ! queue ! overlay.video_sink \
    t_raw. ! queue ! videoscale ! video/x-raw,width=224,height=224 ! \
    tensor_converter ! \
    tensor_filter framework=tensorflow-lite \
    model=tflite_model/mobilenet_v1_1.0_224_quant.tflite ! \
    tensor_decoder mode=image_labeling \
    option1=tflite_model/labels.txt ! \
    overlay.text_sink

How can i sovle the problem?

**Comment by jaeyun-jung** [comment]
Q: When running this example, can you find the warning message about tensorflow-lite?

```
** (gst-launch-1.0:5639): WARNING **: Cannot identify the given neural network framework, tensorflow-lite
```

**Comment by wangheng923** [comment]
> Q: When running this example, can you find the warning message about tensorflow-lite?
> 
> ```
> ** (gst-launch-1.0:5639): WARNING **: Cannot identify the given neural network framework, tensorflow-lite
> ```

Yes, i found this warning.

**Comment by myungjoo** [comment]
It usually means you don't have the nnstreamer-tensorflow-lite plugin installed.

If you have installed nnstreamer from PPA for your Ubuntu system, install nnstreamer-tensorflow-lite:

![image](https://user-images.githubusercontent.com/1109011/68575280-0d785800-04af-11ea-8f59-5a695cf8ba3f.png)


If you are building the code by yourself, please install tensorflow-lite, enable tensorflow-lite when you build nnstreamer, then, place the nnstreamer-tensorflow-lite plugin at an appropriate location. (refer to /etc/nnstreamer.ini)

If you are not using Ubuntu or PPA, you need to be more specific for your development environment.

**Comment by wangheng923** [comment]
> It usually means you don't have the nnstreamer-tensorflow-lite plugin installed.
> 
> If you have installed nnstreamer from PPA for your Ubuntu system, install nnstreamer-tensorflow-lite:
> 
> ![image](https://user-images.githubusercontent.com/1109011/68575280-0d785800-04af-11ea-8f59-5a695cf8ba3f.png)
> 
> If you are building the code by yourself, please install tensorflow-lite, enable tensorflow-lite when you build nnstreamer, then, place the nnstreamer-tensorflow-lite plugin at an appropriate location. (refer to /etc/nnstreamer.ini) If you don't have any related conf, the default location is /usr/lib/nnstreamer/filters/
> 
> If you are not using Ubuntu or PPA, you need to be more specific for your development environment.

**### Thanks for your help. Now I can run demo successfully**
