### ISSUE TITLE
Incorrect Typing: nnstreamer_plugin_api.h/c

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1886]
gst_tensor_get_element_count (const tensor_dim dim); 
should be gsize --> guint

gst_tensor_get_element_size (tensor_type type); 
should be guint --> gsize

**Comment by jaeyun-jung** [comment]
gulong gst_tensor_get_element_count()
gsize gst_tensor_get_element_size()

**Comment by jaeyun-jung** [comment]
I will change this with tensor rank changes.
