### ISSUE TITLE
[Unit Test Case Request] NNFW + ML-API

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1899]
Write unit test cases that uses NNFW/Runtime via ML-Single APIs and ML-Pipeline APIs
We need "fail" (negative-test-cases) cases as well.

Case 1. Single API, Invoke a sample model (needs to be very small) via Single API, supposed to be "SUCCESS"
Case 2. Single API, Invoke a sample model (needs to be very small) via Single API, supposed to be "FAIL" (model not found)
Case 3. Single API, Invoke a sample model (needs to be very small) via Single API, supposed to be "FAIL" (dimension not matched)
Case 4. Pipeline API, Invoke a sample model (small!) via Pipeline API, with a stream input (more than 3 frames)
Case 5. Pipeline API, Invoke a sample model (small!) via Pipeline API, with two input streams (mimicking multi-modal) into a single tensor (use tensor_merge).
Case 6. Pipeline API, Invoke two sample model (small!) via Pipeline API, sharing a single input stream (mimicking multi-model).
Case 7/8: Fail cases of Pipeline API

This will be a good practice for a new comer :)

@gichan-jang : You may start working on this AFTER writing Ubuntu example and BEFORE writing Tizen Studio apps.

@jaeyun-jung : Please help him start writing it. You are 2m away from him. 😄

**Comment by myungjoo** [comment]
You may use either SSAT or GTEST. Use whatever you feel comfortable.

**Comment by myungjoo** [comment]
If NNFW-Runtime does not work inside GBS at all even if only CPU is activated, proceed in ARM devices.

**Comment by myungjoo** [comment]
Until #1911 is fixed, you will need to test this in a real device. (mobile/wearable Tizen devices)

**Comment by gichan-jang** [comment]
> Until #1911 is fixed, you will need to test this in a real device. (mobile/wearable Tizen devices)
@myungjoo 
Thank you for your suggestion. 
If GBS build on an arm arch is not possible until the test code draft is written, I will test on the real device.

**Comment by myungjoo** [comment]
@kparichay has been actively using nnfw, you can ask him if you have problems with its executions.

**Comment by gichan-jang** [comment]
> @kparichay has been actively using nnfw, you can ask him if you have problems with its executions.

Thanks. 
@kparichay helped me for gbs build problem with aarch64.
I owe him my debt.

**Comment by gichan-jang** [comment]
I'm trying to make unit test cast 5 (multi-modal).
I got error message as follow :

[   38s] ** (-0:31455): WARNING **: Tensor info :
[   38s]  0 : uint8 [3:224:224:1] | float32 [1:1:1:1] FAILED

But, It works under tensorflow-lite framework.
Where is the problem? Please give me your wisdom...

```
  pipeline =  
	  g_strdup_printf (
    "appsrc name=appsrc_0 ! video/x-raw,format=RGB,width=%d,height=%d,framerate=0/1 ! tensor_converter ! mux.sink_0 "
    "appsrc name=appsrc_1 ! video/x-raw,format=RGB,width=%d,height=%d,framerate=0/1 ! tensor_converter ! mux.sink_1 "
    "tensor_merge mode=linear option=1 sync_mode=nosync name=mux ! tensor_transform mode=typecast option=uint8 ! "
    "tensor_filter framework=tensorflow-lite model=%s ! tensor_sink name=tensor_sink",
     MODEL_WIDTH/2, MODEL_HEIGHT, MODEL_WIDTH/2, MODEL_HEIGHT, test_model);
```

Test code for multimodal is :
It's part of "unittest_tizen_nnfw_runtime_raw.cpp"
```
#define MODEL_WIDTH   224
#define MODEL_HEIGHT  224

/**
 * @brief Callback for tensor sink signal.
 */
static void
new_data_cb_2 (const ml_tensors_data_h data, const ml_tensors_info_h info, void *user_data)
{
  unsigned int cnt = 0;
  int status;
  uint8_t *data_ptr;
  size_t data_size;
  ml_tensor_dimension out_dim;

  ml_tensors_info_get_count(info, &cnt);
  EXPECT_EQ(cnt, 1);
  
  ml_tensors_info_get_tensor_dimension(info, 0, out_dim);
  EXPECT_EQ(out_dim[0], 1001);
  EXPECT_EQ(out_dim[1], 1);
  EXPECT_EQ(out_dim[2], 1);
  EXPECT_EQ(out_dim[3], 1);
  
  status = ml_tensors_data_get_tensor_data (data, 0, (void **) &data_ptr, &data_size);
  EXPECT_EQ (status, ML_ERROR_NONE);
  EXPECT_EQ (data_size, 1001);
}

/**
 * @brief Test nnfw subplugin multi-modal (pipeline, ML-API)
 * @detail Invoke a model via Pipeline API, with two input streams into a single tensor 
 * 
 */
TEST (nnstreamer_nnfw_mlapi, multimodal_01_p)
{
  gchar *pipeline;
  ml_pipeline_h handle;
  ml_pipeline_src_h src_handle_0, src_handle_1;
  ml_pipeline_sink_h sink_handle;
  ml_tensor_dimension in_dim;
  ml_tensors_info_h info;
  ml_pipeline_state_e state;
  ml_tensors_data_h input_0, input_1;

  const gchar *root_path = g_getenv ("NNSTREAMER_BUILD_ROOT_PATH");
  gchar *test_model;
  /* supposed to run test in build directory */
  if (root_path == NULL)
	root_path = "..";

  /* Model does not exist. */
  test_model = g_build_filename (root_path, "tests", "test_models", "models",
	  "mobilenet_v1_1.0_224_quant.tflite", NULL);
  EXPECT_TRUE (g_file_test (test_model, G_FILE_TEST_EXISTS));

  pipeline =  
	  g_strdup_printf (
    "appsrc name=appsrc_0 ! video/x-raw,format=RGB,width=%d,height=%d,framerate=0/1 ! tensor_converter ! mux.sink_0 "
    "appsrc name=appsrc_1 ! video/x-raw,format=RGB,width=%d,height=%d,framerate=0/1 ! tensor_converter ! mux.sink_1 "
    "tensor_merge mode=linear option=1 sync_mode=nosync name=mux ! tensor_transform mode=typecast option=uint8 ! "
    "tensor_filter framework=nnfw model=%s ! tensor_sink name=tensor_sink",
     MODEL_WIDTH/2, MODEL_HEIGHT, MODEL_WIDTH/2, MODEL_HEIGHT, test_model);

  int status = ml_pipeline_construct (pipeline, NULL, NULL, &handle);
  EXPECT_EQ (status, ML_ERROR_NONE);
  
  /* get tensor element using name */
  status = ml_pipeline_src_get_handle(handle, "appsrc_0", &src_handle_0);
  EXPECT_EQ (status, ML_ERROR_NONE);
    status = ml_pipeline_src_get_handle(handle, "appsrc_1", &src_handle_1);
  EXPECT_EQ (status, ML_ERROR_NONE);
  /* register call back function when new data is arrived on sink pad */
  status = ml_pipeline_sink_register(handle, "tensor_sink", new_data_cb_2, NULL, &sink_handle);
  EXPECT_EQ (status, ML_ERROR_NONE);

  in_dim[0] = 3;
  in_dim[1] = 112;
  in_dim[2] = 224;
  in_dim[3] = 1;
  ml_tensors_info_create(&info);
  ml_tensors_info_set_count(info, 1);
  ml_tensors_info_set_tensor_type(info, 0, ML_TENSOR_TYPE_UINT8);
  ml_tensors_info_set_tensor_dimension(info, 0, in_dim);

  status = ml_pipeline_start (handle);
  EXPECT_EQ (status, ML_ERROR_NONE);

  g_usleep (500000); /* wait for start */
  status = ml_pipeline_get_state (handle, &state);
  EXPECT_EQ (status, ML_ERROR_NONE);
  EXPECT_NE (state, ML_PIPELINE_STATE_UNKNOWN);
  EXPECT_NE (state, ML_PIPELINE_STATE_NULL);

  /* generate data */
  status = ml_tensors_data_create (info, &input_0);
  EXPECT_EQ (status, ML_ERROR_NONE);
  EXPECT_TRUE (input_0 != NULL);

  status = ml_tensors_data_create (info, &input_1);
  EXPECT_EQ (status, ML_ERROR_NONE);
  EXPECT_TRUE (input_0 != NULL);


  /* Push data to the source pad */
  status = ml_pipeline_src_input_data (src_handle_0, input_0, ML_PIPELINE_BUF_POLICY_DO_NOT_FREE);
 	EXPECT_EQ (status, ML_ERROR_NONE);
  status = ml_pipeline_src_input_data (src_handle_1, input_1, ML_PIPELINE_BUF_POLICY_DO_NOT_FREE);
 	EXPECT_EQ (status, ML_ERROR_NONE);

  g_usleep (5000000);

  ml_tensors_info_destroy (info);
  ml_tensors_data_destroy (input_0);
  ml_tensors_data_destroy (input_1);


  status = ml_pipeline_stop (handle);
  EXPECT_EQ (status, ML_ERROR_NONE);
  g_usleep (50000);

  status = ml_pipeline_destroy (handle);
  EXPECT_EQ (status, ML_ERROR_NONE);

  g_free (pipeline);
  g_free (test_model);

}
```

**Comment by kparichay** [comment]
This model should work with nnfw because nnfw does not support UINT8 type [for now](https://review.tizen.org/gerrit/gitweb?p=platform/core/ml/nnfw.git;a=blob;f=runtime/neurun/api/include/nnfw.h;h=1e18deaab332fb2c05a4a5e3810de3ce6825ab38;hb=refs/heads/tizen)

However, the error you are facing is not because of this issue but because of some dimension error from nnfw. This bug has been reported to nnfw.

**Comment by myungjoo** [comment]
We now have the corresponding test case at ```/tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc``` with #2002 .

@gichan-jang Please close an issue if you have resolved it.
