### ISSUE TITLE
Refactor tensor-filter subplugins' c/cc double sources

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1936]
You don't need to implement tensor_filter callbacks in .c and implement hardware/framework invocations in .cc file. You can implement both in a single .cc file and remove .c-.cc wrappers.

Reference: https://github.com/nnsuite/nnstreamer/blob/master/ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc

**Comment by dongju-chae** [comment]
When the referenced PRs are merged, this issue can be closed.
