### ISSUE TITLE
[Api/Single] define new function to open with multi files

### ISSUE THREAD

**Issue by jaeyun-jung** [nnsuite/nnstreamer#1971]
The case if nnfw requires multiple files and options.

```
/**
 * @brief Opens an ML model with multiple files and various options, and returns the instance as a handle.
 */
int ml_single_open_multi (ml_single_h *single, const char **files, const ml_tensors_info_h input_info, const ml_tensors_info_h output_info, ml_nnfw_type_e nnfw, ml_nnfw_hw_e hw, const char *options);
```

Ccurrent single API (open) cannot support this case.
e.g. SNAP-Caffe requires two files and other options

```
Pipeline : "videotestsrc ! videoconvert ! videoscale ! \
video/x-raw,format=RGB,width=224,height=224,framerate=(fraction)30/1 ! \
tensor_converter ! tensor_transform mode=typecast option=float32 ! \
tensor_filter framework=snap \
  model=/model.prototxt,/model.caffemodel \
  input=3:224:224:1 inputtype=float32 inputname=data \
  output=1:1:1000:1 outputtype=float32 outputname=prob \
  custom=ModelFWType:CAFFE,ExecutionDataType:FLOAT32,ComputingUnit:CPU ! \
tensor_sink"
```

**Comment by kparichay** [comment]
Do we need another function? How about add the support for multiple files in `ml_single_open` itself?
Also, I think taking a `comma separated list of files` might be directly applicable than `char **files` as input.

**Comment by jaeyun-jung** [comment]
1. changing old api (ml_single_open)
    - add new param for options and comma separated multi files
    - ACR for changing old native API
2. add new function (ml_single_open_xxx)
    - ACR for adding new native API

**Comment by jaeyun-jung** [comment]
Internal function to handle options.

later work: consider to open new API
