### ISSUE TITLE
Data layout information needed

### ISSUE THREAD

**Issue by kparichay** [nnsuite/nnstreamer#1986]
An input image in tensor format of size HxWxC can be provided as an input in HxWxC or CxHxW.
These are the most common of the two formats used in ML field (corresponding to NHWC or NCHW format). Generally, NCHW is preferred by GPU backend while NHWC is preferred for CPU backend for performance purposes.

Need to add API to take this information from user, and pass to extensions, if extensions support it (at least nnfw-runtime and armnn (as per the sample example) support it).

**Comment by jaeyun-jung** [comment]
In the first version of sub-plugin SNAP, I simply parsed custom string.
`tensor_filter framework=snap custom=ModelFWType:CAFFE,...,InputDataFormat:NHWC`

**Comment by kparichay** [comment]
If multiple sub-plugins are using this property (nnfw, snap, armnn), should this be added a property in tensor_filter?

**Comment by myungjoo** [comment]
Another constraints or conditions we can consider include:
1. We may keep ourselves totally agnostic to data layout or transparent to data layout (it's something between app developers and model developers?)
2. We handle not only vision models, but also sound/speech models or even models with pure numbers without physical dimensions (tensor outputs of other models). Data layout of w/h/c is very awkward thing; we can consider them simply as 1st, 2nd, and 3rd dimension. Then, this data layout becomes some additional syntactic sugar that we may provide, which simply represents a "conditional tensor_transform".

**Comment by myungjoo** [comment]
If a framework (I hear that some H/W frameworks do) mandates the data layout of input images, it should be handled by pipeline writers (app writers).

Anyway, Single API is the pipeline writer; thus, for Single APIs, we may consider supporting data layouts natively.

**Comment by kparichay** [comment]
> Another constraints or conditions we can consider include:
> 
> 1. We may keep ourselves totally agnostic to data layout or transparent to data layout (it's something between app developers and model developers?)

Yes, nnstreamer does not need to consider these layout for itself. It is to be passed to the framework.

> 2. We handle not only vision models, but also sound/speech models or even models with pure numbers without physical dimensions (tensor outputs of other models). Data layout of w/h/c is very awkward thing; we can consider them simply as 1st, 2nd, and 3rd dimension. Then, this data layout becomes some additional syntactic sugar that we may provide, which simply represents a "conditional tensor_transform".

Yes, this information will be optional from the perspective of nnstreamer.

**Comment by myungjoo** [comment]
Long Term Solution: #2015 (Please investigate in the background or after resolving other higher-priority tasks after 설날.)

Short Term Solution Suggestion:
    - Add a property or use the off-the-shelf property of tensor_filter. Provide some rules for subplugins to "read the property" and handle it if they can.
    - E.g., "optionXYZ=transposeBLAHBLAH"

**Comment by kparichay** [comment]
Added a short term solution with #2065.
