### ISSUE TITLE
Bug: .spec version mismatch

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#2036]
The current devel version is 1.3.0, as marked in meson.build and debian/changelog.

However packaging/nnstreamer.spec is not updated. Make all version numbers consistent.

- [ ] 1. meson.build
- [ ] 2. .spec #2040 @anyj0527 
- [ ] 3. debian
- [ ] 4. android jni

**Comment by wooksong** [comment]
I just checked 1) meson.build, 3) debian/changelog, and 4) jni/nnstreamer.mk.
