### ISSUE TITLE
Requirements: data layout

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#2051]
Related PR: #2007

1. Backward Compatibility: the previous pipelines and filters should work without any changes.
2. Data Layout Agnostic Streams: when not specified either by users or elements, all streams should be kept layout-agnostic (no layout, "none")
3. Auto Layout Negotiation: For example, with a pipeline, ```... ! tensor_converter ! tensor_filter something_mandates_NCHW ! ... ```, the tensor_converter should be able to convert the given inputs to NCHW tensor stream. Anyway, if there is no mandates, it may provide a default data layout that matches the given video/x-raw stream and tensor_filter should be able to accept such unless explicitly specified otherwise.

Before accepting any related changes, we need corresponding additional test cases as well:
1. ```videosrc ! POS ! tensor_converter ! tensor_filter conventional ! POS2 !  ...``` Check if POS has been given the intended data layout automatically.
2. ```videosrc ! POS ! tensor_converter ! tensor_filter requiring NCHW implicitly (automatically) ! POS2 ! ...``` Check if POS has been given the intended data layout (NCHW) automatically and tensor_converter converts the data format automatically.
3. ```videosrc ! POS ! tensor_converter ! tensor_filter requiring NONE implicitly (automatically) ! POS2 ! ...``` Check if POS has been given the intended data layout (NONE) automatically.
4. POS2 above should have NONE layout if no others mandate after that
5. POS2 above may bedome some layout with capsfilter.
6. ```POS2 ! tee name=t t. ! queue ! PIPE1 t. ! queue ! PIPE2```, where PIPE1 uses NCHW and PIPE2 uses NONE or ANY. How are you going to cope with this? (need decision)
7. How will merge/mux/split/demux/aggregator behave with data layout?

Note
- Having a property at tensor_filter so that a filter can transpose internally w/ hardware acceleration is fine as long as it is not invasive (do not make changes in CAPI or common data structure, #2007 is invasive.) E.g., having ```tensor_filter dataop='NHWC2NCHW' ...``` is fine for those who have hardware accelerators for such ops. We may rely on this while we solve this #2051 with the requirements above.

**Comment by kparichay** [comment]
**Base Proposal**
Representing data layout as `gst_type_list` of `g_type_enum` at the template stage. After the capabilities are fixed, this would be fixed as `gst_type_list`. 
PRO: Satisfies above requirements. Existing test cases pass. 
CON: Forces the data layout for all the tensors in `other/tensors` to be same. This is because fixed GstCaps cannot be a list or a range.

**Updated Proposal**
Representing data layout as `gst_type_list` of `gst_type_structure` at the template stage. After the capabilities are fixed, this would be fixed as `gst_type_structure`. Each `gst_type_structure` is allowed to have multiple fields in it. Each field in the structure would denote the data layout of each tensor in `other/tensors`.
PRO: Keeps all the PRO from base proposal. Allows all tensors in `other/tensors` to be different.
CON: [Limited support](https://github.com/GStreamer/gstreamer/blob/f018b4eddcbf27b62f7d3ec1cd4dbf3855b8a202/gst/gstcaps.c#L55) of nested GstStructure for serialization. Note that serialization is not used in caps negotiation but for getting string version of caps for debugging and logging.

**Comment by kparichay** [comment]
**Updated Proposal**
Representing data layout as `gst_type_list` of `gst_type_structure` at the template stage. After the capabilities are fixed, this would be fixed as `gst_type_structure`. Each `gst_type_structure` is allowed to have multiple fields in it. Each field in the structure would denote the data layout of each tensor in `other/tensors`.
PRO: Keeps all the PRO from base proposal. Allows all tensors in `other/tensors` to be different.
CON: [Limited support](https://github.com/GStreamer/gstreamer/blob/f018b4eddcbf27b62f7d3ec1cd4dbf3855b8a202/gst/gstcaps.c#L55) of nested GstStructure for serialization. Note that serialization is not used in caps negotiation but for getting string version of caps for debugging and logging.

**Comment by jaeyun-jung** [comment]
Adding new property in tensor-filter (inputlayout and outputlayout)
For the pipeline APIs, it can be done without the changes. But single-shot needs another APIs to set/get the layout in tensors-info. (IMO, no way to set the layouts for single-shot)

Proposal : add new functions to set/get the layouts 
```
/**
 * @brief Possible data layout of tensor in NNStreamer.
 * @details Some frameworks like NNFW and SNAP requires the data layout of tensor to invoke the model.
 *          To run these frameworks, the application should set the proper tensor layout using ml_tensors_info_set_tensor_layout().
 * @since_tizen 6.0
 */
typedef enum _ml_tensor_layout_e
{
  ML_TENSOR_LAYOUT_NONE = 0,      /**< Default, not specified. */
  ML_TENSOR_LAYOUT_NHWC = 1,      /**< Channel first layout. */
  ML_TENSOR_LAYOUT_NCHW = 2,      /**< Channel last layout. */
} ml_tensor_layout_e;

/**
 * @brief Sets the tensor layout with given handle of tensors information.
 * @since_tizen 6.0
 * @param[in] info The handle of tensors information.
 * @param[in] index The index of the tensor to be updated.
 * @param[in] layout The tensor layout to be set.
 * @return @c 0 on success. Otherwise a negative error value.
 * @retval #ML_ERROR_NONE Successful
 * @retval #ML_ERROR_NOT_SUPPORTED Not supported.
 * @retval #ML_ERROR_INVALID_PARAMETER Given parameter is invalid.
 */
int ml_tensors_info_set_tensor_layout (ml_tensors_info_h info, unsigned int index, const ml_tensor_layout_e layout);

/**
 * @brief Gets the tensor layout with given handle of tensors information.
 * @since_tizen 6.0
 * @param[in] info The handle of tensors information.
 * @param[in] index The index of the tensor.
 * @param[out] layout The tensor layout.
 * @return @c 0 on success. Otherwise a negative error value.
 * @retval #ML_ERROR_NONE Successful
 * @retval #ML_ERROR_NOT_SUPPORTED Not supported.
 * @retval #ML_ERROR_INVALID_PARAMETER Given parameter is invalid.
 */
int ml_tensors_info_get_tensor_layout (ml_tensors_info_h info, unsigned int index, ml_tensor_layout_e *layout);
```

**Comment by myungjoo** [comment]
@jaeyun-jung Your proposal potentially requires GST-CAP to have layout info. The APIs you proposed require appsrc & appsink to be aware of layout, which should be propagated to corresponding tensor_filter.

**Comment by jaeyun-jung** [comment]
With the tensor-filter property 'inputlayout' and 'outputlayout'
1. Pipeline : no problem
2. Single : need discussion, how to set the layouts for single-shot instance

**Comment by myungjoo** [comment]
Let's re-open this up when the need arises even after the introduction of new properties of tensor_filter.
