### ISSUE TITLE
TensorFlow Meeting Preparation

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#2054]
I'm accepting comments, questions, and requests until 2020-01-28

Requests/Requirements for Tensorflow
- TF Core
- TF tooling, profiling, debugging
- Platform / Mobile / IoT related
    - Build issue
        - Bazel
        - QEMU env
    - Dependency issue
        - Java dependency
        - SystemLIB compatibility
    - Packaging & releasing
    - C API
- Server/Enterprise/OSS/...
- Infra, H/W support
- Privacy / Fairness
- TF Agents
- TF Federated
- Others

**Comment by dellabee** [comment]
As far as I know, the Fairness Index (beta) service introduced by Google in November 2019 includes TensorFlow model analysis, fairness metrics, TensorFlow data verification, and what if tool (WIT) tools. Among them, the fairness indicator is included in the TensorFlow Extended (TFX) component, and it is understood that the evaluation tool can check the fairness indicator and verify and verify related data. WIT allows us to choose one definition of fairness out of 5 according to the situation, but it seems to be insufficient in reality. Is there industry-level or Google-level recommendations for a single mathematical best definition for the fairness, applicable to machine learning in real?

**Comment by myungjoo** [comment]
Meeting done.
