### ISSUE TITLE
Pytorch compatibility problem

### ISSUE THREAD

**Issue by juncheolye** [nnsuite/nnstreamer#2093]
When I using pytorch model(1) with tensor_filter, it works well.
pytorch model(1) : nnstreamer/tests/test_models/models/pytorch_lenet5.pt

But pytorch model(2) produced by own pytorch framework got a problem like this.
pytorch program : nnstreamer/tests/nnstreamer_filter_pytorch/create_mnist_jit.py

Setting pipeline to PAUSED ...
** Message: 16:17:43.956: gpu = 0, accl = default
terminate called after throwing an instance of 'c10::Error'
  what():  isGenericList() ASSERT FAILED at /build/pytorch-lnE7nO/pytorch-1.1.0/aten/src/ATen/core/ivalue.h:385, please report a bug to PyTorch. (toGenericList at /build/pytorch-lnE7nO/pytorch-1.1.0/aten/src/ATen/core/ivalue.h:385)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x78 (0x7f94b66e40 in /usr/lib/libc10.so)
frame #1: <unknown function> + 0x824bb0 (0x7f92265bb0 in /usr/lib/libtorch.so.1)
frame #2: torch::jit::Unpickler::parse_ivalue_list() + 0x58 (0x7f92263540 in /usr/lib/libtorch.so.1)
frame #3: <unknown function> + 0x9176ec (0x7f923586ec in /usr/lib/libtorch.so.1)
frame #4: torch::jit::load(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x2e8 (0x7f92359e30 in /usr/lib/libtorch.so.1)
frame #5: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x84 (0x7f9235a10c in /usr/lib/libtorch.so.1)
frame #6: TorchCore::loadModel() + 0xcc (0x7f94be24c8 in /home/nvidia/nnstreamer/lib/nnstreamer/filters/libnnstreamer_filter_pytorch.so)
frame #7: TorchCore::init(_GstTensorFilterProperties const*) + 0xa4 (0x7f94be2394 in /home/nvidia/nnstreamer/lib/nnstreamer/filters/libnnstreamer_filter_pytorch.so)
frame #8: <unknown function> + 0x59690 (0x7f94be3690 in /home/nvidia/nnstreamer/lib/nnstreamer/filters/libnnstreamer_filter_pytorch.so)
frame #9: <unknown function> + 0x59734 (0x7f94be3734 in /home/nvidia/nnstreamer/lib/nnstreamer/filters/libnnstreamer_filter_pytorch.so)
frame #10: gst_tensor_filter_common_open_fw + 0xa4 (0x7f94ee9b20 in /home/nvidia/nnstreamer/lib/gstreamer-1.0/libnnstreamer.so)

Aborted (core dumped)

pytorch model(1), (2) were generated by exactly same code (create_mnist_jit.py).

So, I think it's a compatibility problem.

What's wrong on this?
Thanks!

    PyTorch Version: 1.1.0
    OS: Ubuntu 18.04
    Python version: 3.6

**Comment by myungjoo** [comment]
You need to describe your pipeline and input/output specification of your model.

Anyway, the log says PyTorch cannot load the given model. Have you tried to load your model with PyTorch directly? (torch::jit::load("YOUR MODEL") has failed)

**Comment by juncheolye** [comment]
Gstreamer pipeline:

gst-launch-1.0 filesrc location=${PATH_TO_IMAGE} ! pngdec ! videoscale ! imagefreeze ! videoconvert ! video/x-raw, format=GRAY8, framerate=0/1 ! tensor_converter ! tensor_filter framework=pytorch model=${PATH_TO_MODEL2} input=1:28:28:1 inputtype=uint8 output=10:1:1:1 outputtype=uint8 ! filesink location=tensorfilter.out.log

I used the script in runTest.sh(path : nnstreamer/tests/nnstreamer_filter_pytorch/runTest.sh)

The problem occurs before the gstreamer pipeline is aligned.

As you say, I tried to run simple loading example using ppa-nnstreamer-pytorch library(libtorch.so)

#include <torch/script.h> // One-stop header.

#include <iostream>
#include <memory>

int main(int argc, const char* argv[]) {
  if (argc != 2) {
    std::cerr << "usage: example-app <path-to-exported-script-module>\n";
    return -1;
  }

  // Deserialize the ScriptModule from a file using torch::jit::load().
  std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);

  assert(module != nullptr);
  std::cout << "ok\n";
}

This is the code I used. It can be found in pytorch tutorial.

First case: As before,  there is no problem using model provided by nnstreamer repo. (nnstreamer/tests/test_models/models/pytorch_lenet_5.py)

Second case: But it still has a same problem to using own pytorch framework.

First case: 
~/example-app/build$ ./example-app ../pytorch_lenet5.pt 
ok

Second case:
./example-app ../pytorch_lenet5_365.pt 
terminate called after throwing an instance of 'c10::Error'
  what():  isGenericList() ASSERT FAILED at /build/pytorch-lnE7nO/pytorch-1.1.0/aten/src/ATen/core/ivalue.h:385, please report a bug to PyTorch. (toGenericList at /build/pytorch-lnE7nO/pytorch-1.1.0/aten/src/ATen/core/ivalue.h:385)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x78 (0x7f9a64de40 in /usr/lib/libc10.so)
frame #1: <unknown function> + 0x824bb0 (0x7f9d325bb0 in /usr/lib/libtorch.so.1)
frame #2: torch::jit::Unpickler::parse_ivalue_list() + 0x58 (0x7f9d323540 in /usr/lib/libtorch.so.1)
frame #3: <unknown function> + 0x9176ec (0x7f9d4186ec in /usr/lib/libtorch.so.1)
frame #4: torch::jit::load(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x2e8 (0x7f9d419e30 in /usr/lib/libtorch.so.1)
frame #5: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x84 (0x7f9d41a10c in /usr/lib/libtorch.so.1)
frame #6: main + 0xa0 (0x557825474c in ./example-app)
frame #7: __libc_start_main + 0xe0 (0x7f9a6bd6e0 in /lib/aarch64-linux-gnu/libc.so.6)
frame #8: <unknown function> + 0x4504 (0x5578254504 in ./example-app)

Aborted (core dumped)

**Comment by kparichay** [comment]
Different versions of pytorch can have incompatibilities between the serialization of the models.

> First case: As before, there is no problem using model provided by nnstreamer repo.(nnstreamer/tests/test_models/models/pytorch_lenet_5.py)

As you can run the model provided with nnstreamer, I assume that the pytorch you are using with nnstreamer is compatible with this serialized model file provided. 

> Second case: But it still has a same problem to using own pytorch framework.

Did you try using the same pytorch to serialize the model?

I tested with the pytorch provided with nnstreamer ppa (https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa). I serialized an already saved model with this pytorch, and ran it with nnstreamer without any errors. Please try with the pytorch provided with nnstreamer ppa.

Note: `create_mnist_jit.py` provides a sample code to serialize an already saved model. The saved model can be trained with a different version of the pytorch as long as the below two conditions are met:
- the layers in the saved model are supported with the pytorch used to serialize.
- the saved model file (the dictionary format and not the serialized version) is compatible with both the pytorch.

**Comment by juncheolye** [comment]
It works well!!!
Thanks!!!

I thought public pytorch 1.1.0 (conda install) and  nnstreamer ppa pytorch 1.1.0 are same because  specified version is same.

What's difference between?

**Comment by kparichay** [comment]
Although nnstreamer pytorch ppa is also 1.1.0 version, however it is at commit [84b275b70f73d5fd311f62614bccc405f3d5bfa3](https://github.com/pytorch/pytorch/commit/84b275b70f73d5fd311f62614bccc405f3d5bfa3) but it is roughly 100 commits behind the 1.1.0 tag in pytorch github.
I will rebase the nnstreamer ppa pytorch with the 1.1.0 tag in pytorch github soon.

**Comment by juncheolye** [comment]
I completely understand.
Thanks for your advice.
