### ISSUE TITLE
pytorch gpu error

### ISSUE THREAD

**Issue by juncheolye** [nnsuite/nnstreamer#2104]
# Pipeline Description

> $ gst-launch-1.0 v4l2src device="/dev/video1" ! videoconvert ! videoscale ! video/x-raw, width=${WIDTH}, height=${HEIGHT}, format=RGB ! videoconvert ! tensor_converter ! tensor_filter framework=pytorch model=${MODEL_PATH} input=3:${WIDTH}:${HEIGHT}:1 inputtype=uint8 output=3:${OUT_WIDTH}:${OUT_HEIGHT}:1 outputtype=uint8 accelerator=true:gpu ! tensor_decoder mode=direct_video ! videoconvert ! xvimagesink

Error Message
===============

> ** Message: 14:19:26.360: gpu = 1, accl = gpu
> terminate called after throwing an instance of 'c10::Error'
>   what():  p ASSERT FAILED at /build/pytorch-lnE7nO/pytorch-1.1.0/c10/core/impl/DeviceGuardImplInterface.h:132, please report a bug to PyTorch. DeviceGuardImpl for cuda is not available (getDeviceGuardImpl at /build/pytorch-lnE7nO/pytorch-1.1.0/c10/core/impl/DeviceGuardImplInterface.h:132)
> frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x78 (0x7f7f602e40 in /usr/lib/libc10.so)
> frame #1: at::native::to(at::Tensor const&, c10::Device, c10::ScalarType, bool, bool) + 0xd0c (0x7f7db5d52c in /usr/lib/libcaffe2.so)
> frame #2: at::TypeDefault::to(at::Tensor const&, c10::Device, c10::ScalarType, bool, bool) const + 0x3c (0x7f7dd72764 in /usr/lib/libcaffe2.so)
> frame #3: torch::jit::script::Module::to_impl(c10::optional<c10::Device> const&, c10::optional<c10::ScalarType> const&, bool) + 0x4b0 (0x7f7cf5cdb0 in /usr/lib/libtorch.so.1)
> frame #4: torch::jit::script::Module::to_impl(c10::optional<c10::Device> const&, c10::optional<c10::ScalarType> const&, bool) + 0x60 (0x7f7cf5c960 in /usr/lib/libtorch.so.1)
> frame #5: torch::jit::script::Module::to_impl(c10::optional<c10::Device> const&, c10::optional<c10::ScalarType> const&, bool) + 0x60 (0x7f7cf5c960 in /usr/lib/libtorch.so.1)
> frame #6: torch::jit::script::Module::to_impl(c10::optional<c10::Device> const&, c10::optional<c10::ScalarType> const&, bool) + 0x60 (0x7f7cf5c960 in /usr/lib/libtorch.so.1)
> frame #7: torch::jit::script::Module::to(c10::Device, bool) + 0x44 (0x7f7cf5d59c in /usr/lib/libtorch.so.1)
> frame #8: TorchCore::loadModel() + 0x170 (0x7f7f67e56c in /home/nvidia/nnstreamer/lib/nnstreamer/filters/libnnstreamer_filter_pytorch.so)
> frame #9: TorchCore::init(_GstTensorFilterProperties const*) + 0xa4 (0x7f7f67e394 in /home/nvidia/nnstreamer/lib/nnstreamer/filters/libnnstreamer_filter_pytorch.so)
> frame #10: <unknown function> + 0x59690 (0x7f7f67f690 in /home/nvidia/nnstreamer/lib/nnstreamer/filters/libnnstreamer_filter_pytorch.so)
> frame #11: <unknown function> + 0x59734 (0x7f7f67f734 in /home/nvidia/nnstreamer/lib/nnstreamer/filters/libnnstreamer_filter_pytorch.so)
> frame #12: gst_tensor_filter_common_open_fw + 0xa4 (0x7f7f828b20 in /home/nvidia/nnstreamer/lib/gstreamer-1.0/libnnstreamer.so)
> 
> Aborted (core dumped)

It looks like torch cannot find GPU.
I'm using pytorch library produced by nnstreamer/ppa.
What cuda and cudnn version does this package support?

Further Information
===============
* Ubuntu 18.04
* pytorch 1.1.0
* CUDA 10.0
* cuDNN 7.63

**Comment by kparichay** [comment]
The PyTorch package available with nnstreamer PPA is not built with GPU.
You will have to build your PyTorch with GPU yourself, which you can directly run with PyTorch.

Note that you should the PyTorch you build yourself to serialize the model to use.

**Comment by myungjoo** [comment]
This is pytorch-build issue (you need to build and install pytorch-gpu to use gpu w/ pytorch) and completely not related with nnstreamer, I'm closing it.

As @kparichay has mentioned, we do not release PyTorch-GPU. We release PyTorch (non-GPU) only in order to build nnstreamer-pytorch and we are not the official PyTorch maintainer or distributor. You can simply install PyTorch-GPU to enable PyTorch-GPU + nnstreamer-pytorch.

We will (and are able to) address the issue if PyTorch-GPU does not work in nnstreamer pipelines while the same PyTorch-GPU binary works well without nnstreamer.
