### ISSUE TITLE
Framework Auto Detection

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#2128]
Like what we do with Single API, tensor_filter may be able to configure its framework automatically based on the model path.

We will be able to allow to omit framework property with default value of 'auto'.

**Comment by gichan-jang** [comment]
Does it automatically detect when the user omits the framework option?

**Comment by jaeyun-jung** [comment]
TODO
ini file : prioritize_tflite_ex should be removed after setting the fw priority.

**Comment by gichan-jang** [comment]
This issue is solved with #2159
