### ISSUE TITLE
[REGRESSION] TF-Lite/TF

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#2145]
@gichan-jang and @anyj0527 has reported a regression in the behavior of TF-Lite/TF with recent commits.

@gichan-jang / @anyj0527 Please describe the issue and its progress here.

**Comment by anyj0527** [comment]
After #2135,
3 Native tflite examples from nnstreamer-example got segmentation faults.
- speech-command-tflite
- object-detection-tflite
- pose-estimation-tflite

The output of speech-command example:
`
$ ./nnstreamer_example_speech_command_tflite 
**
ERROR:/home/yongjoo/nnstreamer/gst/nnstreamer/tensor_filter/tensor_filter.c:641:gst_tensor_filter_configure_tensor: assertion failed: (gst_tensors_config_is_equal (&priv->out_config, &out_config))
`

**Comment by gichan-jang** [comment]
It's the  same as @anyj0527 

$ ./nnstreamer_example_pose_estimation_tflite 
  Segmentation fault (core dumped)
$ ./nnstreamer_example_speech_command_tflite 
**
ERROR:/home/gichan/workspace/nnstreamer/gst/nnstreamer/tensor_filter/tensor_filter.c:641:gst_tensor_filter_configure_tensor: assertion failed: (gst_tensors_config_is_equal (&priv->out_config, &out_config))
Aborted (core dumped)

**Comment by myungjoo** [comment]
@anyj0527 We'll need a fix this week, preferably submitted by today.

**Comment by wooksong** [comment]
IMO, at least for the case of speech-command-tflite, it is not related to the tf-lite tensorfilter. PTAL, @jaeyun-jung @myungjoo.

**Comment by anyj0527** [comment]
I found that when a tflite model has output tensors of more than one, 
` tensor_ptr = interpreter->tensor (tensor_idx) `
has different value after the first invoke().

(This was not happend when the model has one output tensor)

IMO, #2135 assumes that pointers to input/output tensor are not changed, causing this issue.

**Comment by kparichay** [comment]
@gichan-jang and @anyj0527 Thanks for figuring out this issue and solving it.
I will raise an issue with TensorFlow-lite and confirm if this is intended or a bug on their side.

**Comment by wooksong** [comment]
We need to revert #2135 but it seems that object-detection-tflite also has some bugs itself.

**Comment by anyj0527** [comment]
@wooksong Thank you for the report, I'll check the object-detection-tflite example
