### ISSUE TITLE
tensorflow example segmentation fault

### ISSUE THREAD

**Issue by ddeokho** [nnsuite/nnstreamer#2187]
안녕하세요.

[tensorflow 예제](https://github.com/nnsuite/nnstreamer/wiki/usage-examples-screenshots#example--camera-live-view-object-detection-decoded-by-user-application-with-tensorflow)를 sudo권한으로 동작시켰을 때는 잘 돌아가지만 **sudo권한 없이 동작시키면 segmentaion fault가 나오는 이슈**가 있어 어떻게 해결하면 좋을지 찾지 못해 질문드립니다.

os : 우분투 18.04.3 LTS

sudo 권한 실행
```
(py36) deokho@deokho-ThinkPad-T480s:~/nnstreamer/bin$ sudo ./nnstreamer_example_object_detection_tf
2020-03-20 13:31:45.686699: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
```

sudo 권한 없이 실행
```
(py36) deokho@deokho-ThinkPad-T480s:~/nnstreamer/bin$ ./nnstreamer_example_object_detection_tf

(nnstreamer_example_object_detection_tf:8131): GLib-CRITICAL **: 13:09:52.544: g_file_test: assertion 'filename != NULL' failed
Segmentation fault (core dumped)

```

**Comment by wooksong** [comment]
Check the permissions, owner, attibute of ./tf_model/ssdlite_mobilenet_v2.pb in your binary directory.
```bash
(py36) deokho@deokho-ThinkPad-T480s:~/nnstreamer/bin$ ls -al ./tf_model/
```

**Comment by myungjoo** [comment]
If you want useful answers for segmentation faults, you should provide at least (probably with gdb):
- stack trace of the faulty thread
- values of related variables
- source code of faulty thread along with fault location

And file permission issues are not related with nnstreamer, they are OS-related issues. Simply check if you can access all the related files.

In general, you should provide related info (e.g., if file permission is the issue, you need to provide file permission info. if segmentation fault is the issue, you need to provide thread/stack/memory information. if an execution of an API is problem, you need to provide a minimal reproducible code. )

**Comment by ddeokho** [comment]
- permission
ls -al 커맨드를 이용해 파일들을 확인해 보았을 때 접근 허용이었습니다. 문제는 아직 해결하지 못했지만 permission 관련해서 제 환경에 맞게 스스로 찾아보도록 하겠습니다. 

- segmentation fault
gdb와 같은 keyword를 알려주셔서 segmentation fault를 해결할 수 있었습니다. 

며칠을 헤매던 문제인데 친절히 답변해 주셔서 빠르게 해결할 수 있었습니다. 감사합니다!

**Comment by wooksong** [comment]
@ddeokho Unless you have other questions or problems related to this issue, please close it.
