### ISSUE TITLE
[Test Framework] Import SSAT? :)

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#254]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Monday Jul 02, 2018 at 05:00 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/189_

----

http://github.com/myungjoo/SSAT

**Comment by myungjoo** [comment]
Now, the need for SSAT is arising...

**Comment by myungjoo** [comment]
Done.
