### ISSUE TITLE
[Test Framework] Proper testing scheme with gstreamer needed. gst-launch is not appropriate!

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#269]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Tuesday Jul 03, 2018 at 01:48 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/204_

----

From gstreamer web page:
```
gst-launch is not a good tool to show that your element is finished. Applications such as Rhythmbox and Totem (for GNOME) or AmaroK (for KDE) are. gst-launch will not test various things such as proper clean-up on reset, event handling, querying and so on.
```
https://gstreamer.freedesktop.org/documentation/plugin-development/appendix/checklist-element.html

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jul 03, 2018 at 01:48 GMT_

----

:octocat: **cibot**: Thank you for posting issue #204. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Let's ignore this advice for a while as it appears to be not too relevant.
