### ISSUE TITLE
Migrate issues/PRs from internal github

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#3]
While CI system is being migrated to github.com, we also need our dev history migrated to here.

**Comment by myungjoo** [comment]
This is one of github migration tools: https://github.com/google/github-issue-mover

**Comment by leemgs** [comment]
@ohsewon , Please follow-up the activity for nnstreamer repository after reading  https://github.com/google/github-issue-mover.  In case of TAOS-CI repostiroy,  I will try to do the activity for data migration of the github issue .

**Comment by ohsewon** [comment]
https://github.com/google/github-issue-mover, support only open github(https://github.com)
https://github.com/ahadik/git_mover, Doesn't work.

**Comment by ohsewon** [comment]
git mover example)
Github Profile→Settings→Personal Access Tokens. Save it in an environment variable: 
```SOURCETOKEN=… ``` Same as ```DESTTOKEN=...```
```bash
$ python git-mover.py -dt $DESTTOKEN -dun ohsewon -sr https://github.sec.samsung.net -dr https://api.github.com [--issues, --milestones, --labels] sewon.oh@samsung.com $SOURCETOKEN STAR/nnstreamer nnsuite/nnstreamer

**Comment by ohsewon** [comment]
git_mover has many problems. it is recommended not to use.

**Comment by leemgs** [comment]
I try to test the below tools in case of TAOS-CI repository (e.g., https://github.com/nnsuite/TAOS-CI).
* https://github.com/IQAndreas/github-issues-import
* https://chrome.google.com/webstore/detail/kamino/ffdebockfdjileaojbbccofhgncmioaf?hl=en-US

**Comment by leemgs** [comment]
I have newly created a fork as follows  as a next-generation (NG) version to import successfully issues & pull requests:
* https://github.com/leemgs/github-issues-import-ng

**Comment by ohsewon** [comment]
https://github.com/ohsewon/test/issues - import issue result

**Comment by ohsewon** [comment]
done.
