### ISSUE TITLE
[BaseTransform Users] Find out "filter" of transform_caps

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#318]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Tuesday Jul 10, 2018 at 09:58 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/252_

----

We are implementing "transform_caps" vmethod without considering "filter" parameter.

TODO:
1. Get to know what the heck if "filter" parameter for transform_caps vmethod
2. Apply "filter" to BaseTransform children classes.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jul 10, 2018 at 09:58 GMT_

----

:octocat: **cibot**: Thank you for posting issue #252. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Closing as I now understand this issue :)
