### ISSUE TITLE
[Filter] Apply other/tensors

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#364]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Wednesday Jul 18, 2018 at 07:21 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/298_

----

Upgrade filter to support other/tensors.

1. Upgrade filter/main
2. Upgrade filter subplugins

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Jul 18, 2018 at 07:21 GMT_

----

:octocat: **cibot**: Thank you for posting issue #298. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Duplicated with #111
