### ISSUE TITLE
RunTest/ARM: NNStreamer CI support for ARM v8 (64bit) embedded devices

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#368]
<a href="https://github.sec.samsung.net/geunsik-lim"><img src="https://github.sec.samsung.net/avatars/u/8170?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [geunsik-lim](https://github.sec.samsung.net/geunsik-lim)**
_Thursday Jul 19, 2018 at 04:49 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/302_

----

It seems that NNStreamer guys also have to develop NNStreamer CI support in order to support ARM v8 (64bit) embedded devices 

**GStreamer CI support for embedded devices:**
* https://www.collabora.com/news-and-blog/blog/2018/06/11/gstreamer-ci-support-for-embedded-devices/

----

Step 1: Add gbs test build for aarch64. (trivial)
Step 2: Test on an aarch64 machine with aarch64 userspace binary image. (expected to be trivial, but could be problematic)

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 19, 2018 at 04:49 GMT_

----

:octocat: **cibot**: Thank you for posting issue #302. The person in charge will reply soon.

**Comment by leemgs** [comment]
$ invain@mymate:/work/taos/nnstreamer$ time gbs build -A aarch64
............. OMISSION ......................

=== Total succeeded built packages: (2) ===
info: generated html format report:
     /home/invain/GBS-ROOT-Snapshot/local/repos/tizen/aarch64/index.html
info: generated RPM packages can be found from local repo:
     /home/invain/GBS-ROOT-Snapshot/local/repos/tizen/aarch64/RPMS
info: generated source RPM packages can be found from local repo:
     /home/invain/GBS-ROOT-Snapshot/local/repos/tizen/aarch64/SRPMS
info: build logs can be found in:
     /home/invain/GBS-ROOT-Snapshot/local/repos/tizen/aarch64/logs
info: build roots located in:
     /home/invain/GBS-ROOT-Snapshot/local/BUILD-ROOTS/scratch.aarch64.*
info: Done

real	8m46.203s
user	7m50.796s
sys	0m12.160s

@ohsewon ,Please dicide the activity of this issue between 'close' and still 'open' status?

**Comment by ohsewon** [comment]
IMO,  It is necessary to add gbs test build for aarch64

**Comment by myungjoo** [comment]
The additional memory module for the CI server is going to be delivered tomorrow. Hang tight. ;)

**Comment by myungjoo** [comment]
Done
