### ISSUE TITLE
[Tensor Type] New Type Required: 64b Integer

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#370]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 19, 2018 at 05:23 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/304_

----

From #303 

64bit integers are required!

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 19, 2018 at 05:23 GMT_

----

:octocat: **cibot**: Thank you for posting issue #304. The person in charge will reply soon.

**Comment by myungjoo** [comment]
jaeyun-jung:
> added _NNS_INT64 and _NNS_UINT64

**Comment by myungjoo** [comment]
@jaeyun-jung Then, is it complete? (close this when you have added testcases as well)

**Comment by jaeyun-jung** [comment]
PR #493 (refactoring tensor-converter with gst-adapter)
added testcases for text, audio, and aggregator.

added simple stream test with tensor-transform
