### ISSUE TITLE
[Tensor Type] String!

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#371]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 19, 2018 at 05:24 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/305_

----

From #303 

- [x] Design how to support string type
- [x] Implement.
- [ ] Enough test cases.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 19, 2018 at 05:24 GMT_

----

:octocat: **cibot**: Thank you for posting issue #305. The person in charge will reply soon.

**Comment by myungjoo** [comment]
jaeyun-jung:
> added text/x-raw for media type _NNS_STRING

**Comment by myungjoo** [comment]
Close this when you have
1. resolved the frame-size / dimension issue
2. added proper testcases for strings.

**Comment by jaeyun-jung** [comment]
PR #493 (refactoring tensor-converter with gst-adapter)
added testcases for text,  audio, and aggregator.

tensor with fixed size of string type (GST_TENSOR_STRING_SIZE)
