### ISSUE TITLE
[Tensor Mux / Tensor Demux] Should support framerate

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#400]
<a href="https://github.sec.samsung.net/jijoong-moon"><img src="https://github.sec.samsung.net/avatars/u/19415?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jijoong-moon](https://github.sec.samsung.net/jijoong-moon)**
_Wednesday Jul 25, 2018 at 09:52 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/334_

----

# Issue Description
Tensor Mux & Demux should sync by the frame rate accordingly.

```bash
                                ------------------> fixed frame rate
tensor 1 -->    +-----------------+      X     |    3   |    X    |
tensor 2 -->    |  tensor mux     |      1     |    X   |    5    |
tensor 3 -->    +-----------------+      2     |    4   |    6    |
                                         |          |         |
                                        \/         \/        \/
                                       none      tensors   tensors  
                                                 [ 3,1,4 ] [ 3,5,6 ]
```

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Jul 25, 2018 at 09:52 GMT_

----

:octocat: **cibot**: Thank you for posting issue #334. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Default policy implemented. Create another issue if you need additional / optional policies
