### ISSUE TITLE
[Arch Decision] ROS Node of Tensor_Sink or "Tensor_ROS" plugin

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#404]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 26, 2018 at 00:40 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/338_

----

An ROS node that sends ROS topic with frames from tensor_sink?

Or maybe we can provide tensor_sink_ros or tensor_to_ros plugin.

Reference: http://wiki.ros.org/gscam

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 00:40 GMT_

----

:octocat: **cibot**: Thank you for posting issue #338. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Decision after architecture review meeting of 2018.09.06: we need a separated element for ROS-Sink!
