### ISSUE TITLE
[Dist Decision] Install Path of GST Plugins

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#405]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 26, 2018 at 02:37 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/339_

----

We need to configure gst plugin install paths per SW platform. (ubuntu, tizen, smp).
We need to let users use nnstreamer without configuring gst-plugin-paths.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 02:37 GMT_

----

:octocat: **cibot**: Thank you for posting issue #339. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Fixed with an old PR.
