### ISSUE TITLE
[GUI Tool] pipeviz is not compatible with tensor_* filters.

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#409]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 26, 2018 at 08:11 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/343_

----

If we add tensor_converter (other tensor_* filters are not tested) into a pipeviz ( https://github.com/virinext/pipeviz ) gstreamer pipeline, we soon get:
```
mzx@kohaku:/source/AutoDrv/pipeviz$ ./pipeviz  --gst-plugin-path ../NNStreamer/build/gst/tensor_converter/:../NNStreamer/build/gst/tensor_filter/:../NNStreamer/build/gst/tensor_decoder/
failed to get the current screen resources
QXcbConnection: XCB error: 170 (Unknown), sequence: 163, resource id: 90, major code: 146 (Unknown), minor code: 20
Segmentation fault (core dumped)
mzx@kohaku:/source/AutoDrv/pipeviz$ 
```

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 08:11 GMT_

----

:octocat: **cibot**: Thank you for posting issue #343. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/jinhyuck83-park"><img src="https://github.sec.samsung.net/avatars/u/16767?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jinhyuck83-park](https://github.sec.samsung.net/jinhyuck83-park)**
_Wednesday Aug 08, 2018 at 10:55 GMT_

----

this segmentation fault is caused because there is no data GstTensor_Filter_Framework *fw 
in gst_tensor_filter_property_process function. 
in case of nnstreamer filter example(working), example app loads tensorflow-lite model, and use filter with tensorflow-lite 
but pipeviz, there is no steps to load which nnframework sub-plugin filter use .
so I think there are two possible cadidates to use pipeviz with our nnstreamer.

case 1.
Make own complete filter that loads specific nnstreamer data model.
Pros : no need to modify pipeviz
Cons: have to make every filters with every nnframework

case 2.
Modify pipeviz that allows filter could load nnframework and load data model.
Pros: no need to make every filters that suits for every specific nnframework(tensorflow, tensorflow-lite,caffe ...)
Cons: need to modify pipeviz and don't know it would really works

**Comment by jinhyuck-park** [comment]
when running Pipeviz, all elements are in run-time. so when changing tensor filter's property, set property is 
called while run-time. but currently, tensor filter's set property method does not allows set property in run-time with assertion codes. so will be considered allow set property while run-time when pipeviz runnig mode.
