### ISSUE TITLE
Research & Choose standard (for us) GUI stream design tool!

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#413]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 26, 2018 at 11:29 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/347_

----

1. Required: GUI-based stream design (e.g., pipeviz)
2. Required: tensor_* must be supported (or could be tensor_*'s faults... though...)
3. Required: save/load stream design.
4. Highly recommended: code generation from the GUI-drawn pipelines
5. Highly recommended: supports both Linux and Windows.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 11:29 GMT_

----

:octocat: **cibot**: Thank you for posting issue #347. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Postponed: tensor_decoder has higher priority.

**Comment by myungjoo** [comment]
1. pipeviz
2. firtree (not maintained for 10 years)
3. gst-editor (site abandoned)

So.. it seems pipeviz is the answer for us.
