### ISSUE TITLE
[Converter] Support audio/x-raw

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#416]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 26, 2018 at 11:42 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/350_

----

Support audio/x-raw with converter.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 11:42 GMT_

----

:octocat: **cibot**: Thank you for posting issue #350. The person in charge will reply soon.

**Comment by myungjoo** [comment]
This appears to be implemented. Please add proper unit testcases and clost this.

**Comment by myungjoo** [comment]
@jaeyun-jung Please check the audio support status. (looks like you've even added test cases and they are working fine.)

**Comment by jaeyun-jung** [comment]
PR #493 (refactoring tensor-converter with gst-adapter)
added testcases for text, audio, and aggregator.
