### ISSUE TITLE
[Merge] Implement!

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#417]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 26, 2018 at 11:46 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/351_

----

Implement tensor_merge.

Unlike tensor_mux, this creates a "larger" single tensor from multiple "smaller" tensors.
- mux creates other/tensors from multiple instances of other/tensor
- merge creates other/tensor (no s!!!) from multple instance of other/tensor

mux is useful for creating a single stream-line with different types of tensors. (e.g., video and audio). merge is useful for creating a single tensor from tensors that may placed in a same plane or with same dimensions (e.g., expanding colorspaces by merging RGB video with IR video, adding more channels to same dimensions by merging images of stereo-cameras, stiching RGB videos from mutliple cameras directing different angles.)

tensor_merge is found to be required by Project:FX.
Its priority has been increased.

You may implement the specific mode/option for Project:FX only.

CC: @again4you @wooksong

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 11:46 GMT_

----

:octocat: **cibot**: Thank you for posting issue #351. The person in charge will reply soon.

**Comment by myungjoo** [comment]
@wooksong @again4you You need to implement tensor_merge for Project:FX.

**Comment by myungjoo** [comment]
Please create another issue if you need sub-feature of merge. @jijoongmoon @wooksong
