### ISSUE TITLE
[Example] Multi-Cam with TF-Lite Filter.

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#419]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 26, 2018 at 11:49 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/353_

----

This is going to be a show case of "multi-modal" interaction.
Prerequisite: tensor_merge ( #351 )

Note that in addition to the following suggestions, we need additional elements for the visualization.

Suggestion 1.
```
cam1 -- preprocessors -- tensor_converter --+-- tensor_merge -- tensor_filter -- tensor_sink
cam2 -- preprocessors -- tensor_converter --+
```

Suggestion 2.
```
cam1 -- preprocessors -- tensor_converter -- tensor_filter_1 --+-- tensor_merge -- tensor_sink
cam2 -- preprocessors -- tensor_converter -- tensor_filter_2 --+
```

Suggestion 3.
```
cam1 -- preprocessors -- tensor_converter ----- tensor_filter_1 --+-- tensor_merge -- tensor_sink_1
cam2 -- preprocessors -- tensor_converter --+-- tensor_filter_2 --+
                                            +-- tensor_filter_3 -- tensor_sink_2
```

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 11:49 GMT_

----

:octocat: **cibot**: Thank you for posting issue #353. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/jy1210-jung"><img src="https://github.sec.samsung.net/avatars/u/945?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jy1210-jung](https://github.sec.samsung.net/jy1210-jung)**
_Thursday Jul 26, 2018 at 12:11 GMT_

----

to add two cams in pipeline,
v4l2src device=/dev/video0  for cam1
v4l2src device=/dev/video1  for cam2

v4l2src property 'device' default value is '/dev/video0'

**Comment by myungjoo** [comment]
Tested with two webcams in a single computer.
