### ISSUE TITLE
[EPIC/NN3] tensor_filter subplugin, Caffe

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#421]
Timeline: 2019.3Q

----

Additional requirement: be ready for models with heavily modified caffe libraries. (how are we going to let models bring their own custmoized libraries?) This is really a hell-hole, but I'm sure we will be required to support such.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 11:52 GMT_

----

:octocat: **cibot**: Thank you for posting issue #355. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Caffe2 Done
