### ISSUE TITLE
[Example] What about example NN models??

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#424]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Thursday Jul 26, 2018 at 12:04 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/358_

----

Find somewhere appropriate to store example NN models (e.g., ./tflite_model/mobilenet_v1_1.0_224_quant.tflite in our WIki)

Later, we will need to let CI system to load such NN models to test the code. (at least with "smoke test")

FOr this tflite file, we may need to specify the URL in the wiki and/or in some script?

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 12:04 GMT_

----

:octocat: **cibot**: Thank you for posting issue #358. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/jy1210-jung"><img src="https://github.sec.samsung.net/avatars/u/945?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jy1210-jung](https://github.sec.samsung.net/jy1210-jung)**
_Thursday Jul 26, 2018 at 12:24 GMT_

----

Can we upload tflite model into 'nnstreamer_example/example_filter/tflite_model'?

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Friday Jul 27, 2018 at 01:32 GMT_

----

> Can we upload tflite model into 'nnstreamer_example/example_filter/tflite_model'?

Temporarily, YES.

In long term, NO. What about moving all of such to https://github.com/nnsuite/testcases if they are external open sources. (not developed by us)

Then, we can add packaging info to testcases.git (packaging/*.spec and debian/*), let the build system create .rpm and .deb, and then, let nnstreamer.git to "depend" on such pacakges.

CC: @hello-ahn #357

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/jy1210-jung"><img src="https://github.sec.samsung.net/avatars/u/945?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jy1210-jung](https://github.sec.samsung.net/jy1210-jung)**
_Tuesday Aug 21, 2018 at 09:20 GMT_

----

uploaded tflite model and label files
(https://github.com/nnsuite/testcases/tree/master/DeepLearningModels/tensorflow-lite/Mobilenet_1.0_224_quant)

**Comment by helloahn** [comment]
We will upload the models at [HERE](https://github.com/nnsuite/testcases)
