### ISSUE TITLE
[Tensorfilter] Need NN Model to test other/tensors

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#432]
<a href="https://github.sec.samsung.net/jijoong-moon"><img src="https://github.sec.samsung.net/avatars/u/19415?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jijoong-moon](https://github.sec.samsung.net/jijoong-moon)**
_Monday Jul 30, 2018 at 10:04 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/366_

----

# Issue Description
May need Fast RCNN Model for object detection. The output of this RCNN is other/tensors.
- Input : input image
- Output : detection_boxes, detection_scores, detection_classes, num_detections 

However, it is somewhat difficult to find pre-translated tflite model. According to the tflite manual, we could use toco to translate flatbuffer. It is worth to try. ( It is much better if we could find the proper tflite model from internet.)

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Monday Jul 30, 2018 at 10:04 GMT_

----

:octocat: **cibot**: Thank you for posting issue #366. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/jijoong-moon"><img src="https://github.sec.samsung.net/avatars/u/19415?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jijoong-moon](https://github.sec.samsung.net/jijoong-moon)**
_Monday Jul 30, 2018 at 11:02 GMT_

----

I can build toco successfully on Ubuntu 16.04 with command below:

```bash
$ ./bazel-0.15.2-install-linux-x86_64.sh # install bazel > 0.15
$ bazel build tensorflow/contrib/lite/toco:toco
$ ./bazel-bin/tensorflow/contrib/lite/toco/toco --input_file=./data/frozen_inference_graph.pb --output_file=./data/frozen_inference_graph.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_type=QUANTIZED_UINT8 --input_shape="1,640,480,3" --input_array='image_tensor' --output_array='detection_boxes','detection_scores','num_detections','detection_classes' --std_value=127.5 --mean_value=127.5
```
But still there is some error. Need to do more.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/hello-ahn"><img src="https://github.sec.samsung.net/avatars/u/284?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hello-ahn](https://github.sec.samsung.net/hello-ahn)**
_Tuesday Jul 31, 2018 at 02:04 GMT_

----

Actually, there is a model guide for object detection.
Though I got the result of the model, it doesn't work properly.
Below document can help you
[Running on mobile with TensorFlow Lite](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md)

**Comment by jijoongmoon** [comment]
We have it. Closed.
