### ISSUE TITLE
[other/tensors] What does "rank" mean in other/tensors?

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#435]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Monday Jul 30, 2018 at 11:03 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/369_

----

What does "rank" mean in other/tensors?

Unlike other/tensor, we have multiple tensors in other/tensors.
How "rank" is defined in other/tensors?

If this means the RANK LIMIT, please document so in the code where other/tensors is defined (tensor_common.h)

ps. The range of num_tensors is [1, 16], not [1, 65535]. Right?

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Monday Jul 30, 2018 at 11:03 GMT_

----

:octocat: **cibot**: Thank you for posting issue #369. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/jijoong-moon"><img src="https://github.sec.samsung.net/avatars/u/19415?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jijoong-moon](https://github.sec.samsung.net/jijoong-moon)**
_Monday Jul 30, 2018 at 23:20 GMT_

----

Yes, you are right. rank means RANK LIMIT. and it is also right about num_tensors. Currently maximum number of tensor in tensors is 16. I will document about them. May be also need checking routine in the code.

**Comment by myungjoo** [comment]
We may need to remove "RANK" from all PADCAPs.

**Comment by myungjoo** [comment]
We no longer have RANK. Closing this.
