### ISSUE TITLE
[decoder] More decoder functions

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#436]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Tuesday Jul 31, 2018 at 00:36 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/370_

----

Support many popular NN models with decoder.

- image recognition (labeling) (The first & basic feature.)
- bounding boxes ==> Need higher priority ( #567 )
- bounding boxes + image recognition (labeling) ==> Need higher priority ( #567 )
- segmentation
- ...

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jul 31, 2018 at 00:36 GMT_

----

:octocat: **cibot**: Thank you for posting issue #370. The person in charge will reply soon.

**Comment by myungjoo** [comment]
This is going to be critical soon!

**Comment by myungjoo** [comment]
No more pending subfeatures after bounding box. We will move on to other tasks.
