### ISSUE TITLE
Tizen tensorflow prerelease

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#442]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Tuesday Jul 31, 2018 at 06:13 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/376_

----

https://download.tizen.org/live/home:/prerelease:/Tizen:/Unified:/submit:/tizen:/20180729.232051/standard/x86_64/

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jul 31, 2018 at 06:13 GMT_

----

:octocat: **cibot**: Thank you for posting issue #376. The person in charge will reply soon.

**Comment by again4you** [comment]
From now, `tensorflow-dev`, `tensorflow-lite-dev` & nnstreamer packages for Ubuntu 16.04 are start to release.

### Release Infra
* source code: platform/upstream/tensorflow from tizen.org
* launchpad team: [nnstreamer team](https://launchpad.net/~nnstreamer)
* released package
  * tensorflow-dev
  * tensorflow-lite-dev
  * nnstreamer
  * nnstreamer-dev

### How to add the ppa & install packages
```bash
$ sudo add-apt-repository ppa:nnstreamer/ppa
$ sudo apt-get update
$ sudo apt-get install tensorflow-dev tensorflow-lite-dev -y
```

**Comment by myungjoo** [comment]
Please add Ubuntu guide in wiki, https://github.com/nnsuite/nnstreamer/wiki/how-to-build-install-use then close this. Thank you!

**Comment by again4you** [comment]
I wrote the [PPA for nnstreamer & its related modules](https://github.com/nnsuite/nnstreamer/wiki/PPA-for-nnstreamer-&-its-related-modules) wiki page. If you are satisfied with this page, then please close this issue. Thanks in advance.
