### ISSUE TITLE
[WIP] [Load] Add common internal functions

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#444]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Tuesday Jul 31, 2018 at 10:54 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/pull/378_

----

   
Add common internal functions for tensor_load filter.
It appears that these can be shared with tensor_save later as well.
    
This prepares #322
    
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [X]Skipped

----

_**[myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)** included the following code: https://github.sec.samsung.net/STAR/nnstreamer/pull/378/commits_

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jul 31, 2018 at 10:54 GMT_

----

:memo: Version: 1.20180719. Thank you for submitting PR #378. Your PR must pass all verificiation processes of cibot before starting a review process from reviewers. If you are new member to join this project, please read manuals in documentation folder and wiki page. In order to monitor a progress status of your PR in more detail, visit http://aaci.mooo.com/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jul 31, 2018 at 10:55 GMT_

----

:octocat: **cibot**: @myungjoo-ham, **include/tensor_common.h** does not include doxygen tags such as @file @brief @author @bug. You must include the doxygen tags in the source code at least.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jul 31, 2018 at 10:55 GMT_

----

:octocat: **cibot**: @myungjoo-ham, You wrote code with incorrect doxygen statements. Please check a doxygen rule at http://github.sec.samsung.net/STAR/TAOS-CI/blob/tizen/ci/doc/doxygen-documentation.md

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Jul 31, 2018 at 10:55 GMT_

----

:octocat: **cibot**: @myungjoo-ham, One of the format checkers is failed. If you want to get a hint to fix this issue, please go to https://github.sec.samsung.net/STAR/nnstreamer/wiki/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Tuesday Aug 07, 2018 at 12:03 GMT_

----

HOLD THIS PR.
I had totally incorrect understandings on how to design tensor_load.

**Comment by myungjoo** [comment]
Duplicated #388 (Uh.. this is a PR..??)
