### ISSUE TITLE
Use "filter" of transform_caps callbacks

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#446]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Wednesday Aug 01, 2018 at 00:21 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/380_

----

Many plugins ignore "filter" parameter of transform_caps callback.
We should not ignore this.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 01, 2018 at 00:21 GMT_

----

:octocat: **cibot**: Thank you for posting issue #380. The person in charge will reply soon.

**Comment by myungjoo** [comment]
Resolved long ago.
