### ISSUE TITLE
[Filter/Main] Rethink "negotiation"

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#447]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Wednesday Aug 01, 2018 at 00:45 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/381_

----

The code related with caps negotiation still has obsolete concepts.
The usage of input/outputCapNegotiated should be corrected.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 01, 2018 at 00:45 GMT_

----

:octocat: **cibot**: Thank you for posting issue #381. The person in charge will reply soon.

**Comment by myungjoo** [comment]
This has been refactored a few weeks ago.
