### ISSUE TITLE
[Load][Design Bug] Redesign required. Cannot use transform

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#448]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Wednesday Aug 01, 2018 at 00:54 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/382_

----

This is a decoder plugin. This cannot inherit transform class; we cannot get srcpadcaps from sinkpadcaps. We need to read the frame contents to identify srcpadcaps.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 01, 2018 at 00:54 GMT_

----

:octocat: **cibot**: Thank you for posting issue #382. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Wednesday Aug 01, 2018 at 00:56 GMT_

----

Postponing load/save plugins.
1. They are not urgent feature.
2. We need to get to know how to write plugins from element class, not from other GST plugin base classes.

**Comment by myungjoo** [comment]
Any inputs or advices for BaseElement with unknown PADCAP at pipeline setup is welcomed!

**Comment by myungjoo** [comment]
Will be handled with subissues of #388, implemented from the scratch again.
