### ISSUE TITLE
[AWS Migration] Need external VM instance (e.g., AWS, Azure, GCP) for opensource project

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#455]
<a href="https://github.sec.samsung.net/geunsik-lim"><img src="https://github.sec.samsung.net/avatars/u/8170?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [geunsik-lim](https://github.sec.samsung.net/geunsik-lim)**
_Tuesday Aug 07, 2018 at 01:56 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/389_

----

We need to prepare a  VM instance to run CI service for NNstreamer (http://github.com/nnsuite/nnstreamer).

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Aug 07, 2018 at 01:56 GMT_

----

:octocat: **cibot**: Thank you for posting issue #389. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/geunsik-lim"><img src="https://github.sec.samsung.net/avatars/u/8170?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geunsik-lim](https://github.sec.samsung.net/geunsik-lim)**
_Tuesday Aug 07, 2018 at 02:02 GMT_

----

### 예산 확보 히스토리
0. 동작제어랩내의 과제명 및 과제코드: 
   - 동작제어 Lab :  부서코드 : C10A8115 / AEC   
   - 과제명: "Rocky"   개발과제코드 : RAV0117ZZ-82RF-N-1  
   - 과제명: "STAR AI Core Platform"  개발과제코드 : RAJ0118ZZ-CBRF
   - 과제명: "NN 가속화 솔루션" 개발과제코드: RAJ0118ZZ-51RF

1. Tizen 2019 과제: 
   - 실행계획 수립년월일 (2018/03, 확정후), 경영계획명: Tizen 2019 개발환경, 실행계획명: Tizen 2019 개발환경, 지역: 국내, 과제담당자: 이성재님, 경영계획금액/경영실행계획금액: 36,000,000원, 경영계획ID: SH17647953 ,실행계획ID: EP10024467, 사업부: Samsung Research
2. NNAS 과제: Tizen .NET에서 수립했던 비용 일부를 NNAS로 할당해놓음. 
   - PLM상 NNAS 과제명은  'NN 가속화 솔루션', 과제 코드는 'RAJ0118ZZ-51RF' . 

### 예산 활용 계획
1. 당초: MS Azure 으로 예산 수립
2. 변경: AWS + GCP (실행사례가 없으므로 GCP는 취소) 용도로 사용 수립 필요

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/geunsik-lim"><img src="https://github.sec.samsung.net/avatars/u/8170?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geunsik-lim](https://github.sec.samsung.net/geunsik-lim)**
_Tuesday Aug 07, 2018 at 02:03 GMT_

----

*  참조 자료: 
   * 예산 관련담당: 지원그룹 한승준님 신민규님 
![image](https://github.sec.samsung.net/storage/user/8170/files/6a457a34-9a31-11e8-9f69-67d727c30820)

![image](https://github.sec.samsung.net/storage/user/8170/files/738b6766-9a31-11e8-910d-bd5112bb3080)

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/geunsik-lim"><img src="https://github.sec.samsung.net/avatars/u/8170?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geunsik-lim](https://github.sec.samsung.net/geunsik-lim)**
_Tuesday Aug 07, 2018 at 10:11 GMT_

----

From, 김민정님, 

AWS 신규 사용을 위해서는 하기 절차대로 진행하시면 됩니다. 

1. IRP사전 검토 (http://itrm.sec.samsung.net > 과제관리 > 사전검토 요청 
2. 사전 검토 완료되면 결과 첨부하여 메모결재 진행 (비용에 따라 전결규정 확인하여 상신하시면 됩니다.)
3. 메모결재본 첨부하여 IRP비용 품의 진행 (전결은 기진행 했으므로, 개발혁신G 송인규 부장 합의)

IRP 비용품의까지 완료 되면, AWS에서 계정 생성하신 후 저에게 계정 정보 알려주시면 SR 통합계정으로 추가 됩니다.  (반드시 저와 SR 통합 계정에 추가되었는지 확인 하신 후 사용하셔야 비용처리가 가능합니다)

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/geunsik-lim"><img src="https://github.sec.samsung.net/avatars/u/8170?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geunsik-lim](https://github.sec.samsung.net/geunsik-lim)**
_Monday Aug 20, 2018 at 23:33 GMT_

----

Sender : 정현철 <steve.chung@samsung.com> 수석보/CMS운영그룹(CMS사업)/삼성SDS

Date : 2018-08-08 08:28 (GMT+9)
Title : IRP 과제 문의드립니다. (과제코드: 18S0946)
* 수신: 이성재 프로(SR)
* 참조: 김민정 프로(SR)
 
 

  | 과제명 | nnsuite code review 자동 시스템용 VM instance 구축 | 센싱코드 | 18S0946
-- | -- | -- | -- | --






안녕하세요. 이성재 프로님.정보전략그룹 정현철 수석보 입니다. IRP 과제 등록하신 'nnsuite code review 자동 시스템용 VM instance 구축' (18S0946)건  관련해서 잠시 문의 드리고자합니다. 

1. AWS 사용 금액 스펙 확인요청
   . m4.4xlarge (16-core + 64GB RAM + EBS) instance 5개로 우선 운영을 시작하여 load에 따라 추가 예정. (by 이성재님)
2. 해당 AWS 사용시 전사 DC율(25%) 적용여부 확인
   . 산정된 금액에는 할인 적용은 감안하지 않았으나, 사용 확정되면, SR 계정에 포함하여 EDP 할인 25% 적용 예정입니다. (by 김민정님)

**Comment by myungjoo** [comment]
Closing as this is something adminitrative. Migrated to internal issue repo.
