### ISSUE TITLE
[Benchmark] Performance Comparison of NNStreamer vs ROS

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#460]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Wednesday Aug 08, 2018 at 07:48 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/394_

----

This is to brag potential performance advantages of NNStreamer.

CASE 1
---

The two implementations to be compared:

NNStreamer:
```
[USB-CAM 1920x1080 or higher] --> [Video Scaler (videoconverter) 640x480 or lower] --> [tf_lite model, "A"] --> [tensor_sink] --> [APP print out]
```
ROS:
```
[USB-CAM 1920x1080 or higher] --> [Video Scaler (not sure if this needs to be a node) 640x480 or lower] --> [tf_lite model, "A"] --> [APP print out]
```

```[APP Print out]``` can be replaced by ```tee``` + ```tensor_dec``` (if ```tensor_dec``` is ready for bounding-boxes or text-overlay) + ```video_mixer``` + ```video_sink```, which is much better!!!

It is highly recommended to use useful, but lightweight NN model. (e.g., MTCNN or MobileNet).

We may need to find a way to emphasize the performance effect, 

CASE 2
---

With this case, we have "linear NN model", Nx, whose input and output tensor size is huge (e.g., 1920x1080x3) while it has almost no real processing in it (extremely light model. probably output == input). For proper comparison, we may need to add artifical load in it (to simulate an optimized lightweight model)

The proposed execution is:
```
[USE_CAM] --> [Nx 1] --> [Nx 2] --> [Nx 3] --> [tf_lite mode, "A" (real useful)] --> [tensor_sink]
```
For demonstration purpose we may add video_mixer and text/box overlay.

Performance Measurements
---

Execution Scenario A:
- Run as fast as possible in a system. Get the average FPS.
- Note that this could be misleading if USB-CAM overshoots frames and the stream / node configuration is not well implemented.

Execution Scenario B: (This is required as well!!!)
- Run at a slower fixed rate (e.g., 1 per 10 second). Count the number of memory transactions with PMU
- For this we need someone who's familiar with PMU/Perf/... (At least one of @wook16-song @sangjung-woo @geunsik-lim is familiar with this.)

Ease of App Implementation
---

Write concise test app code. Make it as short as possible but readable.
Write a single-line bash command as well. (as an extreme comparison case)

Other Things to Consider
---

Performance profiling (execution time, cpu time, memory transactions) of ROS nodes might be troublesome or tricky. You need to count ALL relevant processes. For NNStreamer/Gstreamer, you don't need to worry this as it's a single process program.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 08, 2018 at 07:48 GMT_

----

:octocat: **cibot**: Thank you for posting issue #394. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/wook16-song"><img src="https://github.sec.samsung.net/avatars/u/40506?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wook16-song](https://github.sec.samsung.net/wook16-song)**
_Monday Aug 27, 2018 at 06:53 GMT_

----

Before pushing the example app for Case 1 (nnstreamer) of this issue, I just leaved a comment to share the result on the experimental environments of the pipelines:
1) [USB-CAM 1920x1080, 24/1 framerates] --> [Video Scaler 224x224+ Video Converter RGB] --> [tf_lite model, "MOBINET"] --> [tensor_sink] --> [APP print out]
Avg. FPS = 3.968254 (processed: 1, elapsed time (ms): 252), Cur. FPS = 3.968254
Avg. FPS = 3.683241 (processed: 2, elapsed time (ms): 543), Cur. FPS = 3.436426
Avg. FPS = 3.717472 (processed: 3, elapsed time (ms): 807), Cur. FPS = 3.802281
Avg. FPS = 3.734827 (processed: 4, elapsed time (ms): 1071), Cur. FPS = 3.787879
Avg. FPS = 3.723008 (processed: 5, elapsed time (ms): 1343), Cur. FPS = 3.690037
Avg. FPS = 3.710575 (processed: 6, elapsed time (ms): 1617), Cur. FPS = 3.649635
Avg. FPS = 3.674541 (processed: 7, elapsed time (ms): 1905), Cur. FPS = 3.484321
Avg. FPS = 3.663004 (processed: 8, elapsed time (ms): 2184), Cur. FPS = 3.597122
Avg. FPS = 3.668977 (processed: 9, elapsed time (ms): 2453), Cur. FPS = 3.717472
Avg. FPS = 3.671072 (processed: 10, elapsed time (ms): 2724), Cur. FPS = 3.703704
Avg. FPS = 3.683858 (processed: 11, elapsed time (ms): 2986), Cur. FPS = 3.816794
Avg. FPS = 3.687769 (processed: 12, elapsed time (ms): 3254), Cur. FPS = 3.731343
Avg. FPS = 3.698435 (processed: 13, elapsed time (ms): 3515), Cur. FPS = 3.846154
Avg. FPS = 3.708609 (processed: 14, elapsed time (ms): 3775), Cur. FPS = 3.846154
Avg. FPS = 3.710116 (processed: 15, elapsed time (ms): 4043), Cur. FPS = 3.731343
Avg. FPS = 3.717472 (processed: 16, elapsed time (ms): 4304), Cur. FPS = 3.846154
Avg. FPS = 3.723987 (processed: 17, elapsed time (ms): 4565), Cur. FPS = 3.846154
Avg. FPS = 3.722854 (processed: 18, elapsed time (ms): 4835), Cur. FPS = 3.717472
Avg. FPS = 3.728414 (processed: 19, elapsed time (ms): 5096), Cur. FPS = 3.831418
Avg. FPS = 3.727171 (processed: 20, elapsed time (ms): 5366), Cur. FPS = 3.717472
Avg. FPS = 3.727370 (processed: 21, elapsed time (ms): 5634), Cur. FPS = 3.745318
Avg. FPS = 3.731343 (processed: 22, elapsed time (ms): 5896), Cur. FPS = 3.816794

2) [USB-CAM 1920x1080, 5/1 framerates] --> [Video Scaler 224x224+ Video Converter RGB] --> [tf_lite model, "MOBINET"] --> [tensor_sink] --> [APP print out]
Avg. FPS = 3.984064 (processed: 1, elapsed time (ms): 251), Cur. FPS = 3.984064
Avg. FPS = 3.367003 (processed: 2, elapsed time (ms): 594), Cur. FPS = 2.923977
Avg. FPS = 2.988048 (processed: 3, elapsed time (ms): 1004), Cur. FPS = 2.439024
Avg. FPS = 2.816901 (processed: 4, elapsed time (ms): 1420), Cur. FPS = 2.403846
Avg. FPS = 2.779322 (processed: 5, elapsed time (ms): 1799), Cur. FPS = 2.638522
Avg. FPS = 2.684564 (processed: 6, elapsed time (ms): 2235), Cur. FPS = 2.298851
Avg. FPS = 2.694380 (processed: 7, elapsed time (ms): 2598), Cur. FPS = 2.754821
Avg. FPS = 2.667556 (processed: 8, elapsed time (ms): 2999), Cur. FPS = 2.493766
Avg. FPS = 2.627737 (processed: 9, elapsed time (ms): 3425), Cur. FPS = 2.352941
Avg. FPS = 2.630887 (processed: 10, elapsed time (ms): 3801), Cur. FPS = 2.666667
Avg. FPS = 2.619671 (processed: 11, elapsed time (ms): 4199), Cur. FPS = 2.512563
Avg. FPS = 2.599090 (processed: 12, elapsed time (ms): 4617), Cur. FPS = 2.392344
Avg. FPS = 2.603124 (processed: 13, elapsed time (ms): 4994), Cur. FPS = 2.659574
Avg. FPS = 2.584456 (processed: 14, elapsed time (ms): 5417), Cur. FPS = 2.364066
Avg. FPS = 2.587992 (processed: 15, elapsed time (ms): 5796), Cur. FPS = 2.638522
Avg. FPS = 2.573589 (processed: 16, elapsed time (ms): 6217), Cur. FPS = 2.380952
Avg. FPS = 2.577710 (processed: 17, elapsed time (ms): 6595), Cur. FPS = 2.652520
Avg. FPS = 2.564833 (processed: 18, elapsed time (ms): 7018), Cur. FPS = 2.369668
Avg. FPS = 2.570346 (processed: 19, elapsed time (ms): 7392), Cur. FPS = 2.673797
Avg. FPS = 2.561475 (processed: 20, elapsed time (ms): 7808), Cur. FPS = 2.403846
Avg. FPS = 2.554745 (processed: 21, elapsed time (ms): 8220), Cur. FPS = 2.433090
Avg. FPS = 2.559628 (processed: 22, elapsed time (ms): 8595), Cur. FPS = 2.673797
Avg. FPS = 2.550455 (processed: 23, elapsed time (ms): 9018), Cur. FPS = 2.364066
Avg. FPS = 2.548312 (processed: 24, elapsed time (ms): 9418), Cur. FPS = 2.506266
Avg. FPS = 2.546603 (processed: 25, elapsed time (ms): 9817), Cur. FPS = 2.506266
Avg. FPS = 2.550020 (processed: 26, elapsed time (ms): 10196), Cur. FPS = 2.638522
Avg. FPS = 2.543091 (processed: 27, elapsed time (ms): 10617), Cur. FPS = 2.380952
Avg. FPS = 2.546149 (processed: 28, elapsed time (ms): 10997), Cur. FPS = 2.638522
Avg. FPS = 2.540072 (processed: 29, elapsed time (ms): 11417), Cur. FPS = 2.380952

**Comment by wooksong** [comment]
For the ROS application of Case 1, a [PR](https://github.sec.samsung.net/wook16-song/ros_kinetic_usb-cam-to-tflite/pull/1) was submitted to https://github.sec.samsung.net/wook16-song/ros_kinetic_usb-cam-to-tflite. Based on this application, several scenarios to show performance effect of NNStreamer will be added.

**Comment by wooksong** [comment]
The ROS application for Case 1 is updated. https://github.sec.samsung.net/wook16-song/ros_kinetic_video-benchmark-with-tflite/pull/2

**Comment by wooksong** [comment]
## Performance comparisons of simple mobinet with TensorFlow Lite applications (NNStreamer vs. ROS)

#### 1. Application descriptions

- NNStreamer 
```
v4l2src [USB-CAM 1920x1080] -- videoconvert -- tee (optional) -- queue -- textoverlay -- fpsdisplaysink
                                                |                                                
                                                -- queue -- videoscale [224x224] -- videoconvert [RGB]-- tensor_converter -- tensor_filter [Mobinet w/ TF Lite] -- tensor_sink -> [APP Print Out]
```
- ROS
```
usb_cam_node [USB-CAM 1920x1080] (pub) -------- /usb_cam/image_raw ----------------------> (sub) viewer_node (optional)
                                   |                                                         ^
                                   |                                                         |
                                   |                                                         |
                                   |                                                       (pub) /tflite_mobinet_node_handle/mobinet_result                                                           
                                   |                                                         | 
                                 (pub) -------- /usb_cam/image_raw --------> (sub) tflite_mobinet_node
```
#### 2-1. Performance measurements: CPU time during 10 mintures of running Mobinet (w/o fpsdisplaysink or viewer_node)

TBD

**Comment by wooksong** [comment]
[The above comment](https://github.com/nnsuite/nnstreamer/issues/460#issuecomment-422255001) is copied to the wiki page: https://github.com/nnsuite/nnstreamer/wiki/Performance-comparisons-of-simple-mobinet-with-TensorFlow-Lite-applications-(NNStreamer-vs.-ROS).  I closed this issue and would open a new one up (or reopen this issue) when it is required to be updated.
