### ISSUE TITLE
[Filter] change parameter to meta structure

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#467]
<a href="https://github.sec.samsung.net/hello-ahn"><img src="https://github.sec.samsung.net/avatars/u/284?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hello-ahn](https://github.sec.samsung.net/hello-ahn)**
_Wednesday Aug 22, 2018 at 01:48 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/pull/401_

----

change the parameter of `getInputDimension` and `getOutputDimension` from tensor_dim, type to META structure including each dim array and type array.

**Self evaluation:**
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped

Signed-off-by: HyoungjooAhn <hello.ahn@samsung.com>

----

_**[hello-ahn](https://github.sec.samsung.net/hello-ahn)** included the following code: https://github.sec.samsung.net/STAR/nnstreamer/pull/401/commits_

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 22, 2018 at 01:48 GMT_

----

:memo: Version: 1.20180719. Thank you for submitting PR #401. Your PR must pass all verificiation processes of cibot before starting a review process from reviewers. If you are new member to join this project, please read manuals in documentation folder and wiki page. In order to monitor a progress status of your PR in more detail, visit http://aaci.mooo.com/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 22, 2018 at 01:48 GMT_

----

:octocat: **cibot**: @hello-ahn, **nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c** does not include doxygen tags such as @file @brief @author @bug. You must include the doxygen tags in the source code at least.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 22, 2018 at 01:49 GMT_

----

:octocat: **cibot**: @hello-ahn, You wrote code with incorrect doxygen statements. Please check a doxygen rule at http://github.sec.samsung.net/STAR/TAOS-CI/blob/tizen/ci/doc/doxygen-documentation.md

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 22, 2018 at 01:49 GMT_

----

:octocat: **cibot**: @hello-ahn, One of the format checkers is failed. If you want to get a hint to fix this issue, please go to https://github.sec.samsung.net/STAR/nnstreamer/wiki/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 22, 2018 at 01:52 GMT_

----

:octocat: **cibot**: @hello-ahn, **nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c** does not include doxygen tags such as @file @brief @author @bug. You must include the doxygen tags in the source code at least.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 22, 2018 at 01:52 GMT_

----

:octocat: **cibot**: @hello-ahn, You wrote code with incorrect doxygen statements. Please check a doxygen rule at http://github.sec.samsung.net/STAR/TAOS-CI/blob/tizen/ci/doc/doxygen-documentation.md

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 22, 2018 at 01:52 GMT_

----

:octocat: **cibot**: @hello-ahn, One of the format checkers is failed. If you want to get a hint to fix this issue, please go to https://github.sec.samsung.net/STAR/nnstreamer/wiki/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Wednesday Aug 22, 2018 at 07:37 GMT_

----

:octocat: **cibot**: @hello-ahn, Oooops. A Ubuntu builder checker could not be completed. To get a hint, please go to http://aaci.mooo.com/nnstreamer/ci/repo-workers/pr-audit/201808221624020.38536405563354-401-bca4312d4c24f1de9c546d2a042a5395dace529b/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Aug 23, 2018 at 01:41 GMT_

----

:octocat: **cibot**: @hello-ahn, One of the format checkers is failed. If you want to get a hint to fix this issue, please go to https://github.sec.samsung.net/STAR/nnstreamer/wiki/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Aug 23, 2018 at 01:53 GMT_

----

:octocat: **cibot**: @hello-ahn, Oooops. A Ubuntu builder checker could not be completed. To get a hint, please go to http://aaci.mooo.com/nnstreamer/ci/repo-workers/pr-audit/201808231042040.32208204269409-401-5bc58df03b0822cc6a730baa057c230e98172136/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Aug 23, 2018 at 02:07 GMT_

----

:octocat: **cibot**: @hello-ahn, Oooops. A Ubuntu builder checker could not be completed. To get a hint, please go to http://aaci.mooo.com/nnstreamer/ci/repo-workers/pr-audit/201808231056080.014482975006104-401-651ebcda2268a1179c3e6adf8677c07fd10f2ee1/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Aug 23, 2018 at 02:29 GMT_

----

:octocat: **cibot**: @hello-ahn, Oooops. A Ubuntu builder checker could not be completed. To get a hint, please go to http://aaci.mooo.com/nnstreamer/ci/repo-workers/pr-audit/201808231118240.82147598266602-401-18e230548b84f5ad87640741e9c89e39a04e13f0/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Aug 23, 2018 at 02:49 GMT_

----

:octocat: **cibot**: @hello-ahn, Oooops. A Ubuntu builder checker could not be completed. To get a hint, please go to http://aaci.mooo.com/nnstreamer/ci/repo-workers/pr-audit/201808231137510.51353311538696-401-eacc5ebdea0f125c263ff2a70a5910a154077ed4/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Aug 23, 2018 at 04:30 GMT_

----

:octocat: **cibot**: @hello-ahn, Oooops. A Ubuntu builder checker could not be completed. To get a hint, please go to http://aaci.mooo.com/nnstreamer/ci/repo-workers/pr-audit/201808231318570.41724896430969-401-c7bf5945c63576eee1ed68f5a82db197ce6519fd/.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Monday Aug 27, 2018 at 05:00 GMT_

----

Remove duplicated part ( #400 )

**Comment by myungjoo** [comment]
Change setInputDimension() as well. This has the same purpose with getInput/OutputDimension.

**Comment by helloahn** [comment]
It was a PR :)
