### ISSUE TITLE
[Pipeviz UI tool] Need to make new element to set pipeline of nnstremer

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#472]
<a href="https://github.sec.samsung.net/jinhyuck83-park"><img src="https://github.sec.samsung.net/avatars/u/16767?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jinhyuck83-park](https://github.sec.samsung.net/jinhyuck83-park)**
_Monday Aug 27, 2018 at 01:41 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/406_

----

---
name: Need make new element to set pipeline of nnstremer
about: when I try to make pipeline and run nnstreamer example like nnstreamer filter example, there is some problem in pipeviz app.
unlike nnstreamer example app, pipeviz does not have external application that gets tensor result from tensor sink and lead to textoverlay text sink, so I think pipeviz need another new element that works as external application does

---

# Issue Description

![image](https://user-images.githubusercontent.com/1109011/44968137-fbcd2380-af80-11e8-88c0-e1bf66cb5fd7.png)

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Monday Aug 27, 2018 at 01:41 GMT_

----

:octocat: **cibot**: Thank you for posting issue #406. The person in charge will reply soon.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Monday Aug 27, 2018 at 05:13 GMT_

----

Please note that the pipeline with tensor_sink + application + textoverlay is a workaround. We should use "tensor_dec" instead of tensor_sink+application+textoverlay.

So.. with more advanced tensor_dec:

It would be
```
tensor_filter->tensor_dec option=... -+>videomixer-->videosink
                              ...   ->textoverlay-->videosink
```
OR
```
tensor_filter->tensor_dec option=... -> txt
                   ...   -> textoverlay name=txt-->videosink
```
Depending on how we can use textoverlay. For such usage, we will need additional properties for tensor_dec as well.

**Comment by myungjoo** [comment]
Note that this "new" element can be implemented by enhancing "tensor_dec" to have more decoding options. Please do not create another element for this.

**Comment by jinhyuck-park** [comment]
we discussed and have conclusion that enhancing "tensor_dec" is reasonable for pipeviz GUI
