### ISSUE TITLE
[TensorSplit] Skeleton to split tensor into multiple tensor

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#473]
<a href="https://github.sec.samsung.net/jijoong-moon"><img src="https://github.sec.samsung.net/avatars/u/19415?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jijoong-moon](https://github.sec.samsung.net/jijoong-moon)**
_Monday Aug 27, 2018 at 02:19 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/pull/407_

----

# PR Description
In order to split tensor to multiple tensor, tensor_split is
required. It take one big tensor as an input and push the multiple
small tensor segment to downstream according to segment option.

This PR includes skeleton of tensor split.

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [ ]Passed [ ]Failed [X]Skipped

Signed-off-by: jijoong.moon <jijoong.moon@samsung.com>

----

_**[jijoong-moon](https://github.sec.samsung.net/jijoong-moon)** included the following code: https://github.sec.samsung.net/STAR/nnstreamer/pull/407/commits_

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Monday Aug 27, 2018 at 02:19 GMT_

----

:memo: Version: 1.20180719. Thank you for submitting PR #407. Your PR must pass all verificiation processes of cibot before starting a review process from reviewers. If you are new member to join this project, please read manuals in documentation folder and wiki page. In order to monitor a progress status of your PR in more detail, visit http://aaci.mooo.com/.

**Comment by myungjoo** [comment]
This is PR. Not an issue.
