### ISSUE TITLE
[Advanced Queueing] Support aggregation

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#474]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Monday Aug 27, 2018 at 05:07 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/408_

----

New Feature or Gstreamer-Usage Required.

For incoming stream, aggregate pre-defined numbers of elements and push the aggregated as a single frame. Support "moving window" concept as well.

For example, with incoming stream with frame 1, 2, 3, ...., the outgoing (to be fed to tensor_filter) stream is
[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8], ...., where [a, b, c, d] is an aggregated frame.

I'm not sure if we need yet another feature in NNStreamer of we can reuse what gstreamer already has.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Monday Aug 27, 2018 at 05:07 GMT_

----

:octocat: **cibot**: Thank you for posting issue #408. The person in charge will reply soon.

**Comment by myungjoo** [comment]
From jaeyun-jung:
> plugin name : tensor_aggregator
>
> properties:
>
>   "frames-out" : the number of frames in out buffer (0 default, with tensor dim in caps)
    "frames-flush" : the number of frames to flush (0 default, flush all output)
    "frames-max" : the max frames in adapter (0 default, unlimited)
