### ISSUE TITLE
[Wait for PR] [TensorSplit] Add Set/Get Properties

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#476]
<a href="https://github.sec.samsung.net/jijoong-moon"><img src="https://github.sec.samsung.net/avatars/u/19415?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jijoong-moon](https://github.sec.samsung.net/jijoong-moon)**
_Tuesday Aug 28, 2018 at 02:58 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/pull/410_

----

# PR Description

In order to get/set tensor split size, TENSORSEG property is added. To
Manupilate set and get properties function is modified.

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [ ]Passed [ ]Failed [X]Skipped

Signed-off-by: jijoong.moon <jijoong.moon@samsung.com>

----

_**[jijoong-moon](https://github.sec.samsung.net/jijoong-moon)** included the following code: https://github.sec.samsung.net/STAR/nnstreamer/pull/410/commits_

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Tuesday Aug 28, 2018 at 02:58 GMT_

----

:memo: Version: 1.20180719. Thank you for submitting PR #410. Your PR must pass all verificiation processes of cibot before starting a review process from reviewers. If you are new member to join this project, please read manuals in documentation folder and wiki page. In order to monitor a progress status of your PR in more detail, visit http://aaci.mooo.com/.

**Comment by myungjoo** [comment]
This is PR.
