### ISSUE TITLE
[Timestamp] Many NNS Plugins do not preserve timestamp.

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#511]
There are many nnstreamer plugins do not preserve timestamp.

1. Survey timestamp policies of "reputable" gstreamer good plugins, which are not source or sink plugins.
2. Decide our own timestamp plocies for "transform"-like plugins
    A. I suppose "The most recent timestamp of sink pads" is proper for the timestamp of src pads for most cases
    B. However, we do not know how to handle timestamp at aggregator where input-frames > 1 and we have overlapping windows or multple frames from a single frame via aggregator. This may happen with 2nd aggregator of Project:NS. Let's assume "the most recent timestamp" is good enough and postpone decision regarding this issue.
3. Apply timestamping policies to ALL tensor_* plugins.

Reported by @jaeyun-jung

**Comment by jaeyun-jung** [comment]
In video mixer, updated with segment.

  if (mix->segment.position == -1)
    output_start_time = mix->segment.start;
  else
    output_start_time = mix->segment.position;


  *outbuf = gst_buffer_new_allocate (NULL, outsize, &params);
  GST_BUFFER_TIMESTAMP (*outbuf) = output_start_time;
  GST_BUFFER_DURATION (*outbuf) = output_end_time - output_start_time;

**Comment by jaeyun-jung** [comment]
In audio aggregator, updated with segment.

  if (agg_segment->rate > 0.0) {
    GST_BUFFER_PTS (outbuf) = agg_segment->position;
    GST_BUFFER_OFFSET (outbuf) = aagg->priv->offset;
    GST_BUFFER_OFFSET_END (outbuf) = next_offset;
    GST_BUFFER_DURATION (outbuf) = next_timestamp - agg_segment->position;

**Comment by myungjoo** [comment]
I guess this is complete.?
