### ISSUE TITLE
[Performance Verification] Tensor_filter memcpy-less-ness verification

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#513]
We need to guarantee that we do not incur memcpy of incoming/outgoing tensors in the following pipeline. However, we do not (and cannot) care memcpy INSIDE the given model or framework. We do care up until the input tensor location of the given model/framework and from the output tensor location of the given model/framework.

```
... ---other/tensor(s)--HERE--> tensor_filter/tf-lite ---other/tensor(s)--HERE--> ...
                                |                   ^
                                |                   |
                               HERE                HERE
                                |                   |
                                V                   |
                                tensorflow-lite I/O interface's buffer (allocated memory)
```

It'd be best if we can add regression test for this. (if there is a memcpy with a text-example tf-lite model, reject the PR)

**Comment by leemgs** [comment]
** common function name style (gst_***_class_init) of nnstreamer elements 

* https://github.com/nnsuite/nnstreamer/blob/master/gst/tensor_decoder/tensordec.c#L418

* gst_tensordec_class_init()

* gst_tensordec_init (GstTensorDec * self)

**Comment by leemgs** [comment]
When we try to check share object dependencies of nnstreamer_example_filter (ELF, dynamically linked), the file does not include shared librarys inthe cotents of the file's dynamic section.

* Screenshot:
```bash
$ ldd ./nnstreamer_example_filter
        linux-vdso.so.1 =>  (0x00007ffe0bb9e000)
        libgstreamer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007f95550d8000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f9554e85000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f9554b74000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f95547aa000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f95545a6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f955429d000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9554095000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9553e91000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9553c74000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f9553a6c000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f95537fc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9555402000)
```

* Analysis:
Basically, The gstreamer media framework launch the gst plug-in libraries of the nnstreamer_example_filter file with dlopen(3). 
```
Execution sequence: (1) nnstreamer_example_filter ---> (2) gstreamer framework ----> (3) dlopen (plug-in.so)
```

**Comment by myungjoo** [comment]
Ok. It appears that it's mostly proven.
