### ISSUE TITLE
[Filter] handling float type at sub-plugin

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#519]
The main data type of `nnstreamer` is `uint8`.
However, there are so many models constructed with `float32`.
Usually, it is converted with `uint8` through below function.
```bash
${FLOAT32} = (${UINT8_VALUE} - 127.5f) / 127.5f;
```

I'm not sure it is usual(or de-facto) method or not.
If it is not, we have to concern how to make it work with `float` data type.

**Comment by myungjoo** [comment]
If we need such operations, we need to IMPLEMENT additional properties to ```tensor_transform`` with type-change mode. For example:
```
... ! tensor_transform mode=typecast option=float32 algorithm=normalize_pn_half
```

**Comment by helloahn** [comment]
@myungjoo you mean, maintain the current policy of `tensor_filter`, which only control `uint8_t`, and convert it at the other elements before `tensor_filter`?

**Comment by myungjoo** [comment]
```tensor_filter``` controls all types. Only the pointer type is uint8_t and that does not mean that the data is uint8_t.

Whether a pointer p is in uint8_t * or double * does not affect when you simply transfer a binary blob.

**Comment by helloahn** [comment]
To handle those data types, in my opinion, the `invoke` methods of each framework should be modified because it only takes `uint8_t` as in/out parameter currently.
It will be updated at next PR.

**Comment by helloahn** [comment]
We will use the current version `tensor_transform` temporarily, update `tensor_transform` later to handle various equation, like regularization, average, min_max, etc.

**Comment by myungjoo** [comment]
> To handle those data types, in my opinion, the invoke methods of each framework should be modified because it only takes uint8_t as in/out parameter currently.

If you are going to add additional function prototypes, you will be adding N x N functions with the exact same behaviors, which is a total waste.

If you are going to change uint8 ptr to void ptr, that is a valid approach although you really need to be careful with size calculations, which is why I stuck with uint8.
