### ISSUE TITLE
[TensorDec] Enhance tensor decoder for support Pipeviz tool

### ISSUE THREAD

**Issue by jinhyuck-park** [nnsuite/nnstreamer#524]
To support pipeviz GUI tool, we need enhance tensor decoder
it will be implemented as below

tensor_filter->tensor_dec option=... -> txt
                   ...   -> textoverlay name=txt-->videosink

---
Added for clarification ( @myungjoo )

This is to implement image labeling.

Input: tensor of the image label.
Output: text/x-raw. string of the corresponding label.
Requires property value: the label file path.

**Comment by myungjoo** [comment]
That looks good. Please proceed with that plan.
