### ISSUE TITLE
[Filter/TF-lite] Memcpy-less tf-lite result output buffering

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#536]
I checked the address of the output tensor from TF-Lite for checking how much can we believe the output data. The result is, it's not guaranteed.

At below log, each `outputTensor` address is equal.

With @jaeyun-jung @myungjoo , we discussed about this problem and we decided to make the flag, `allocate_in_invoke` of tensorflow-lite, FALSE.
In this case, `tensor_filter` will allocate each memory and buffer will manage it.

```bash

outputTensor address: 0x1a4ba88
** Message: receiving new data [3]
...

outputTensor address: 0x1a4ba88
** Message: receiving new data [4]
...

outputTensor address: 0x1a4ba88
** Message: receiving new data [5]
...

```

**Comment by myungjoo** [comment]
Wow.. this is incredible. Then, we definitely need to do something.

Possible approaches:

1. Need to check if tensorflow supports this:
    A. An option/env-var/parameters/... to allocate a new memory chunk for every output and assume that the user is respondible for free-ing the chunk
    B. An option to do some reference-counting on the allocated memory chunk for output.

2. Enforce tensorflow to allocate a new memory chunk externally (external from tensorflow). (memory map??)

3. Modify tensorflow (allowing 1-A) and upstream it

4. Do memcpy on outptr (WORST CASE)

**Comment by helloahn** [comment]
@myungjoo you mean tensorflow-lite rather than tensorflow, right?

**Comment by helloahn** [comment]
I checked it by dividing the pipeline with `tee`.
Below command is used
```bash
gst-launch-1.0 v4l2src name=cam_src ! videoconvert ! video/x-raw,width=640,height=480,format=RGB,framerate=30/1 ! tee name=t_raw t_raw. ! queue ! textoverlay name=tensor_res font-desc="Sans, 24" ! videoconvert ! ximagesink name=img_tensor t_raw. ! queue ! videoscale ! video/x-raw,width=224,height=224 ! tensor_converter ! tee name=t_test t_test. ! queue ! tensor_filter framework="tensorflow-lite" model="tflite_model/mobilenet_v1_1.0_224_quant.tflite" ! tensor_sink name=tensor_sink t_test. ! queue ! tensor_filter framework="tensorflow-lite" model="tflite_model/mobilenet_v1_1.0_224_quant.tflite" ! tensor_sink name=tensor_sink1
```

and the result
```bash

...
outptr address: 0x7f67e0b54040 // tee1
outptr address: 0x7f67e0c7b040 // tee2

outptr address: 0x7f67e0b54040
outptr address: 0x7f67e0c7b040

outptr address: 0x7f67e0b54040
outptr address: 0x7f67e0c7b040
...

```

In my guess, whenever the model is loaded, tfllite secures enough space first, and uses only that space continuously.

**Comment by myungjoo** [comment]
> @myungjoo you mean tensorflow-lite rather than tensorflow, am I right?

They both share the same git source repo. :)


```0x7f67e0c7b040 - 0x7f67e0b54040 = 0x127000``` (1180kiB)
This is not a really big buffer for tensors.

And please check the usage of ```Interpreter::SetTensorParametersReadWrite```, which appears to configure memory allocation policies. It appears that you can even allocate output buffer for TF-lite or take the reponsibilities of freeing output buffers from TF-lite to the caller.

**Comment by helloahn** [comment]
#652 solves this issue temporally with `memcpy`.
Whenever we have the better idea, it will be updated as soon as possible.

**Comment by myungjoo** [comment]
Updated the title as #652 is a workaround with memcpy.

**Comment by helloahn** [comment]
I tried to remove `memcpy` but failed.

I found the flag about the allocation of `TfLiteTensor` and tried to change it like below code.
```bash
  for (int i = 0; i < getOutputTensorSize (); i++) {
    int out_index = interpreter->outputs ()[i];
    TfLiteTensor *output_tensor = interpreter->tensor (out_index);

    g_assert (output_tensor->bytes == output[i].size);

    output_tensor->allocation_type = kTfLiteDynamic;
    output_tensor->data.raw = (char *)output[i].data;

    _print_log("address: %p", output_tensor->data.raw);
  }
```

It looks almost done.
At the end of the stream, however, I met below error.
```bash
...

** Message: Invoke() is finished: 314.994000
** Message: address: 0x7fe7bc3db200
** Message: address: 0x7fe7bca80360
ERROR: from element /GstPipeline:pipeline0/GstXImageSink:img_tensor: Output window was closed
Additional debug info:
ximagesink.c(700): gst_x_image_sink_handle_xevents (): /GstPipeline:pipeline0/GstXImageSink:img_tensor
** Message: Invoke() is finished: 311.928000
*** Error in `nnstreamer_example_object_detection': free(): invalid pointer: 0x00007fe7bc3db200 ***

...
```

The result of this test is because tensorflow executes `free` internally first, `gst` cannot do `free` the memory and generate an error.

If you have any further idea, leave comments please.
