### ISSUE TITLE
[Taos-CI] when indent error occurs, TAOS/pr-format-indent details does not link properly

### ISSUE THREAD

**Issue by jinhyuck-park** [nnsuite/nnstreamer#541]
when indent error occurs, TAOS/pr-format-indent details does not link properly
=> it leads to file diff, but it should lead to /report/indent-format.patch

**Comment by leemgs** [comment]
![image](https://user-images.githubusercontent.com/82404/45660185-82adfe80-bb32-11e8-87dc-54f54e24f914.png)
