### ISSUE TITLE
[TensorDec] Struct variable name is too long.

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#542]
https://github.com/nnsuite/TAOS-CI/issues/256

![err](https://user-images.githubusercontent.com/12094135/45661386-47aec980-bb38-11e8-84f2-6928d4c63bd6.png)

This error comes from long variable name.

Gstreamer suggest indent rule(https://gstreamer.freedesktop.org/documentation/frequently-asked-questions/developing.html#what-is-the-coding-style-for-gstreamer-code)
and we should keep rules.

In the rule, line-length should be less than 80. but this case struct in struct in struct..  so using variable like
``` self->tensordec_mode_image_label.image_labeling_info.labels``` . That mean, it is easy to over line-length 80. 
Thus, we should shorten variable name.

**Comment by jinhyuck-park** [comment]
I will update variable name with regarding this
