### ISSUE TITLE
[Performance Bug] FPS drops when the pipeline using NNStreamer is attached to the normal gstreamer pipeline

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#546]
#### Issue Description ####
The structure of ./nnstreamer_example/example_filter_performance_profile is as follows:
```
v4l2src [USB-CAM 1920x1080/30fps] -- videoconvert -- tee -- queue -- textoverlay -- fpsdisplaysink
                                                      |                                                
                                                      -- queue -- videoscale [224x224] -- videoconvert [RGB]-- tensor_converter -- tensor_filter [Mobinet w/ TF Lite] -- tensor_sink
```
Under this structure, the FPS value measured by fpsdisplaysink drops to about 20. Howerver, when the NNStreamer line is disabled (which means the bottom queue is not linked to the upper tee), the FPS value measured by fpsdisplaysink is 30, same as that of input.

#### How to reproduce ####
- Clone https://github.com/wooksong/nnstreamer/tree/issue-546
- Build
- 1. For the nnline-enabled running, 
```
./nnstreamer_example_filter_performance_profile -c /dev/video0
```
![image](https://user-images.githubusercontent.com/2772376/45674440-1a7a0f80-bb68-11e8-945a-9ba170cacfc3.png)

- 2. For the nnline-disabled running, 
```
./nnstreamer_example_filter_performance_profile -c /dev/video0 --streamline-only
```
![image](https://user-images.githubusercontent.com/2772376/45674335-dedf4580-bb67-11e8-995f-0874ce7bbdbe.png)

**Comment by myungjoo** [comment]
How's the CPU utilization in both cases?

**Comment by wooksong** [comment]
@myungjoo 
1. The case of the nnline-enabled running: about 16%
![nnenabled](https://user-images.githubusercontent.com/2772376/45862900-c44add80-bdae-11e8-8dc4-ed7e7fca693b.png)

2. The case of the nnline-disabled running: about 5%
![nndisabled](https://user-images.githubusercontent.com/2772376/45863370-d3328f80-bdb0-11e8-982a-7853b2bbae67.png)

**Comment by wooksong** [comment]
This issue is detailed in #741.

**Comment by myungjoo** [comment]
Duplicated. Closing this. (Continued on #741)
