### ISSUE TITLE
[Investigate othercaps in tensor_filter] we need further investigation.

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#549]
- [x] Add othercap logging to tensor_filter
- [ ] Find the values of othercap and why. --> Canceled. We do not have cases where it has valid value.
- [ ] Determine how to utilize othercap along with additional test cases / apps.

**Comment by jaeyun-jung** [comment]
[filter_caps_log.txt](https://github.com/nnsuite/nnstreamer/files/2533030/filter_caps_log.txt)

1. single tensor in/out (unittest custom filter)
[ RUN      ] tensor_stream_test.custom_filter_tensor

2. multi tensor in/out (unittest custom filter)
[ RUN      ] tensor_stream_test.custom_filter_tensors

3. single tensor in / multi tensor out (example object detection)
$ nnstreamer_example_object_detection

**Comment by jaeyun-jung** [comment]
call the fixate vmethod in base-transform,

    /* note that we pass the complete array of structures to the fixate
     * function, it needs to truncate itself */
    othercaps =
        klass->fixate_caps (trans, GST_PAD_DIRECTION (pad), caps, othercaps);

**Comment by myungjoo** [comment]
Thanks. PTAL #774
