### ISSUE TITLE
NNStreamer Mini summit: Sep-18-2018 (Photo)

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#550]
* NNStreamer Mini summit: Sep-18-2018 (Photo)
   * https://github.com/nnsuite/nnstreamer/wiki/NNStreamer--Mini-summit

![20180918_200316](https://user-images.githubusercontent.com/82404/45731093-b2333880-bc10-11e8-8994-a5edefe7f1e9.jpg)
![20180918_202538](https://user-images.githubusercontent.com/82404/45731094-b2cbcf00-bc10-11e8-8485-aa2af7adc317.jpg)
![20180918_202551](https://user-images.githubusercontent.com/82404/45731095-b2cbcf00-bc10-11e8-8402-416c4a196ec1.jpg)

**Comment by myungjoo** [comment]
Make it a wiki page, not an issue. You can store photos in wiki as well.

**Comment by leemgs** [comment]
closed becuase the photos are merged to wiki page.
