### ISSUE TITLE
[Filter/tensorflow-lite] AllocateTensors appears to be called too many time.

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#557]
Please check if the following code is correct in tensorflow-lite subplugin:
```
  for (int i = 0; i < getInputTensorSize (); i++) {
    int input = interpreter->inputs ()[i];

    if (interpreter->AllocateTensors () != kTfLiteOk) {
      _print_log ("Failed to allocate tensors");
      return -2;
}
```

It appears that you need to call ```interpreter->AllocateTensors()``` only once for each invoke.
Refer: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/apis.md

**Comment by helloahn** [comment]
it's updated at the new version already :)

https://github.com/nnsuite/nnstreamer/blob/057d0ee0e658ddc4289d1c8656494201d0ebfa0c/gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc#L292-L304
