### ISSUE TITLE
[Decoder] Refactoring / Enhancement Requests (subplugin arch)

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#581]
After #567 is completed and working with a few test cases, we need the following refactoring / enhancement in tensor_decoder.

1. Do not call strcmp0 frequently (every frame)
  - Parse it and store corresponding enum values in the "self" private data structure

2. Write each "mode" as separate .C file, but not separate .so file.
I'd suggest to have following structure:

```tensor_decoder.c/h```
```
struct X {
   gchar *modename;
   int modeID;
   functypeA opA;
   functypeB .opB;
   ...
}
// calls op* in its routines.
enum modeID = {
   ENUM_X = 0,
   ENUM_Y, 
   ...
   ENUM_END,
}
...
struct X * subpluginlist[ENUM_END];
someInitFunc() {
  subpluginlist[ENUM_X] = Ximpl;
  ...
}
```
```tensor_decoder_subpluginX.c```
```
static functypeA X_implementationA() {
...
}
struct X Ximpl = {
  .modename="X";
  .modelID = ENUM_X;
  .opA = X_implementationA;
  ...
};
```

Anyway, please try to do this after image-label and bounding-boxes are completed.

**Comment by jinhyuck-park** [comment]
OK as soon as image-label and bounding-boxes are completed 
I will work with this way

**Comment by myungjoo** [comment]
Done.
