### ISSUE TITLE
Behaviour for typecasting float types to unsigned integer types is different between arm and x86_64

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#618]
Since the result of the test case for testing the typecast operation of "uint8 -> int8 -> float32 -> float64 -> uint8" on the armv7l architecture is different from the result on the x86_64 architecture, the TAOS/pr-audit-build-tizen-armv7l check for PR #612 is failed.

In the case of x86_64, 
-1.000000 of float64 is successfully converted to unsigned integer 255 as we intended:
uint8:255 -> int8:-1 -> float32:-1.000000 -> float64:-1.000000 -> **uint8:255**

In the case of armv7l,
**255 becomes 0** after all the typecasting:
uint8:255 -> int8:-1 -> float32:-1.000000 -> float64:-1.000000 -> **uint8:0**

IMO, we need to discuss about this behaviour difference.

In order to typecast from float to unsigned integer, it is OK on both armv7l and x86_64 with using signed integer as an intermediate type. For example, in PR #612, testcase 8, uint8 -> int8 -> float32 -> float64 -> int64 -> uint8, succeeds on both armv7l and x86_64.

**Comment by myungjoo** [comment]
Requirement: same results for all archs.
