### ISSUE TITLE
[RunTest] run a camera  test of the apptest module

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#625]
We have to enable a camera test (with [v4l2loopback.ko](https://github.com/umlaeute/v4l2loopback)) into the existing apptest module of the NNStreamer repository when a PR happens. This  job is a next activity of  the issue https://github.com/nnsuite/nnstreamer/issues/531 (Resolved).

* Problem: Why can not we load  a signed kernel module with 'insmod' command? 

* Related Plug-in: pr-nnstreamer-ubuntu-apptest.sh
https://github.com/nnsuite/TAOS-CI/blob/master/ci/taos/plugins-staging/pr-nnstreamer-ubuntu-apptest.sh

* CI server: http://nnsuite.mooo.com 

* When:  Whenever a PR is submitted,

**Comment by leemgs** [comment]
@ohsewon Please summarize the progress status of this issue.

**Comment by ohsewon** [comment]
try to apply virtual usb camera device using 'insmod'.
below is trial and error.
1. using openssl
```bash
$ mkdir ~/.ssl
$ cd ~/.ssl
$ openssl req -new -x509 -newkey rsa:2048 -keyout MOK.priv -outform DER -out MOK.der -nodes  -subj "/CN=Owner/"
$ chmod 600 MOK.*
$ sudo /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ~/.ssl/MOK.priv ~/.ssl/MOK.der 
  v4l2loopback.ko
$ sudo apt-get install mokutil
$ sudo mokutil --import ~/.ssl/MOK.der
EFI variables are not supported on this system ubuntu <- error
$ sudo insmod v4l2loopback.ko <-- doens't work
insmod: ERROR: could not insert module v4l2loopback.ko: Unknwon symbol in module
$ sudo dmesg -c
PKCS#7 signature not signed with a trustred key
v4l2loopback: Unkown symbol...
```

2.  make sign key in certs forlder
```bash
$ cd /usr/src/linux-headers-$(uname -r)/certs
$ vi x509.genkey
[ req ]
default_bits = 4096
distinguished_name = req_distinguished_name
prompt = no
string_mask = utf8only
x509_extensions = myexts

[ req_distinguished_name ]
CN = Modules

[ myexts ]
basicConstraints=critical,CA:FALSE
keyUsage=digitalSignature
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
$ openssl req -new -nodes -utf8 -sha512 -days 36500 -batch -x509 -config x509.genkey -outform DER -out signing_key.x509 -keyout signing_key.priv
(manually sign)
$ /usr/src//usr/src/linux-headers-$(uname -r)/scripts/sign-file sha512 /usr/src//usr/src/linux-headers-$(uname -r)/certs/signing_key.pem /usr/src//usr/src/linux-headers-$(uname -r)/certs/signing_key.x509 v4l2loopback.ko
$ sudo insmod v4l2loopback.ko <-- doens't work
insmod: ERROR: could not insert module v4l2loopback.ko: Unknwon symbol in module
$ sudo dmesg -c
PKCS#7 signature not signed with a trustred key
```

ref :
https://gist.github.com/Garoe/74a0040f50ae7987885a0bebe5eda1aa
https://www.kernel.org/doc/html/v4.15/admin-guide/module-signing.html
https://wiki.gentoo.org/wiki/Signed_kernel_module_support

**Comment by leemgs** [comment]
> There is something strange. When I try above, sometimes 'sudo insmod' is working well.
> so, I don't know why it is working or not.

@ohsewon, Do you mean that the insmod command sometimes works normally? However, sometimes it does not work?

> Question is how to sign *.ko with trusted key.
> Goal is 'sudo insmod *.ko' is working well.

@ohsewon , If we can not load v4l2loopback.ko with insmod because it has a bug in case of asigned kernel module, Let's use modprobe command instead of insmod finally.

**Comment by leemgs** [comment]
@wooksong , Could you give us some hints. Welcome any comments. :)

**Comment by leemgs** [comment]
Here is error message in case that we try to run 'insmod' command to load a signed kernel module. 

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

$ sudo insmod /lib/modules/4.4.0-134-generic/updates/dkms/v4l2loopback.ko
insmod: ERROR: could not insert module /lib/modules/4.4.0-134-generic/updates/dkms/v4l2loopback.ko: Unknown symbol in module

$ dmesg
[   64.005389] v4l2loopback: Unknown symbol video_ioctl2 (err 0)
[   64.005437] v4l2loopback: Unknown symbol v4l2_ctrl_handler_init_class (err 0)
[   64.005489] v4l2loopback: Unknown symbol video_devdata (err 0)
[   64.005528] v4l2loopback: Unknown symbol v4l2_ctrl_new_custom (err 0)
[   64.005565] v4l2loopback: Unknown symbol video_unregister_device (err 0)
[   64.005601] v4l2loopback: Unknown symbol video_device_alloc (err 0)
[   64.005640] v4l2loopback: Unknown symbol v4l2_device_register (err 0)
[   64.005689] v4l2loopback: Unknown symbol __video_register_device (err 0)
[   64.005725] v4l2loopback: Unknown symbol v4l2_ctrl_handler_free (err 0)
[   64.005757] v4l2loopback: Unknown symbol v4l2_device_unregister (err 0)
[   64.005789] v4l2loopback: Unknown symbol video_device_release (err 0)

**Comment by leemgs** [comment]
> Question is how to sign *.ko with trusted key.
> Goal is 'sudo insmod *.ko' is working well.
> 

@ohsewon , I have found a solution to fix this issue. 

## My proposal: How to load a signed kernel module with 'insmod' commad

### Step 1: make your own signing key.
```bash
$ sudo su - 
# cd   /usr/src/linux-headers-`uname -r`/certs/
# vi x509.genkey
[ req ]
default_bits = 4096
distinguished_name = req_distinguished_name
prompt = no
string_mask = utf8only
x509_extensions = myexts

[ req_distinguished_name ]
CN = Modules

[ myexts ]
basicConstraints=critical,CA:FALSE
keyUsage=digitalSignature
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid

# openssl req -new -nodes -utf8 -sha512 -days 36500 -batch -x509 -config x509.genkey -outform DER -out signing_key.x509 -keyout signing_key.pem

# exit
```

### Step 2: build a kernel module, Then load it with insmod command. 
```bash
$ git clone  https://github.com/umlaeute/v4l2loopback.git
$ cd v4l2loopback
$ make
$ sudo insmod /lib/modules/`uname -r`/kernel/drivers/media/media.ko  
$ sudo insmod /lib/modules/`uname -r`/kernel/drivers/media/v4l2-core/videodev.ko  
$ sudo insmod ./v4l2loopback.ko 
```

### Evaluation: The test result is okay. 

![image](https://user-images.githubusercontent.com/82404/46949263-c5281400-d0bb-11e8-959a-8623e090f3be.png)

**Comment by ohsewon** [comment]
It is good for me. But, after I testing several times, I realize that it is unnecessary to do step 1/2.
only step 2/2 solves the problem.

**Comment by ohsewon** [comment]
Done by applying ci server
