### ISSUE TITLE
[Bug in Build Infra] Dep-package 'tensorflow' in tizen.org

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#645]
In the build code for Debian/Ubuntu, tensorflow has incorrect code that breaks aarch64/armv7 build in launchpad:

https://git.tizen.org/cgit/platform/upstream/tensorflow/tree/debian/control?h=tizen

```
Build-Depends: debhelper (>=9), sed, zlib1g-dev, cmake (>=3.9), python, git, python-numpy, swig, python-dev, libc6-dev, libc6-dev-i386, unzip
```

Please remove i386 or use architecture-macro.

Related launchpad build log: https://launchpadlibrarian.net/392924175/buildlog_ubuntu-bionic-arm64.tensorflow_1.9.0-0~201810080620~ubuntu18.04.1_BUILDING.txt.gz

```
The following packages have unmet dependencies:
 sbuild-build-depends-tensorflow-dummy : Depends: cmake (>= 3.9) but it is not going to be installed
                                         Depends: libc6-dev-i386 but it is not installable
```

**Comment by again4you** [comment]
After removing `libc6-dev-i386` in Build-Depends, **tensorflow-aarch64** completed to be built on launchpad.net. However, **armhf version** failed to be built because of another issue.
So I am going to close this and create new one.
