### ISSUE TITLE
[CI/apptest] Python apptest can't find nnstreamer plugin.

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#658]
In CI server,  Apptest error message is below.
```bash
** Message: start app..
** Message: finished to load labels, total 1001
Traceback (most recent call last):
  File "nnstreamer_example_filter.py", line 241, in <module>
    example.run_example()
  File "nnstreamer_example_filter.py", line 75, in run_example
    'tensor_filter framework=tensorflow-lite model=' + self.tflite_model + ' ! '
GLib.Error: gst_parse_error: no element "tensor_filter" (1)
```

C tests have no problem. 
Only python test can't find 'tensor_filter' plugin.
Python packages are already installed.

run command: ```python nnstreaemr_example_filter.py```

Can I get a hint about them?

**Comment by myungjoo** [comment]
Please describe the path (```pwd```) of your execution and other environments (from git clone to where you get the error.)

**Comment by myungjoo** [comment]
Anyway, I think you need to do ```$ export GST_PLUGIN_PATH=${the_location_where_you_have_libnnstreamer.so}``` before running the python script.

**Comment by ohsewon** [comment]
I don't change anything, but it is working well today..
Done..
