### ISSUE TITLE
[CD] "This branch has not been deployed" happens per pull request

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#659]
It is strange. Suddenly, "**This branch has not been deployed**" happens whenever a pull request is submitted.

* Message
```bash
This branch has not been deployed
No deployments
```

* Screenshot

![image](https://user-images.githubusercontent.com/82404/47063489-29f78180-d216-11e8-8cef-c132c1b20675.png)

**Comment by leemgs** [comment]
I sent a e-mail to the person in charge via https://github.com/contact.

**Comment by leemgs** [comment]
I got a reply from the Gihub development team as follows.

![screenshot_20181024-180502](https://user-images.githubusercontent.com/82404/47420258-fb028200-d7b8-11e8-8111-e1fcb923d658.png)

**Comment by myungjoo** [comment]
Good. Thanks!
