### ISSUE TITLE
[Test] Evaluating Producer & Consumer with GUI video application

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#660]
Here is  a video app test: producer / consumer

## Testcase 1 ( summary)
   * producer:  $ gst-launch-1.0 videotestsrc ! v4l2sink device=/dev/video0
   * consumer:  $ gst-launch-1.0 v4l2src device=/dev/video0 ! xvimagesink

###  gstreamer: producer
$ ffmpeg -f x11grab -r 15 -s 1280x720 -i :0.0+0,0 -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0

$ gst-launch-1.0 videotestsrc ! v4l2sink device=/dev/video0

$ wget http://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_640_3MG.mp4
$ gst-launch-1.0  filesrc location=./file_example_MP4_640_3MG.mp4 ! decodebin ! videoconvert ! v4l2sink device=/dev/video0

### gstreamer: consumer
$ gst-launch-1.0 v4l2src device=/dev/video0 ! xvimagesink

$ ./nnstreamer_example_filter

**Comment by jaeyun-jung** [comment]
http://gstreamer-devel.966125.n4.nabble.com/xvimagesink-Could-not-initialise-Xv-output-and-No-port-available-td3092246.html

**Comment by leemgs** [comment]
I have summarized my solution as a workaround to solve this issue at https://github.com/nnsuite/nnstreamer/issues/660#issuecomment-430535584. It is experimented on Ubunu 16.04 x86_64 distribution + Windows mobaxterm (vnc session).

**Comment by leemgs** [comment]
@jijoongmoon , @jaeyun-jung  Could you check if my solution  (as a workaround) is okay in your Ubuntu desktop computer?

**Comment by leemgs** [comment]
Resolved.
