### ISSUE TITLE
[Decoder] Property, "output-type" unnecessary?

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#667]
Because the output type is deteremined by "mode", output type doesn't need to be entered with property.
Please consider this and remove the property "output-type" from tensor_decoder if you think so as well.

**Comment by jinhyuck-park** [comment]
I agree with this , 
until now, there are three modes 
1. direct video => output type video
2. image labeling => output type text
3. boundig boxes => output type video
but in fuctional view, these three mode operates differently
not with "output type" but with "mode"
So I will refactory this codes
