### ISSUE TITLE
Camera/Runtest: Is log message normal?

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#685]
I tried to check the execution result of apptest (running nnstreamer with virtual camear + mobilenet model). @ohsewon  Is the log messages normal? Please check it. Then close this issue after doing appropriate activity. 

* Screenshot: 
![image](https://user-images.githubusercontent.com/82404/47330643-ed170900-d6b3-11e8-8823-b50f194d0518.png)

* log message
[nnstreamer-apptest-error.log](https://github.com/nnsuite/nnstreamer/files/2504163/nnstreamer-apptest-error.log)
[nnstreamer-apptest-output.log](https://github.com/nnsuite/nnstreamer/files/2504164/nnstreamer-apptest-output.log)

**Comment by ohsewon** [comment]
done.
