### ISSUE TITLE
[CI] Unit test coverage doesn't update

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#689]
link : http://nnsuite.mooo.com/nnstreamer/ci/taos/ 

Only the date is changed and the contents do not change.
Contents made by old commit.

**Comment by leemgs** [comment]
* Screenshot:
![image](https://user-images.githubusercontent.com/82404/47344156-cae8af80-d6e2-11e8-85f4-56a65258e27b.png)

**Comment by ohsewon** [comment]
Done by https://github.com/nnsuite/TAOS-CI/pull/310
