### ISSUE TITLE
[Custom Filter] Suggest a new `rank_type` for custom filter

### ISSUE THREAD

**Issue by again4you** [nnsuite/nnstreamer#708]
### Problems ###

As custom filter developer of nnstreamer, the shape of tensor is sometimes confused for me. For example, an input image is converted to a tensor by tensor_converter, then its shape is as below
 * **[Channel] [Width] [Height] [Batch]**

In order to update the dimension of output tensor, custom filter developers have to directly use an integer index as below.
* [nnstreamer_customfilter_example_average.c:72](https://github.com/nnsuite/nnstreamer/blob/master/nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c#L72)
```cpp
GstTensorsInfo * out_info;

/* Update output dimension [1] and [2] with new-x, new-y */
out_info->info[0].dimension[1] = 1;
out_info->info[0].dimension[2] = 1;
```

### Possible solution ###

In my opinion, primitive integer index is so confusing that I made lots of mistakes when writing a custom filter of nnstreamer. What about defining a rank_type and use it as below?
```cpp
# type definition
typedef enum _nns_rank_type
{
  NNS_CHANNEL = 0,
  NNS_X_AXIS,
  NNS_Y_AXIS,
  NNS_BATCH,

  NNS_END,
} rank_type;

...
# usage in custom filter
out_info->info[0].dimension[NNS_X_AXIS] = 1;
out_info->info[0].dimension[NNS_Y_AXIS] = 1;

```

### Draft PR ###
I already submit a PR as a first draft (#707). After taking a look and let me know your opinion.

**Comment by myungjoo** [comment]
As discussed earlier, we are not going to add special semantics to specific dimension/rank.
