### ISSUE TITLE
[Filter] tensor-filter properties for tensor dimension and type, are these necessary?

### ISSUE THREAD

**Issue by jaeyun-jung** [nnsuite/nnstreamer#714]
Tensor-Filter properties - input, inputtype, output, outputtype - are defined for tensor dimensions and types.

Is it necessary to write these properties in pipeline?
Now tensor-filter loads tensor info from NN model, so I think these are unnecessary.

**Comment by myungjoo** [comment]
For models with flexible dimensions (using setInputDim()), we can enforce dimensions with properties.

**Comment by jaeyun-jung** [comment]
I understood, these properties can be used to fix tensor info later.
