### ISSUE TITLE
[EPIC/PP2] Android Sample GUI Application

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#724]
Android NNStreamer Sample Application

----

**Comment by leemgs** [comment]
* https://gstreamer.freedesktop.org/documentation/tutorials/android/index.html

**Comment by leemgs** [comment]
* Repository for Android application: https://github.com/nnsuite/nnstreamer-example/tree/master/android

**Comment by leemgs** [comment]
* Issue: A JNI source code  of tutorial-1 can not be run by ndk-build command.
   * https://gitlab.freedesktop.org/gstreamer/gst-docs/issues/27

**Comment by leemgs** [comment]
I have updated the existing action items (for EPIC) above.

**Comment by jaeyun-jung** [comment]
1. install android-studio
2. install ndk (version 12)
3. download gst-tutorial
4. import project and change target api version (24)
5. in jni/Android.mk
   5-1. add mk to build nnstreamer static lib
   ```
   include $(LOCAL_PATH)/Android-nnstreamer-static.mk
   LOCAL_STATIC_LIBRARIES := nnstreamer
   ```
   5-2. add gst-audio dep
   ```
   GSTREAMER_EXTRA_DEPS      := gstreamer-video-1.0 gstreamer-audio-1.0 gobject-2.0
   ```
6. jni/tutorial-3.c 
   6-1.gst_native_init() add code to register nnst
   ```
     GST_PLUGIN_STATIC_REGISTER (nnstreamer);
     init_dv();
   ```
   6-2. app_function() change pipeline
   ```
   "videotestsrc ! videoconvert ! tensor_converter ! tensor_decoder mode=direct_video ! autovideosink"
   ```

**Comment by jaeyun-jung** [comment]
[android-tutorial-nnst.zip](https://github.com/nnsuite/nnstreamer/files/2991755/android-tutorial-nnst.zip)

**Comment by myungjoo** [comment]
Done and uploaded at Play Store.
