### ISSUE TITLE
[Filter/Tensorflow] ambiguity at input/output tensor

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#730]
To get the dimension of the input/output specification, we need to analyze the model.
In `tf-lite`, because we convert `tensorflow` model into `tf-lite` model with the exact input/output tensor and dimension of those, we can get the input/output tensors of the model and dimension easily.
When I analyzed the `frozen_graph.pb` of the object detection model with [`summrize_graph`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#inspecting-graphs) tool of `tensorflow`, however, below result was generated.
```bash
$ bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=/home/helloahn/workspace/tensorflow_c/build/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb
Found 1 possible inputs: (name=image_tensor, type=uint8(4), shape=[?,?,?,3]) 
No variables spotted.
Found 4 possible outputs: (name=num_detections, type=INVALID(0), shape=None) , op=Identity) (name=detection_classes, type=INVALID(0), shape=None) , op=Identity) (name=detection_scores, type=INVALID(0), shape=None) , op=Identity) (name=detection_boxes, type=INVALID(0), shape=None) , op=Identity) 
...

```

We can get just the candidates of input/output tensors, and there is no exact shape except the mendatory value(`3(channels)` in this case of the input tensor).

If you have any idea, please leave comments :)

**Comment by myungjoo** [comment]
This is why  we have setInputDimension callback.

**Comment by myungjoo** [comment]
@helloahn Do you have more questions on this matter?
