### ISSUE TITLE
[Converter] Memory leak occurs unless using 4xN width for input streams.

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#735]
# Issue Description
Unless 4xN width is used for input streams, memory leak occurs.

How to Reproduce
===============
```bash
gst-launch-1.0 videotestsrc ! video/x-raw,width=1921,height=1080,format=RGB ! tensor_converter ! tensor_sink
```
Here is how 'MemFree' of '/proc/meminfo' is changed after running above command.
![memleak](https://user-images.githubusercontent.com/2772376/47771696-a36b9580-dd27-11e8-8bdc-2955f90fb71e.png)

Expected Result
============
If 4xN width is used for input streams, nothing goes wrong.
```bash
gst-launch-1.0 videotestsrc ! video/x-raw,width=1920,height=1080,format=RGB ! tensor_converter ! tensor_sink
```
![memnotleak](https://user-images.githubusercontent.com/2772376/47772013-a87d1480-dd28-11e8-95c8-cac0a27dae78.png)

**Comment by jaeyun-jung** [comment]
it needs gst_buffer_unref in gst_tensor_converter_chain function when,
1. video (remove padding, width % 4 > 0)
2. string (in-buffer size != 1024)

**Comment by jaeyun-jung** [comment]
PR #736  added code to unref old buffer.

**Comment by wooksong** [comment]
After #736, 
```bash 
gst-launch-1.0 videotestsrc ! video/x-raw,width=1921,height=1080,format=RGB ! tensor_converter ! tensor_sink
```
![memnotleak_after_pr](https://user-images.githubusercontent.com/2772376/47776450-c8670500-dd35-11e8-83c0-bafd7dd3b24d.png)

**Comment by jaeyun-jung** [comment]
IMO, this issue is fixed now.
