### ISSUE TITLE
[Filter/Tensorflow] Linking error with protobuf

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#750]
During development of the filter with tensorflow, I'm in trouble with [protobuf](https://github.com/protocolbuffers/protobuf/blob/master/src/README.md).
Tensorflow, connected with protobuf, cannot load its protobuf library properly.

The detail is,
* installed tensorflow, protobuf
* write `cmake` like below for the test
```bash
...

find_package(PkgConfig REQUIRED)
pkg_check_modules(tf REQUIRED tensorflow)
pkg_check_modules(pb REQUIRED protobuf)

...

include_directories(
  ${tf_INCLUDE_DIRS}
  ${pb_INCLUDE_DIRS}
  )

...

add_executable(tfexample
  main.cc
  )

target_link_libraries(tfexample
  ${tf_LIBRARIES}
  ${pb_LIBRARIES}
  )
```
* generated `undefined reference to...` error message
```bash
CMakeFiles/tfexample.dir/main.cc.o: In function `google::protobuf::internal::MapField<tensorflow::NodeDef::NodeDef_AttrEntry, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tensorflow::AttrValue, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)11, 0>::GetMap() const':
main.cc:(.text._ZNK6google8protobuf8internal8MapFieldIN10tensorflow7NodeDef17NodeDef_AttrEntryENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS3_9AttrValueELNS1_14WireFormatLite9FieldTypeE9ELSE_11ELi0EE6GetMapEv[_ZNK6google8protobuf8internal8MapFieldIN10tensorflow7NodeDef17NodeDef_AttrEntryENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS3_9AttrValueELNS1_14WireFormatLite9FieldTypeE9ELSE_11ELi0EE6GetMapEv]+0x14): undefined reference to `google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
collect2: error: ld returned 1 exit status
...
```

**Comment by helloahn** [comment]
Furthermore, since tizen officially supports 2.6.1(old version), we need to find another way to build tensorflow 1.9 with gbs.

**Comment by myungjoo** [comment]
> Furthermore, since tizen officially supports protobuf 2.6.1(old version), we need to find another way to build tensorflow 1.9 with gbs.

What I understand is:
- tensorflow 1.9 @ Tizen uses "downloaded" protobuf (3.x), which is "hard-embedded" in tensorflow.git
- protobuf @ Tizen is 2.x

Then, in fact, the fastest way will be upgrading protobuf in Tizen.. (seriously....)

**Comment by myungjoo** [comment]
In the worst case scenario, you will be required to add protobuf to
- https://build.tizen.org/project/show/devel:AIC:Tizen:5.0:nnsuite
and
- Our internal OBS server.

**Comment by daeinki** [comment]
18. 11. 2. 오후 3:04에 MyungJoo Ham 이(가) 쓴 글:
>> Furthermore, since tizen officially supports protobuf 2.6.1(old version), we need to find another way to build tensorflow 1.9 with gbs.
> 
> What I understand is:
> - tensorflow 1.9 @ Tizen uses "downloaded" protobuf (3.x), which is "hard-embedded" in tensorflow.git
> - protobuf @ Tizen is 2.x
> 
> Then, in fact, the fastest way will be upgrading protobuf in Tizen.. (seriously....)
> 
> You can do it :)  (register an account at tizen.org, submit patches to review.tizen.org, contact maintainers and part leaders ... once you start it, I can help contact them.)
> @daeinki : are you ready to accept newer version of protobuf? 

As far as I know, package owner of Tizen team is checking whether all the tizen modules work properly with the latest protobuf version, so it may be duplicated.

Thanks,
Inki Dae

> > ps. I don't remember when, but protobuf@tizen has a branch of "sandbox/mzx/3.5.2", which has quite recent version of protobuf for Tizen.
> 
>

**Comment by helloahn** [comment]
I'll check the tensorflow package first to decide we need to link protobuf in person :)

**Comment by myungjoo** [comment]
> As far as I know, package owner of Tizen team is checking whether all the tizen modules work properly with the latest protobuf version, so it may be duplicated.

Great! Thanks a lot!
