### ISSUE TITLE
Sleep 60 is overkill. Shorten the check period

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#776]
As you can see in the OBS build log, 
```
[  604s] [1;32m[PASSED][0m [0;34mnnstreamer_mux[0m (29 passed among 29 cases)
[  604s] ==================================================
[  604s] [1;32m[PASSED] [0;34mAll Test Groups (15) Passed![0m
[  604s]          TC Passed: 255 / Failed: 0
[  604s] 
[  637s] ++ ps
[  637s] ++ grep 108569
[  637s] + [[ ! -n '' ]]
[  637s] + break
[  637s] ++ ps
[  637s] ++ grep 108569
[  638s] + [[ -n '' ]]
[  638s] + wait 108569
```

In average, we are wasting 30 seconds for each build because of 60s period.
Let's reduce it... I'd recommend ... what about 10 seconds?

**Comment by leemgs** [comment]
# Reminder:
In order to use 'timeout' command, there is a core-utils package in Tizen platform. But Tizen could not upgrade version of the package because of a license issue. 

Package | License
-- | --
www.gnu.org/software/coreutils/ (latest version) | GNU GPL v3

**Comment by leemgs** [comment]
@ohsewon  As I described a workaround to you, Please submit a PR  to control too long build time with macro (e.g., define build_timeout_level = 0 or 1)
