### ISSUE TITLE
[CI] gbs build: installing security-config & shared-mime-info is too slow since Nove-01-2018

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#785]
It is strange.  gbs build is too slow since Nove-01-2018. This issue is reported by @ohsewon on Nov-03-2018. 

* security-config & shared-mime-info
```bash
.............. omission ............
[  295s] Running libopenblas_pthreads0 %posttrans script
[  295s] [128/283] installing libpcrecpp-8.41-6.1
[  296s] [129/283] installing tzdata-2018f-9.1
[  298s] [130/283] installing elfutils-0.153-3.147
[  300s] [131/283] installing libgnutls-3.3.27-5.9
[  301s] [132/283] installing libtiff-4.0.9-7.3
[  302s] [133/283] installing security-config-1.0-43.1 <------------------- HERE !!!!
[ 1116s] groupadd: group 'dbus' already exists
[ 1116s] [134/283] installing libarchive-3.3.2-5.1
[ 1124s] [135/283] installing shared-mime-info-1.7-5.9<------------------- HERE !!!!
[ 2602s] [136/283] installing gtest-devel-1.8.0-4.7
[ 2604s] [137/283] installing libncurses-6.1-10.38
[ 2606s] [138/283] installing ca-certificates-0.0.4-5.1
[ 2609s] [139/283] installing glibc-devel-2.24-12.9
[ 2610s] [140/283] installing less-466-8.7
[ 2612s] [141/283] installing libicu-devel-60.2-6.1
[ 2614s] [142/283] installing libreadline-5.2-4.131
[ 2615s] [143/283] installing procps-ng-3.3.15-8.1
[ 2617s] [144/283] installing libmount-devel-2.30-10.2
[ 2618s] [145/283] installing perl-5.20.0-6.42
[ 2621s] [146/283] installing libharfbuzz-1.8.1-5.3
[ 2624s] [147/283] installing libsystemd-231-29.1
[ 2629s] [148/283] installing pcre-devel-8.41-6.1
 .............. omission ................
```
* Log file: 
[build_log_784_tizen_x86_64_output.txt](https://github.com/nnsuite/nnstreamer/files/2555661/build_log_784_tizen_x86_64_output.txt)

**Comment by myungjoo** [comment]
We may need to find a way to reuse GBS-ROOT (at least for a week from Monday-Sunday) with a fixed Tizen:Base/Tizen:Unified snapshots (not latest) without --clean option.

Then, a cron service in the CI system will change the snapshot address to more recent one weekly (or bi-weelky) basis. In case there are glitches, we may follow Tizen:Base with about 2~3 weeks latencies. (Need some careful implementation on the logic choosing snapshot)

**Comment by myungjoo** [comment]
Anyway, the current GBS in AWS is way too slow (the above is a workaround and should not be rely on entirely.)

Every package install is slowed extremely. This is not going to be %post script errors in a few packages.
It could be some issues in the AWS instance or Tizen-GBS overall issue.

Please post the effective gbs conf in AWS.

**Comment by myungjoo** [comment]
Or maybe we just have too many GBS/PDEBUILD instances in a single AWS instance, thrashing the qemu-I/O.
Let them wait until other PRs are cleared. (We have per-PR queues, right?)

**Comment by myungjoo** [comment]
![image](https://user-images.githubusercontent.com/1109011/48068044-218ed700-e215-11e8-9763-c69554edb3d8.png)


Plus, let's abort a overwritten PR checks. (PR 762)

**Comment by myungjoo** [comment]
Another point:
```
[  795s] [135/283] installing shared-mime-info-1.7-5.9
[ 1808s] [136/283] installing gtest-devel-1.8.0-4.7
```

And from .spec of shared-mime-info
```
  59 %post
  60 %{_bindir}/update-mime-database %{_datadir}/mime || true
  61 
  62 %lang_package
  63 
  64 %docs_package
```

**Comment by leemgs** [comment]
If this is issue  is resulted from Tizen platform platform, You can report this issue at https://bugs.tizen.org/ (The official Tizen bug management system)

**Comment by ohsewon** [comment]
> @ohsewon Please upload the execution of security-config & shared-mime-info in case that you run 
> "gbs build" in your own Ubuntu PC. Also, attach log file.

In my local ubuntu PC
``` bash 
.............. omission ............
[   27s] [133/283] installing pcre-devel-8.41-6.2
[   27s] [134/283] installing elfutils-0.153-3.134
[   27s] [135/283] installing libgnutls-3.3.27-5.9
[   27s] [136/283] installing security-config-1.0-43.1   <---- here
[   33s] groupadd: group 'dbus' already exists
[   33s] [137/283] installing libarchive-3.3.2-5.2
[   34s] [138/283] installing shared-mime-info-1.7-5.9 <--- here
[   43s] [139/283] installing gcc-6.2.1-28.1
[   44s] [140/283] installing build-mkbaselibs-20120927-3.1
.............. omission ............
```
full log linked: https://github.com/nnsuite/nnstreamer/issues/797

In AWS, /var/www/nnstreamer
```bash
$ sudo gbs build -A armv7l --clean --overwrite --buildroot ./GBS-ROOT/ | sudo tee armv7l
.............. omission ............
[   32s] [133/283] installing pcre-devel-8.41-6.2
[   32s] [134/283] installing elfutils-0.153-3.134
[   32s] [135/283] installing libgnutls-3.3.27-5.9
[   32s] [136/283] installing security-config-1.0-43.1   <---- here
[   38s] groupadd: group 'dbus' already exists
[   38s] [137/283] installing libarchive-3.3.2-5.2
[   39s] [138/283] installing shared-mime-info-1.7-5.9   <---- here
[   55s] [139/283] installing gcc-6.2.1-28.1
[   56s] [140/283] installing build-mkbaselibs-20120927-3.1
[   56s] [141/283] installing libncurses-6.1-10.48
[   56s] [142/283] installing ca-certificates-0.0.4-5.1
.............. omission ............

full log: [armv7l.txt](https://github.com/nnsuite/nnstreamer/files/2560291/armv7l.txt)

**Comment by leemgs** [comment]
@ohsewon Please post the below experiment result additionally. 

1. In my local ubuntu PC: with www-data account 
2. In AWS: with www-data account

**Comment by leemgs** [comment]
Note:

OpenCV requires two packages (syscurity-config, shared-mime-info).

**Comment by myungjoo** [comment]
Let's not focus on improving such peripheral software packages.
As told yesterday, let's simply drop arm/arm64 per-PR unittesting in x64 VMs.
