### ISSUE TITLE
Support MESON build

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#787]
Enable Meson build for GBS/OBS and PDEBUILD.
Then, remove CMake build.

**Comment by leemgs** [comment]
It seems that #831 &  #845 fix this issue. 
@ohsewon Please memorize that you have to write"Fixed issue #xxx" statement in a PR body.

**Comment by myungjoo** [comment]
Meson build confirmed. Next steps will be issued independently
