### ISSUE TITLE
[CI] When ci is overload, unit test is failed(armv7l) 

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#791]
only armv7l and below test('tensor_stream_test.video_split') make this case.

``` bash
[  389s] [ RUN      ] tensor_stream_test.video_split
[  390s] /home/abuild/rpmbuild/BUILD/nnstreamer-0.0.3/tests/nnstreamer_sink/unittest_sink.cpp:3059: Failure
[  390s]       Expected: g_test_data.received
[  390s]       Which is: 3   <-- sometimes value is 4
[  390s] To be equal to: num_buffers
[  390s]       Which is: 5
[  390s] [  FAILED  ] tensor_stream_test.video_split (518 ms)
[  390s] [ RUN      ] tensor_stream_test.video_aggregate_1
```

full log: 
[build_log_782_tizen_armv7l_output.txt](https://github.com/nnsuite/nnstreamer/files/2556050/build_log_782_tizen_armv7l_output.txt)

**Comment by leemgs** [comment]
@ohsewon Please how to reproduce this issue on local PC.

**Comment by myungjoo** [comment]
Duplicated: #751

**Comment by myungjoo** [comment]
Closing this as it's duplicated.

**Comment by leemgs** [comment]
I am not sure that this issue is related to ```cat /proc/sys/kernel/hung_task_timeout_secs
120``` setting.

**Comment by myungjoo** [comment]
This is duplicated. Refer #751 .

**Comment by myungjoo** [comment]
hung_task_timeout has nothing to do with this. It took less than 1 second.

**Comment by ohsewon** [comment]
> @ohsewon Please how to reproduce this issue on local PC.

I don't know either. just copy ci log..
