### ISSUE TITLE
Move example applications to nnstreamer-example

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#795]
As example applications are getting bigger and more dependencies,
let's export them into nnstreamer-example repo.

This will require
1. clean up CMakeLists.txt
2. move files to nnstreamer-example
3. setup nnstreamer-example (rpm / deb / CMake or Meson)
4. ensure nnstreamer-dev is appropriate (you may need to debug -dev packaging)

**Comment by jaeyun-jung** [comment]
Examples are moved to nnstreamer-example repository. (remained custom filters and basic examples for unittest)
Now in nnstreamer-example repository, added build script for rpm, deb using meson.
