### ISSUE TITLE
[EPIC/BC7] Ubuntu ARM instance on Amazon EC2? 

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#817]
We need to survey  again if we can use Ubuntu ARM Server AMI on Amazon EC2 to follow up ARM device. 

* History of ARM Ubuntu image:
   * https://wiki.ubuntu.com/ARM/Server?_ga=2.259654796.766101751.1542014106-42344228.1542014106

**Comment by leemgs** [comment]
It seems that [Scaleway](https://www.scaleway.com/) is the first cloud hosting provider, to my knowledge, to offer ARM-based server. And it is cheap. Let’s try to create a Virtual Private Server (VPS) and configure it to run a website.

* Screenshot:

![image](https://user-images.githubusercontent.com/82404/48337910-9e9fcd80-e6a7-11e8-98d5-3e4623cf4d58.png)

**Comment by myungjoo** [comment]
Looks like we may add one within the bugdet. Nice catch!!!

**Comment by leemgs** [comment]
I reopen this issue because we get the good news as following:

The below new service is announce at re:Invent 2018 Keynote: 
* https://aws.amazon.com/about-aws/whats-new/2018/11/introducing-amazon-ec2-a1-instances/
* https://aws.amazon.com/blogs/aws/new-ec2-instances-a1-powered-by-arm-based-aws-graviton-processors/

**Comment by leemgs** [comment]
## Questions

1. Supported ARM OS: Ubuntu/ARM 16.04 only? Tizen/ARM 5.0???
2. Supported ARM CPU architectures: armv7l, arvm7hf, aarch64,....
3. Please append here.!!!!

**Comment by hyunsikyoon** [comment]
Can we add more question? 
- Does ARM VM on AWS support openCL? What version do they support?

**Comment by myungjoo** [comment]
@hyunsikyoon Normally, that's what users' VM images need to take care of.

**Comment by myungjoo** [comment]
1. Assuming that we supply our own Linux kernel for EC2/ARM,
    1. Do you have specific requirement / manual for configuring kernel for EC2/ARM?
    2. If our kernel hangs (kernel panic or halts), how to recover from it?
    3. (similar to 2) If the supplied kernel always "panics" during boot, how to recover from it?

2. General Performance Characteristics
    1. CPU Type (microarchitecture) / Clock / ...
    2. Main bus type & bandwidth / DRAM specification / ..
    3. Coprocessors? (GPU / VPU / ...) If exists, their SW backend? (OpenCL / CUDA / ...)
    4. Storage device performance characterstics (both sequential and random access)

3. Standard OS or SW Platform Supported
    1. Can we install custom kernel module (*.ko) on Amazon's EC2/ARM standard sw platform?

**Comment by myungjoo** [comment]
No one cares now. Let's drop this.
