### ISSUE TITLE
[Seminar Request] Gstreamer Tracging, Profiling, and Debugging Infrastructure

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#842]
Open4Participation. (please pick this up until 11/22. for scheduling, this can be moved to 1812A after picking up)

By doing this, you will become THE GST TOOL EXPERT in the team. :)

Requested Topic.

1. Using gdb-gst along with nnstreamer
2. Using GST-SHARK along with nnstreamer plugins
3. Using gst-debugger + hawktracerstreamer
    - Performance debugging of a stream pipeline

**Comment by leemgs** [comment]
[Epic: Performance] Support performance measurement facility
   * https://github.com/nnsuite/nnstreamer/issues/132

**Comment by leemgs** [comment]
Refer to ./tools/ folder.
* https://github.com/nnsuite/nnstreamer/tree/master/tools
