### ISSUE TITLE
[packaging/debian] nnstreamer build failure on launchpad.net

### ISSUE THREAD

**Issue by again4you** [nnsuite/nnstreamer#850]
## Issue Description

Since `tensorflow-dev` package is only built for amd64 and arm64 on launchpad.net, nnstreamer for armhf and i386 count not be built.

* https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa/+packages

## Possible solution
* Remove `tensorflow-dev` Build-Depends in control file

**Comment by myungjoo** [comment]
Please remove the dependency on tensorflow-dev for 32bit systems ONLY.

**Comment by again4you** [comment]
Fixed.
