### ISSUE TITLE
[Launchpad] Unit Test Fail in aarch64, arm32, x86_32.

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#877]
Related Log:

https://launchpadlibrarian.net/398472092/buildlog_ubuntu-bionic-i386.nnstreamer_0.0.3-0~201811210943~ubuntu18.04.1_BUILDING.txt.gz

If you request me, I can give you the access previleges to the launchpad recipe.

**Comment by myungjoo** [comment]
Or we can test with gbs:
```
$ gbs build -A i586 --define "unit_test 1" --spec nnstreamer.spec
```

**Comment by myungjoo** [comment]
i586 error in Tizen: due to recent update in opencv at Tizen:Unified
arm64/arm32 error in Tizen/Ubuntu: #882
i586 error in Ubuntu: to be investigated further.

**Comment by myungjoo** [comment]
i586@Tizen : Resolved (fix submitted to Tizen:Unified and being reviewed)
arm64/arm32: Resolved

Remaining: i386@Ubuntu. Mysterious. (OpenCV in Ubuntu i386 appears to have the same issue... wth..)

**Comment by leemgs** [comment]
Let's close this issue.
