### ISSUE TITLE
Fail testcases 12-15 of nnstreamer_filter_custom in my local HostPC

### ISSUE THREAD

**Issue by tyoungroy** [nnsuite/nnstreamer#921]
I cloned nnstreamer and build it with Cmake referring to https://github.com/nnsuite/nnstreamer/blob/master/Documentation/getting-started.md

After installing SSAT, i ran ssat  in "nnstreamer/tests/nnstreamer_filter_custom/" but 26 TCs passed and 5 failed.

>tychung@tychung-ubuntu:/codes/sandbox/ubuntu/nnstreamer/tests/nnstreamer_filter_custom(master)$ ssat 
**
ERROR:/codes/sandbox/ubuntu/nnstreamer/gst/tensor_filter/tensor_filter.c:1120:gst_tensor_filter_transform_caps: assertion failed: (0)
**
ERROR:/codes/sandbox/ubuntu/nnstreamer/gst/tensor_filter/tensor_filter.c:1120:gst_tensor_filter_transform_caps: assertion failed: (0)
**
ERROR:/codes/sandbox/ubuntu/nnstreamer/gst/tensor_filter/tensor_filter.c:1120:gst_tensor_filter_transform_caps: assertion failed: (0)
**
ERROR:/codes/sandbox/ubuntu/nnstreamer/gst/tensor_filter/tensor_filter.c:1120:gst_tensor_filter_transform_caps: assertion failed: (0)
cmp: EOF on testcase15.opencv.average.log which is empty
Test Group nnstreamer_filter_custom Starts.
[PASSED] 0:gst-launch of case 0
[PASSED] 1:gst-launch of case 1
[PASSED] 1:Compare 1
[PASSED] 2:gst-launch of case 2
[PASSED] 2:Compare 2
[PASSED] 3:gst-launch of case 3
[PASSED] 3:Compare 3
[PASSED] 4-1:gst-launch of case 4-1
[PASSED] 4-2:Compare 4-2
[PASSED] 4-3:gst-launch of case 4-3
[PASSED] 4-4:Compare 4-4
[PASSED] 5:gst-launch of case 5
[PASSED] 5:Compare 5
[PASSED] 6:gst-launch of case 6
[PASSED] 6:Golden test comparison
[PASSED] 6:gst-launch of case 6
[PASSED] 7:Golden test comparison
[PASSED] 8:gst-launch of case 8
[PASSED] 9:gst-launch of case 9
[PASSED] 10:gst-launch of case 10
[PASSED] 11:gst-launch of case 11
[PASSED] 11:Golden test comparison
[FAILED][Critical] 12:gst-launch of case 12
[PASSED] 12:Compare 12
[FAILED][Critical] 13:gst-launch of case 13
[PASSED] 13:Golden test comparison
[FAILED][Critical] 14:gst-launch of case 14
[PASSED] 14:Golden test comparison
[PASSED] 15:gst-launch of case 15
[FAILED][Critical] 15:gst-launch of case 15
[FAILED][Critical] 15:Compare 15
[FAILED] Test Group nnstreamer_filter_custom has failed cases (5)
[FAILED] nnstreamer_filter_custom (26 passed among 31 cases)
[FAILED] There are failed test groups! (1)
         TC Passed: 26 / Failed: 5

what does mean "gst_tensor_filter_transform_caps: assertion failed: (0)"? how do i solve it?

**Comment by jijoongmoon** [comment]
The test cases cause the error are related with OpenCV. Could you let us know more specifics about the running env like OS, Opencv version, etc.?

**Comment by again4you** [comment]
@tyoungroy 

First of all, thanks for reporting.

I tested it as you mentioned but all test cases are passed without any errors. 
My test environment and result are as below.
```bash
$ cat /etc/issue
Ubuntu 16.04.5 LTS \n \l
$ pkg-config --modversion opencv
2.4.9.1
$ ssat
...
[PASSED] 13:gst-launch of case 13
[PASSED] 13:Golden test comparison
[PASSED] 14:gst-launch of case 14
[PASSED] 14:Golden test comparison
[PASSED] 15:gst-launch of case 15
[PASSED] 15:gst-launch of case 15
[PASSED] 15:Compare 15
==================================================
[PASSED] Test Group nnstreamer_filter_custom Passed

==================================================

[PASSED] nnstreamer_filter_custom (31 passed among 31 cases)
==================================================
[PASSED] All Test Groups (1) Passed!
         TC Passed: 31 / Failed: 0
```

One of my colleges tested it using OpenCV3 and it passed all the test cases.
In order to handle this issue, I'd like to know your ''detailed'' test environment

**Comment by tyoungroy** [comment]
@again4you, @jijoongmoon,
my env. is 

```
$ cat /etc/issue 
Ubuntu 18.04.1 LTS \n \l
$ pkg-config --modversion gstreamer-1.0 opencv
1.14.1
3.4.2
```
I share how to install nnstreamer and run test.
```
#1. I added PPA,  and installed tensorflow-dev and tensorflow-lite-dev by apt install. 
(https://github.com/nnsuite/nnstreamer/wiki/PPA-for-nnstreamer-&-its-related-modules)
#2. git clone nnstreamer repository
#3. make build directory
#4. cd build
#5. cmake .. 
#6. make
#7. sudo make install
#8. I checked the installed so files in /usr/local/lib and /usr/local/lib/gstreamer-1.0
#9. but linking is broken.  
when i command ldd /usr/local/libnnstreamer_custom_filter_opencv_scaler.so , libnnstreamer.so in /usr/local/lib/gstreamer-1.0/ is not found.
#10. ln - s /usr/local/lib/gstreamer-1.0/libnnstreamer.so /usr/local/lib/libnnstreamer.so 
solve broken linking problem at step #9. 
#11. I back to nnstreamer/tests/nnstreamer_filter_custom/ and 
$ ssat 
[FAILED][Critical] 12:gst-launch of case 12
[PASSED] 12:Compare 12
[FAILED][Critical] 13:gst-launch of case 13
[PASSED] 13:Golden test comparison
[FAILED][Critical] 14:gst-launch of case 14
[PASSED] 14:Golden test comparison
[PASSED] 15:gst-launch of case 15
[FAILED][Critical] 15:gst-launch of case 15
[FAILED][Critical] 15:Compare 15
[FAILED] Test Group nnstreamer_filter_custom has failed cases (5)
[FAILED] nnstreamer_filter_custom (26 passed among 31 cases)
[FAILED] There are failed test groups! (1)
TC Passed: 26 / Failed: 5
```
Please let me know if i did wrong steps.
or is there any installation approach i run test?
(All i need is to run test and dump filtered image(tensor) by opencv)

**Comment by again4you** [comment]
@tyoungroy

I checked the exact same version of **OpenCV 3.4.2** that you mentioned and it works without any errors as below. IMHO, it will works after you set GST_PLUGIN_PATH environment variable.

```bash
$ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

$ pkg-config --modversion gstreamer-1.0 opencv
1.14.1
3.4.2

$ ssat
==================================================

==================================================
    Test Group nnstreamer_filter_custom Starts.
[PASSED] 0:gst-launch of case 0
[PASSED] 1:gst-launch of case 1
[PASSED] 1:Compare 1
[PASSED] 2:gst-launch of case 2
[PASSED] 2:Compare 2
[PASSED] 3:gst-launch of case 3
[PASSED] 3:Compare 3
[PASSED] 4-1:gst-launch of case 4-1
[PASSED] 4-2:Compare 4-2
[PASSED] 4-3:gst-launch of case 4-3
[PASSED] 4-4:Compare 4-4
[PASSED] 5:gst-launch of case 5
[PASSED] 5:Compare 5
[PASSED] 6:gst-launch of case 6
[PASSED] 6:Golden test comparison
[PASSED] 6:gst-launch of case 6
[PASSED] 7:Golden test comparison
[PASSED] 8:gst-launch of case 8
[PASSED] 9:gst-launch of case 9
[PASSED] 10:gst-launch of case 10
[PASSED] 11:gst-launch of case 11
[PASSED] 11:Golden test comparison
[PASSED] 12:gst-launch of case 12
[PASSED] 12:Compare 12
[PASSED] 13:gst-launch of case 13
[PASSED] 13:Golden test comparison
[PASSED] 14:gst-launch of case 14
[PASSED] 14:Golden test comparison
[PASSED] 15:gst-launch of case 15
[PASSED] 15:gst-launch of case 15
[PASSED] 15:Compare 15
==================================================
[PASSED] Test Group nnstreamer_filter_custom Passed

==================================================

[PASSED] nnstreamer_filter_custom (31 passed among 31 cases)
==================================================
[PASSED] All Test Groups (1) Passed!
         TC Passed: 31 / Failed: 0
```


@myungjoo
OK. I will.

**Comment by tyoungroy** [comment]
@again4you,
After settting GST_PLUGIN_PATH and LD_LIBRARY_PATH, it works!
I got all pass. 

```
$ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

$ pkg-config --modversion gstreamer-1.0 opencv
1.14.1
3.4.2

==================================================
    Test Group nnstreamer_filter_custom Starts.
[PASSED] 0:gst-launch of case 0
[PASSED] 1:gst-launch of case 1
[PASSED] 1:Compare 1
[PASSED] 2:gst-launch of case 2
[PASSED] 2:Compare 2
[PASSED] 3:gst-launch of case 3
[PASSED] 3:Compare 3
[PASSED] 4-1:gst-launch of case 4-1
[PASSED] 4-2:Compare 4-2
[PASSED] 4-3:gst-launch of case 4-3
[PASSED] 4-4:Compare 4-4
[PASSED] 5:gst-launch of case 5
[PASSED] 5:Compare 5
[PASSED] 6:gst-launch of case 6
[PASSED] 6:Golden test comparison
[PASSED] 6:gst-launch of case 6
[PASSED] 7:Golden test comparison
[PASSED] 8:gst-launch of case 8
[PASSED] 9:gst-launch of case 9
[PASSED] 10:gst-launch of case 10
[PASSED] 11:gst-launch of case 11
[PASSED] 11:Golden test comparison
[PASSED] 12:gst-launch of case 12
[PASSED] 12:Compare 12
[PASSED] 13:gst-launch of case 13
[PASSED] 13:Golden test comparison
[PASSED] 14:gst-launch of case 14
[PASSED] 14:Golden test comparison
[PASSED] 15:gst-launch of case 15
[PASSED] 15:gst-launch of case 15
[PASSED] 15:Compare 15
==================================================
[PASSED] Test Group nnstreamer_filter_custom Passed

==================================================

[PASSED] nnstreamer_filter_custom (31 passed among 31 cases)
==================================================
[PASSED] All Test Groups (1) Passed!
         TC Passed: 31 / Failed: 0
```

Thank you very much!!
