### ISSUE TITLE
[Converter] Support dynamic cap negotiation between pause-start

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#941]
1. Run a pipeline.
2. Pause a piprline (e.g., stop button of pipeviz)
3. Motify capsfilter before tensor_converter
4. Restart the pipeline
````
ERROR:/source/AutoDrv/NNStreamer/gst/tensor_converter/tensor_converter.c:586:gst_tensor_converter_chain: assertion failed: (self->tensor_configured)
Aborted (core dumped)
```

**Comment by jaeyun-jung** [comment]
assertion in _chain() function, it doesn't get tensor info.
maybe called gst_tensor_converter_change_state() and then resets configured tensor info.

**Comment by jaeyun-jung** [comment]
In tensor-converter gst_tensor_converter_parse_caps()
Remove self->tensor_info = config.info; in the last.

This line updates the property 'input-dim' and makes error when doing caps-negotiation.
I will make a PR for this after changing nnstreamer directory structure.
