### ISSUE TITLE
[Filter] sink-pad must be aware of frame drops / sync.

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#97]
<a href="https://github.sec.samsung.net/myungjoo-ham"><img src="https://github.sec.samsung.net/avatars/u/30515?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [myungjoo-ham](https://github.sec.samsung.net/myungjoo-ham)**
_Friday May 25, 2018 at 04:58 GMT_
_Originally opened as https://github.sec.samsung.net/STAR/nnstreamer/issues/32_

----

The incoming frames for tensor_filter may have high FPS (e.g., 60FPS, 120FPS, ...).

However, tensor_filter is expected to have non-deterministic and slower FPS (e.g., fluctuating between 5 ~ 15 FPS).

Besides, we may have multiple sources with different FPS and/or timing.

According to @heechul-jeon , this could be mitigated by designing sink-pad of NN elements carefully.
We will have to design/modify/implment our own pad for this.

**Comment by myungjoo** [comment]
This is being resolved by multi-stream sync at mux/merge.
