### ISSUE TITLE
[decoder] about the 'mode'

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#985]
I have question about the role of the various modes of tensor_decoder (like bounding_boxes).

For instance, the [`tensordec_boundingbox`](https://github.com/nnsuite/nnstreamer/blob/master/gst/tensor_decoder/tensordec-boundingbox.c) is exactly matched with [ssd_mobilenet_v2_coco.tflite](https://github.com/nnsuite/testcases/blob/master/DeepLearningModels/tensorflow-lite/ssd_mobilenet_v2_coco/ssd_mobilenet_v2_coco.tflite) currently.
For this reason, if we want to use another ssd model, and if it has different graph structure (like the [model for tensorflow](https://github.com/nnsuite/testcases/blob/master/DeepLearningModels/tensorflow/ssdlite_mobilenet_v2/ssdlite_mobilenet_v2.pb)), it won't work properly.

If it is for the example, there is no problem.
However if we want to handle various ssd model with this decoder mode, it can't.

Furthermore, what should I do if I want to make a new example with another ssd model?
Should I make a new mode of `tensor_decoder`? or update the `tensordec_boundingbox` mode to handle another model too?

**Comment by myungjoo** [comment]
For the initial approach, I'd recommend to supply yet another option to ```tensordec_boundingbox```.

**Comment by helloahn** [comment]
Ok I'll try with it.
