### ISSUE TITLE
[PP3] Android/bionic: Building Gstreamer source using Cerbero on Ubuntu

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer#987]
This issue is a sub-item of issue #978 (EPIC)

We have to ready to generate gst-android prebuilt binaries to compile Android applications (C/C++ and JAVA) for NNstreamer.

----
 ### Reference: 
The official manual of Cerbero is available at https://gstreamer.freedesktop.org/. 

* https://gstreamer.freedesktop.org/documentation/installing/building-from-source-using-cerbero.html
* https://gitlab.freedesktop.org/gstreamer/cerbero
* https://github.com/centricular/cerbero-docs/blob/master/start.md

**Comment by leemgs** [comment]
* The archive of the prebuilt gst-android binaries (Experimental)
    - http://nnsuite.mooo.com/prebuilt-gst-android/

**Comment by myungjoo** [comment]
Cerbero sounds like sirBero @mylibero ? 😃
