### ISSUE TITLE
[Unittest] how to pass test cases for the not available framework

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#994]
I made a unit test case for tensorflow with MNIST model.
However, it occurs an error because some of the architectures are not able to use tensorflow (like i586).

The problem is, because ssat run whole of test cases in the `tests` directory, we cannot adjust according to the validation of framework.
Now I'm trying to avoid this problem by checking the architecture or the validation of tensorflow at the `runTest.sh` before running testcases.

Are there any better Ideas?

**Comment by myungjoo** [comment]
In the script, check if tensorflow is available. skip the test if it's not available.
